import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const AckSchema = z.object({
  ok: z.boolean(),
  message: z.string().optional(),
})
export type Ack = z.infer<typeof AckSchema>;
