import { z } from "zod";
import { DisplayNameSchema } from "../../_scalars.js";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const ActorRefSchema = z.object({
  id: z.uuid(),
  displayName: DisplayNameSchema,
  email: z.email().optional(),
})
export type ActorRef = z.infer<typeof ActorRefSchema>;

export const ActorRefMeta = {
  email: { inputType: "email" },
} as const;
