import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const EntitySchema = z
  .object({
    id: z.uuid(),
    createdAt: z.coerce.date(),
    updatedAt: z.coerce.date().optional(),
  })
  .describe("Surrogate primary-key base for all persisted rows.")
export type Entity = z.infer<typeof EntitySchema>;
