import { z } from "zod";
import { SoftDeletableEntitySchema } from "./SoftDeletableEntity.js";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const OwnedEntitySchema = SoftDeletableEntitySchema
  .extend({
    ownerId: z.uuid(),
  })
  .describe("Base for rows owned by an account.")
export type OwnedEntity = z.infer<typeof OwnedEntitySchema>;
