import { z } from "zod";
import { SoftDeletableEntitySchema } from "./SoftDeletableEntity.js";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const OwnedEntitySchema = SoftDeletableEntitySchema
  .safeExtend({
    ownerId: z
      .string()
      .uuid()
      .describe("UUID type - maps to uuid column in PostgreSQL"),
  })
  .describe("Base for rows owned by an account.")
export type OwnedEntity = z.infer<typeof OwnedEntitySchema>;
