import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const PageInfoSchema = z.object({
  nextPageToken: z.string().optional(),
  totalCount: z.string().regex(/^-?\d+$/).optional(),
})
export type PageInfo = z.infer<typeof PageInfoSchema>;
