import { z } from "zod";
import { PageSizeSchema } from "../../_scalars.js";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const PageRequestSchema = z.object({
  pageSize: PageSizeSchema,
  pageToken: z.string().optional(),
})
export type PageRequest = z.infer<typeof PageRequestSchema>;
