import { z } from "zod";
import { EntitySchema } from "./Entity.js";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const SoftDeletableEntitySchema = EntitySchema
  .extend({
    deletedAt: z.coerce.date().optional(),
  })
  .describe("Base for rows that should support soft deletion.")
export type SoftDeletableEntity = z.infer<typeof SoftDeletableEntitySchema>;
