# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from typing import Any, TYPE_CHECKING
from uuid import UUID, uuid4
from datetime import datetime
from enum import Enum

from sqlalchemy import Column, DateTime, Enum as SAEnum, ForeignKey, Index, Text, func
from sqlalchemy.dialects.postgresql import JSONB
from sqlmodel import Field, Relationship, SQLModel

if TYPE_CHECKING:
    from ..accounts.user import User


class WorldVisibility(str, Enum):
    """Auto-generated enum for world_visibility."""

    private = "private"
    unlisted = "unlisted"
    public = "public"


class SafetyRating(str, Enum):
    """Auto-generated enum for safety_rating."""

    general = "general"
    teen = "teen"
    mature = "mature"


class World(SQLModel, table=True):
    """A player-created world that owns story trees and reusable content pools."""

    __tablename__ = "worlds"  # type: ignore
    __table_args__ = (
        Index("worlds_owner_id_created_at_idx", "owner_id", "created_at"),
        Index("worlds_visibility_deleted_at_idx", "visibility", "deleted_at"),
    )

    # Unique identifier shared by most persisted records.
    id: UUID = Field(
        default_factory=uuid4,
        primary_key=True,
        sa_column_kwargs={
            "comment": "Unique identifier shared by most persisted records."
        },
    )
    # Timestamp when the record was created.
    created_at: datetime = Field(
        sa_column=Column(
            DateTime(timezone=True),
            nullable=False,
            server_default=func.now(),
            comment="Timestamp when the record was created.",
        )
    )
    # Timestamp of the last update.
    updated_at: datetime | None = Field(
        default=None,
        sa_column=Column(
            DateTime(timezone=True), comment="Timestamp of the last update."
        ),
    )
    # Soft delete marker for archival workflows.
    deleted_at: datetime | None = Field(
        default=None,
        sa_column=Column(
            DateTime(timezone=True),
            comment="Soft delete marker for archival workflows.",
            index=True,
        ),
    )
    # Display name of the world. Referenced by forms and collaboration models through lookup types.
    name: str = Field(
        index=True,
        max_length=200,
        sa_column_kwargs={
            "nullable": False,
            "comment": "Display name of the world. Referenced by forms and collaboration models through lookup types.",
        },
    )
    # Stable human-readable slug used by cross-namespace references.
    slug: str = Field(
        unique=True,
        max_length=80,
        sa_column_kwargs={
            "nullable": False,
            "comment": "Stable human-readable slug used by cross-namespace references.",
        },
    )
    # System prompt used to guide AI generation within the world.
    prompt: str = Field(
        sa_column=Column(
            Text,
            nullable=False,
            comment="System prompt used to guide AI generation within the world.",
        )
    )
    # Who can discover and join this world.
    visibility: WorldVisibility = Field(
        sa_column=Column(
            SAEnum(WorldVisibility),
            nullable=False,
            index=True,
            server_default="private",
            comment="Who can discover and join this world.",
        )
    )
    # Content safety classification for moderation and parental controls.
    safety_rating: SafetyRating = Field(
        sa_column=Column(
            SAEnum(SafetyRating),
            nullable=False,
            index=True,
            server_default="teen",
            comment="Content safety classification for moderation and parental controls.",
        )
    )
    # Optional JSON settings payload for custom generation behavior.
    settings: dict[str, Any] | None = Field(
        default=None,
        sa_column=Column(
            JSONB,
            comment="Optional JSON settings payload for custom generation behavior.",
        ),
    )
    owner_id: UUID = Field(
        sa_column=Column(
            ForeignKey("users.id", ondelete="CASCADE", onupdate="CASCADE"),
            nullable=False,
            index=True,
        )
    )

    # ─── Relationships ─────────────────────
    # User who owns and manages this world.
    owner: User | None = Relationship()
