import { z } from "zod";
import { StringPairSchema } from "../shared/StringPair.js";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const AuditEventViewSchema = z.object({
  id: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  actorId: z
    .string()
    .uuid()
    .optional()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  action: z.string(),
  resourceType: z.string(),
  resourceId: z
    .string()
    .uuid()
    .optional()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  severity: z.union([
    z.literal(0),
    z.literal(1),
    z.literal(2),
    z.literal(3),
    z.literal(4),
    z.literal(5)
  ]),
  createdAtIso: z.string(),
  metadata: z.array(StringPairSchema),
})
export type AuditEventView = z.infer<typeof AuditEventViewSchema>;
