import { z } from "zod";
import { AuditEventViewSchema } from "./AuditEventView.js";
import { PageInfoSchema } from "../shared/PageInfo.js";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const QueryAuditEventsResponseSchema = z.object({
  events: z.array(AuditEventViewSchema),
  page: PageInfoSchema,
})
export type QueryAuditEventsResponse = z.infer<typeof QueryAuditEventsResponseSchema>;
