import { z } from "zod";
import { PageRequestSchema } from "../shared/PageRequest.js";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const QueryAuditEventsRequestSchema = z.object({
  actorId: z
    .string()
    .uuid()
    .optional()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  resourceType: z.string().optional(),
  resourceId: z
    .string()
    .uuid()
    .optional()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  actionPrefix: z.string().optional(),
  page: PageRequestSchema,
})
export type QueryAuditEventsRequest = z.infer<typeof QueryAuditEventsRequestSchema>;
