// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package characters

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/datatypes"
	"gorm.io/gorm"

	demo_game_platform_worlds "github.com/demo-user/demo/demo/game_platform/worlds"
)

// Npc Non-player character belonging to a world.
type Npc struct {
	// Unique identifier shared by most persisted records.
	ID uuid.UUID `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid();comment:Unique identifier shared by most persisted records." json:"id"`
	// Timestamp when the record was created.
	CreatedAt time.Time `gorm:"column:created_at;type:timestamptz;autoCreateTime;not null;comment:Timestamp when the record was created." json:"createdAt"`
	// Timestamp of the last update.
	UpdatedAt *time.Time `gorm:"column:updated_at;type:timestamptz;comment:Timestamp of the last update." validate:"omitempty" json:"updatedAt,omitempty"`
	// Soft delete marker for archival workflows.
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;index;comment:Soft delete marker for archival workflows." json:"deletedAt"`
	// Foreign key to the owning world.
	WorldID uuid.UUID `gorm:"column:world_id;type:uuid;not null;index:npcs_world_id_idx;index:npcs_world_id_name_idx,priority:1;comment:Foreign key to the owning world." validate:"required" json:"worldId"`
	// Name of the NPC - indexed for lookup.
	Name string `gorm:"column:name;type:varchar(200);not null;index:npcs_name_idx;index:npcs_world_id_name_idx,priority:2;comment:Name of the NPC - indexed for lookup." validate:"required,max=200" json:"name"`
	// Narrative description used in AI generation.
	Description string `gorm:"column:description;type:text;not null;comment:Narrative description used in AI generation." validate:"required" json:"description"`
	// Optional structured traits used during prompt assembly.
	Traits *datatypes.JSON `gorm:"column:traits;type:jsonb;comment:Optional structured traits used during prompt assembly." validate:"omitempty" json:"traits,omitempty"`

	// ─── Relationships ─────────────────────
	World demo_game_platform_worlds.World `gorm:"foreignKey:WorldID;references:ID;constraint:OnDelete:CASCADE,OnUpdate:CASCADE" json:"world"`
}

// TableName returns the table name for Npc.
func (Npc) TableName() string {
	return "npcs"
}
