# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from datetime import datetime

from sqlalchemy import Column, DateTime
from sqlmodel import Field, SQLModel
from .entity import Entity



class SoftDeletableEntity(Entity):
    """Base for rows that should support soft deletion."""


    deleted_at: datetime | None = Field(default=None, sa_column=Column(DateTime(timezone=True), index=True))
