# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from typing import Any, TYPE_CHECKING
from uuid import UUID
from datetime import datetime
from enum import Enum

from sqlalchemy import Column, DateTime, Enum as SAEnum, ForeignKey
from sqlalchemy.dialects.postgresql import JSONB, UUID as PG_UUID
from sqlmodel import Field, Relationship, SQLModel
from ..shared.entity import Entity


if TYPE_CHECKING:
    from .assistant_task import AssistantTask


class ApprovalDecision(str, Enum):
    """Auto-generated enum for approval_decision."""

    pending = "pending"
    approved = "approved"
    rejected = "rejected"


class AssistantApproval(Entity, table=True):
    """Approval gate before an assistant mutates or shares vault content."""

    __tablename__ = "assistant_approvals" # type: ignore

    task_id: UUID = Field(sa_column=Column(PG_UUID(as_uuid=True), ForeignKey("assistant_tasks.id", ondelete="CASCADE"), nullable=False, index=True))
    action: str = Field(max_length=160, sa_column_kwargs={"nullable": False})
    resource_type: str = Field(max_length=80, sa_column_kwargs={"nullable": False})
    resource_id: UUID = Field(sa_column=Column(PG_UUID(as_uuid=True), nullable=False))
    proposal_json: Any = Field(sa_column=Column(JSONB, nullable=False))
    decision: ApprovalDecision = Field(sa_column=Column(SAEnum(ApprovalDecision), nullable=False, server_default="pending"))
    decided_by: UUID | None = Field(default=None, sa_column=Column(PG_UUID(as_uuid=True)))
    decided_at: datetime | None = Field(default=None, sa_column=Column(DateTime(timezone=True)))

    # ─── Relationships ─────────────────────
    task: AssistantTask | None = Relationship()
