# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from typing import TYPE_CHECKING
from datetime import datetime
from enum import Enum

from sqlalchemy import Column, DateTime, Enum as SAEnum
from sqlmodel import Field, Relationship, SQLModel
from ..shared.owned_entity import OwnedEntity


if TYPE_CHECKING:
    from ..identity.user_account import UserAccount


class ConversationState(str, Enum):
    """Auto-generated enum for conversation_state."""

    active = "active"
    archived = "archived"


class AssistantConversation(OwnedEntity, table=True):
    """User-facing conversation. Tool calls are runtime events, not primary tables."""

    __tablename__ = "assistant_conversations" # type: ignore

    title: str = Field(max_length=200, sa_column_kwargs={"nullable": False})
    state: ConversationState = Field(sa_column=Column(SAEnum(ConversationState), nullable=False, server_default="active"))
    last_message_at: datetime | None = Field(default=None, sa_column=Column(DateTime(timezone=True)))

    # ─── Relationships ─────────────────────
    owner: UserAccount | None = Relationship()
