# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from uuid import UUID
from enum import Enum

from pydantic import BaseModel, Field


class ConversationStateCode(int, Enum):
    """Auto-generated enum for conversation_state_code."""

    conversation_state_unspecified = 0
    active = 1
    archived = 2


class ConversationView(BaseModel):
    """ConversationView"""

    id: UUID = Field(...)
    owner_id: UUID = Field(...)
    title: str = Field(...)
    state: ConversationStateCode = Field(...)
    last_message_at_iso: str | None = Field(None)
