# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from uuid import UUID
from enum import Enum

from pydantic import BaseModel, Field


class MessageRoleCode(int, Enum):
    """Auto-generated enum for message_role_code."""

    message_role_unspecified = 0
    user = 1
    assistant = 2
    system = 3


class MessageView(BaseModel):
    """MessageView"""

    id: UUID = Field(...)
    conversation_id: UUID = Field(...)
    role: MessageRoleCode = Field(...)
    content: str = Field(...)
    created_at_iso: str = Field(...)
