import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const PublicUserSchema = z
  .object({
    id: z.uuid(),
    email: z.email().max(320),
    displayName: z.string().max(100),
    avatarUrl: z.url().max(512).optional(),
    preferredLocale: z.string().max(16).optional(),
    credits: z.number().int(),
    isActive: z.boolean(),
  })

    .describe("Public user record with sensitive and operational fields removed. Kept explicit so generated form schemas stay free of table-only relations.")
export type PublicUser = z.infer<typeof PublicUserSchema>;

export const PublicUserMeta = {
  email: { inputType: "email" },
  avatarUrl: { inputType: "url" },
} as const;
