import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const ApprovalRequestViewSchema = z.object({
  id: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  taskId: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  action: z.string(),
  resourceType: z.string(),
  resourceId: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  proposalJson: z
    .string()
    .describe("JSON binary - maps to JSONB column in PostgreSQL"),
  decision: z.union([z.literal(0), z.literal(1), z.literal(2), z.literal(3)]),
})
export type ApprovalRequestView = z.infer<typeof ApprovalRequestViewSchema>;
