import { z } from "zod";
import { ConversationViewSchema } from "./ConversationView.js";
import { MessageViewSchema } from "./MessageView.js";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const AssistantReplySchema = z.object({
  conversation: ConversationViewSchema,
  messages: z.array(MessageViewSchema),
})
export type AssistantReply = z.infer<typeof AssistantReplySchema>;
