import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const AssistantTaskViewSchema = z.object({
  id: z.uuid(),
  conversationId: z.uuid(),
  taskType: z.string(),
  objective: z.string(),
  status: z.union([
    z.literal(0),
    z.literal(1),
    z.literal(2),
    z.literal(3),
    z.literal(4),
    z.literal(5),
    z.literal(6)
  ]),
  targetNodeId: z.uuid().optional(),
  resultSummary: z.string().optional(),
})
export type AssistantTaskView = z.infer<typeof AssistantTaskViewSchema>;
