import { z } from "zod";
import { ApprovalRequestViewSchema } from "./ApprovalRequestView.js";
import { AssistantTaskViewSchema } from "./AssistantTaskView.js";
import { MessageViewSchema } from "./MessageView.js";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const AssistantEventSchema = z.object({
  conversationId: z.uuid(),
  task: AssistantTaskViewSchema.optional(),
  message: MessageViewSchema.optional(),
  approval: ApprovalRequestViewSchema.optional(),
})
export type AssistantEvent = z.infer<typeof AssistantEventSchema>;
