import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const ConversationViewSchema = z.object({
  id: z.uuid(),
  ownerId: z.uuid(),
  title: z.string(),
  state: z.union([z.literal(0), z.literal(1), z.literal(2)]),
  lastMessageAtIso: z.string().optional(),
})
export type ConversationView = z.infer<typeof ConversationViewSchema>;
