import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const MessageViewSchema = z.object({
  id: z.uuid(),
  conversationId: z.uuid(),
  role: z.union([z.literal(0), z.literal(1), z.literal(2), z.literal(3)]),
  content: z.string(),
  createdAtIso: z.string(),
})
export type MessageView = z.infer<typeof MessageViewSchema>;
