import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const SendMessageRequestSchema = z.object({
  conversationId: z.uuid(),
  senderId: z.uuid(),
  content: z.string(),
})
export type SendMessageRequest = z.infer<typeof SendMessageRequestSchema>;
