import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const SendMessageRequestSchema = z.object({
  conversationId: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  senderId: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  content: z.string(),
})
export type SendMessageRequest = z.infer<typeof SendMessageRequestSchema>;
