import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const StartAssistantTaskRequestSchema = z.object({
  conversationId: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  requestedBy: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  taskType: z.string(),
  objective: z.string(),
  targetNodeId: z
    .string()
    .uuid()
    .optional()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
})
export type StartAssistantTaskRequest = z.infer<typeof StartAssistantTaskRequestSchema>;
