import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const SubmitApprovalDecisionRequestSchema = z.object({
  approvalId: z.uuid(),
  decidedBy: z.uuid(),
  decision: z.union([z.literal(0), z.literal(1), z.literal(2), z.literal(3)]),
})
export type SubmitApprovalDecisionRequest = z.infer<typeof SubmitApprovalDecisionRequestSchema>;
