import { z } from "zod";
import { AssistantEventSchema } from "./AssistantEvent.js";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const WatchConversationEventSchema = z.object({
  occurredAtIso: z.string(),
  event: AssistantEventSchema,
})
export type WatchConversationEvent = z.infer<typeof WatchConversationEventSchema>;
