import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const WatchConversationRequestSchema = z.object({
  conversationId: z.uuid(),
  requesterId: z.uuid(),
})
export type WatchConversationRequest = z.infer<typeof WatchConversationRequestSchema>;
