# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from pydantic import BaseModel, EmailStr, Field


class CreateInvitationForm(BaseModel):
    """Form payload for creating an invitation. Uses `@data` instead of `@table` - no DB schema is generated.  `::type` rule for decorators that require a `Scalar` target (e.g. `@inputType`): - Direct-scalar field  (`message?: text`)  → `@@dec(Form.message::type, ...)` `::type` resolves to the `text` scalar directly. ✓ - Lookup-typed field (`worldPrompt: World.prompt`) → `Form.worldPrompt::type` resolves to the source `ModelProperty` (`World.prompt`), NOT the scalar. Go one level deeper via the source property: `@@dec(World.prompt::type, ...)`. ✓"""

    # Email address of the person being invited. Lookup type: inherits @maxLength(320) and @format("email") from User.email. @title and @placeholder target ModelProperty - apply inline as normal.
    invitee_email: EmailStr = Field(
        ...,
        max_length=320,
        title="Invitee Email",
        description='Email address of the person being invited. Lookup type: inherits @maxLength(320) and @format("email") from User.email. @title and @placeholder target ModelProperty - apply inline as normal.',
        json_schema_extra={"placeholder": "friend@example.com"},
    )
    # Name of the world to invite into. Lookup type: inherits @maxLength(200) from World.name.
    world_name: str = Field(
        ...,
        max_length=200,
        title="World Name",
        description="Name of the world to invite into. Lookup type: inherits @maxLength(200) from World.name.",
        json_schema_extra={"placeholder": "Select or type a world name"},
    )
    # Prompt text for the target world. Lookup type whose source scalar is `text` (custom, not a built-in) - used below to demonstrate `@@inputType` via `World.prompt::type`.
    world_prompt: str = Field(
        ...,
        title="World Prompt",
        description="Prompt text for the target world. Lookup type whose source scalar is `text` (custom, not a built-in) - used below to demonstrate `@@inputType` via `World.prompt::type`.",
    )
    # Optional personal message included in the invitation. Direct custom scalar (`text`) - @inputType applied via `::type` below.
    message: str | None = Field(
        None,
        title="Personal Message",
        description="Optional personal message included in the invitation. Direct custom scalar (`text`) - @inputType applied via `::type` below.",
        json_schema_extra={"placeholder": "Write a short note to your invitee…"},
    )
