# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from typing import Any, TYPE_CHECKING
from uuid import UUID, uuid4
from datetime import datetime

from sqlalchemy import Column, DateTime, Index, Text, func
from sqlalchemy.dialects.postgresql import JSONB
from sqlmodel import Field, Relationship, SQLModel

if TYPE_CHECKING:
    from .world import World


class Npc(SQLModel, table=True):
    """Non-player character belonging to a world"""

    __tablename__ = "npcs"  # type: ignore
    __table_args__ = (Index("npcs_world_id_name_idx", "world_id", "name"),)

    # Unique identifier - use
    id: UUID = Field(
        default_factory=uuid4,
        primary_key=True,
        sa_column_kwargs={"comment": "Unique identifier - use"},
    )
    # Timestamp when the record was created
    created_at: datetime = Field(
        sa_column=Column(
            DateTime(timezone=True),
            nullable=False,
            server_default=func.now(),
            comment="Timestamp when the record was created",
        )
    )
    # Timestamp of the last update - omit in extending model to skip
    updated_at: datetime | None = Field(
        default=None,
        sa_column=Column(
            DateTime(timezone=True),
            comment="Timestamp of the last update - omit in extending model to skip",
        ),
    )
    # Soft delete timestamp - null if active, set to deletion time when "deleted".
    deleted_at: datetime | None = Field(
        default=None,
        sa_column=Column(
            DateTime(timezone=True),
            comment='Soft delete timestamp - null if active, set to deletion time when "deleted".',
            index=True,
        ),
    )
    # Name of the NPC - indexed for lookup, max 200 characters
    name: str = Field(
        index=True,
        max_length=200,
        sa_column_kwargs={
            "nullable": False,
            "comment": "Name of the NPC - indexed for lookup, max 200 characters",
        },
    )
    # Narrative description used in AI generation
    description: str = Field(
        sa_column=Column(
            Text, nullable=False, comment="Narrative description used in AI generation"
        )
    )
    # Optional JSON object holding personality traits and attributes
    traits: dict[str, Any] | None = Field(
        default=None,
        sa_column=Column(
            JSONB,
            comment="Optional JSON object holding personality traits and attributes",
        ),
    )
    world_id: UUID = Field(
        foreign_key="worlds.id", sa_column_kwargs={"nullable": False}
    )

    # ─── Relationships ─────────────────────
    # World this NPC belongs to - cascades deletion
    world: World | None = Relationship(back_populates="npcs")
