# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from typing import TYPE_CHECKING
from uuid import UUID, uuid4
from datetime import datetime
from decimal import Decimal
from enum import Enum

from sqlalchemy import Column, DateTime, Enum as SAEnum, Index, Numeric, func
from sqlmodel import Field, Relationship, SQLModel

if TYPE_CHECKING:
    from .user import User


class SubscriptionPlan(str, Enum):
    """Auto-generated enum for subscription_plan."""

    free = "free"
    basic = "basic"
    premium = "premium"
    enterprise = "enterprise"


class Subscription(SQLModel, table=True):
    """User subscription plan"""

    __tablename__ = "subscriptions"  # type: ignore
    __table_args__ = (
        Index("subscriptions_user_id_is_active_idx", "user_id", "is_active"),
    )

    # Unique identifier - use
    id: UUID = Field(
        default_factory=uuid4,
        primary_key=True,
        sa_column_kwargs={"comment": "Unique identifier - use"},
    )
    # Timestamp when the record was created
    created_at: datetime = Field(
        sa_column=Column(
            DateTime(timezone=True),
            nullable=False,
            server_default=func.now(),
            comment="Timestamp when the record was created",
        )
    )
    # Timestamp of the last update - omit in extending model to skip
    updated_at: datetime | None = Field(
        default=None,
        sa_column=Column(
            DateTime(timezone=True),
            comment="Timestamp of the last update - omit in extending model to skip",
        ),
    )
    # Soft delete timestamp - null if active, set to deletion time when "deleted".
    deleted_at: datetime | None = Field(
        default=None,
        sa_column=Column(
            DateTime(timezone=True),
            comment='Soft delete timestamp - null if active, set to deletion time when "deleted".',
            index=True,
        ),
    )
    # Subscription plan tier - determines access level and billing. Indexed for fast filtering by plan type.
    plan: SubscriptionPlan = Field(
        sa_column=Column(
            SAEnum(SubscriptionPlan),
            nullable=False,
            index=True,
            comment="Subscription plan tier - determines access level and billing. Indexed for fast filtering by plan type.",
        )
    )
    # Monthly price stored as NUMERIC(10,2) to avoid floating-point rounding errors. Use @precision(10, 2) - do NOT use float or double for monetary values.
    monthly_price: Decimal = Field(
        sa_column=Column(
            Numeric(10, 2),
            nullable=False,
            comment="Monthly price stored as NUMERIC(10,2) to avoid floating-point rounding errors. Use @precision(10, 2) - do NOT use float or double for monetary values.",
        )
    )
    # Start date of the subscription period
    start_date: datetime = Field(
        sa_column=Column(
            DateTime(timezone=True),
            nullable=False,
            comment="Start date of the subscription period",
        )
    )
    # Optional end date - null means the subscription is open-ended
    end_date: datetime | None = Field(
        default=None,
        sa_column=Column(
            DateTime(timezone=True),
            comment="Optional end date - null means the subscription is open-ended",
        ),
    )
    # Quick flag for access-control checks without date comparisons
    is_active: bool = Field(
        sa_column_kwargs={
            "nullable": False,
            "server_default": "true",
            "comment": "Quick flag for access-control checks without date comparisons",
        }
    )
    # FK field for the owning user
    user_id: UUID = Field(
        foreign_key="users.id",
        sa_column_kwargs={"nullable": False, "comment": "FK field for the owning user"},
    )

    # ─── Relationships ─────────────────────
    # Owning user - cascades deletion to subscriptions when the user is removed
    user: User | None = Relationship(back_populates="subscriptions")
