# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from typing import TYPE_CHECKING
from uuid import UUID, uuid4
from datetime import datetime

from sqlalchemy import Column, DateTime, UniqueConstraint, func
from sqlmodel import Field, Relationship, SQLModel

if TYPE_CHECKING:
    from .world import World


class Tag(SQLModel, table=True):
    """Tag used to classify and filter content pool entries. The (world_id, name) pair is globally unique per world."""

    __tablename__ = "tags"  # type: ignore
    __table_args__ = (
        UniqueConstraint("world_id", "name", name="tags_world_id_name_unique"),
    )

    # Unique identifier - use
    id: UUID = Field(
        default_factory=uuid4,
        primary_key=True,
        sa_column_kwargs={"comment": "Unique identifier - use"},
    )
    # Timestamp when the record was created
    created_at: datetime = Field(
        sa_column=Column(
            DateTime(timezone=True),
            nullable=False,
            server_default=func.now(),
            comment="Timestamp when the record was created",
        )
    )
    # Timestamp of the last update - omit in extending model to skip
    updated_at: datetime | None = Field(
        default=None,
        sa_column=Column(
            DateTime(timezone=True),
            comment="Timestamp of the last update - omit in extending model to skip",
        ),
    )
    # Soft delete timestamp - null if active, set to deletion time when "deleted".
    deleted_at: datetime | None = Field(
        default=None,
        sa_column=Column(
            DateTime(timezone=True),
            comment='Soft delete timestamp - null if active, set to deletion time when "deleted".',
            index=True,
        ),
    )
    # Tag name - max 100 characters, unique within its world
    name: str = Field(
        max_length=100,
        sa_column_kwargs={
            "nullable": False,
            "comment": "Tag name - max 100 characters, unique within its world",
        },
    )
    # Category used to group related tags - indexed for filtering, max 50 characters
    category: str = Field(
        index=True,
        max_length=50,
        sa_column_kwargs={
            "nullable": False,
            "comment": "Category used to group related tags - indexed for filtering, max 50 characters",
        },
    )
    world_id: UUID = Field(
        foreign_key="worlds.id", sa_column_kwargs={"nullable": False}
    )

    # ─── Relationships ─────────────────────
    # World this tag belongs to - cascades deletion
    world: World | None = Relationship(back_populates="tags")
