import { describe, expect, it } from "vitest";
import { emitZodFile } from "./utils.jsx";

describe("Zod @data model generation", () => {
  it("generates schema variable declaration with correct name", async () => {
    const output = await emitZodFile(
      `
      @data("User form")
      model CreateUserForm {
        name: string;
        email: string;
      }
    `,
      "CreateUserForm.ts",
    );

    // Should have PascalCase schema name
    expect(output).toContain("CreateUserFormSchema");
  });

  it("generates z.object() as the base schema", async () => {
    const output = await emitZodFile(
      `
      @data("Form")
      model TestForm {
        name: string;
      }
    `,
      "TestForm.ts",
    );

    expect(output).toContain("z.object(");
  });

  it("generates type alias using z.infer", async () => {
    const output = await emitZodFile(
      `
      @data("Form")
      model TestForm {
        name: string;
      }
    `,
      "TestForm.ts",
    );

    expect(output).toContain("z.infer<typeof");
    expect(output).toContain("export type TestForm");
  });

  it("generates optional fields with .optional()", async () => {
    const output = await emitZodFile(
      `
      @data("Form")
      model TestForm {
        name: string;
        bio?: string;
      }
    `,
      "TestForm.ts",
    );

    const bioIndex = output.indexOf("bio:");
    expect(bioIndex).toBeGreaterThan(-1);
    const bioSection = output.slice(bioIndex, bioIndex + 50);
    expect(bioSection).toContain(".optional()");
  });

  it("generates default values with .default()", async () => {
    const output = await emitZodFile(
      `
      @data("Form")
      model TestForm {
        enabled: boolean = true;
        count?: int32 = 0;
      }
    `,
      "TestForm.ts",
    );

    expect(output).toContain(".default(");
  });

  it("generates field with constraints", async () => {
    const output = await emitZodFile(
      `
      @data("Form")
      model TestForm {
        @minLength(1) @maxLength(100) name: string;
      }
    `,
      "TestForm.ts",
    );

    expect(output).toContain(".min(");
    expect(output).toContain(".max(");
  });

  it("generates field with @format constraints", async () => {
    const output = await emitZodFile(
      `
      @data("Form")
      model TestForm {
        @format("email") email: string;
      }
    `,
      "TestForm.ts",
    );

    expect(output).toContain(".email()");
  });
});

describe("Zod model file structure", () => {
  it("generates generated header comment", async () => {
    const output = await emitZodFile(
      `
      @data("Form")
      model User {
        name: string;
      }
    `,
      "User.ts",
    );

    expect(output).toContain("// Code generated by @qninhdt/typespec-orm");
  });

  it("exports schema and type", async () => {
    const output = await emitZodFile(
      `
      @data("Form")
      model User {
        name: string;
      }
    `,
      "User.ts",
    );

    expect(output).toContain("export");
    expect(output).toContain("UserSchema");
  });
});
