// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"

	entschema "entgo.io/ent/schema"
)

// GameEvent Event rule that mutates world state when its conditions are met.
type GameEvent struct {
	ent.Schema
}

func (GameEvent) Annotations() []entschema.Annotation {
	return []entschema.Annotation{
		entsql.Annotation{Table: "game_events"},
		entsql.WithComments(true),
	}
}

func (GameEvent) Mixin() []ent.Mixin {
	return []ent.Mixin{
		WorldOwned{},
	}
}

func (GameEvent) Fields() []ent.Field {
	return []ent.Field{
		field.String("name").
			MaxLen(200).
			Comment("Name of the event - indexed for lookup."),
		field.Text("description").
			Comment("Narrative description used in AI generation."),
		field.JSON("conditions", map[string]any{}).
			Comment("Predicate expression evaluated at runtime.").
			Optional(),
		field.JSON("effects", map[string]any{}).
			Comment("Mutations applied when the event fires.").
			Optional(),
	}
}

func (GameEvent) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("world", World.Type).
			Field("world_id").
			Unique().
			Required().
			Annotations(entsql.OnDelete(entsql.Cascade)),
	}
}

func (GameEvent) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("name"),
	}
}
