// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	entschema "entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
	"github.com/google/uuid"
)

// Invitation Invitation record linking a user email to a shared world. Demonstrates cross-namespace lookup types and relations on the same table.
type Invitation struct {
	ent.Schema
}

func (Invitation) Annotations() []entschema.Annotation {
	return []entschema.Annotation{
		entsql.Annotation{Table: "world_invitations"},
		entsql.WithComments(true),
	}
}

func (Invitation) Mixin() []ent.Mixin {
	return []ent.Mixin{
		Timestamped{},
	}
}

func (Invitation) Fields() []ent.Field {
	return []ent.Field{
		field.String("invitee_email").
			MaxLen(320).
			Comment("Email of the invitee - inherits validators from Accounts.User.email."),
		field.String("redeem_code").
			MaxLen(64).
			Comment("Unique redeem code sent through email or copied in the UI.").
			Unique(),
		field.Enum("status").Values("pending", "accepted", "revoked", "expired").
			Default("pending").
			Comment("Current lifecycle state for the invitation."),
		field.Text("message").
			MaxLen(1000).
			Comment("Optional personal note from the inviter.").
			Optional().
			Nillable(),
		field.Time("expires_at").
			Comment("When the invitation expires, if at all.").
			Optional().
			Nillable(),
		field.Time("accepted_at").
			Comment("When the invitation was accepted by the recipient.").
			Optional().
			Nillable(),
		field.UUID("inviter_id", uuid.UUID{}),
		field.UUID("world_id", uuid.UUID{}),
	}
}

func (Invitation) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("inviter", User.Type).
			Field("inviter_id").
			Unique().
			Required().
			Annotations(entsql.OnDelete(entsql.Cascade)),
		edge.To("world", World.Type).
			Field("world_id").
			Unique().
			Required().
			Annotations(entsql.OnDelete(entsql.Cascade)),
	}
}

func (Invitation) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("status"),
		index.Fields("inviter_id", "status"),
	}
}
