// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	entschema "entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
)

// Location Physical or virtual location available inside a world.
type Location struct {
	ent.Schema
}

func (Location) Annotations() []entschema.Annotation {
	return []entschema.Annotation{
		entsql.Annotation{Table: "locations"},
		entsql.WithComments(true),
	}
}

func (Location) Mixin() []ent.Mixin {
	return []ent.Mixin{
		WorldOwned{},
	}
}

func (Location) Fields() []ent.Field {
	return []ent.Field{
		field.String("name").
			MaxLen(200).
			Comment("Name of the location - indexed for lookup."),
		field.Text("description").
			Comment("Narrative description used in AI generation."),
		field.JSON("coordinates", map[string]any{}).
			Comment("Bounding box or point stored as GeoJSON.").
			Optional(),
	}
}

func (Location) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("world", World.Type).
			Field("world_id").
			Unique().
			Required().
			Annotations(entsql.OnDelete(entsql.Cascade)),
	}
}

func (Location) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("name"),
	}
}
