// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
	"entgo.io/ent/schema/mixin"
	"github.com/google/uuid"
)

// WorldOwned Shared mixin for content that belongs to a specific world. Demonstrates mixin-to-mixin inheritance.
type WorldOwned struct {
	mixin.Schema
}

func (WorldOwned) Mixin() []ent.Mixin {
	return []ent.Mixin{
		Timestamped{},
	}
}

func (WorldOwned) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("world_id", uuid.UUID{}).
			Comment("Foreign key to the owning world."),
	}
}

func (WorldOwned) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("world_id"),
	}
}
