// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
	"github.com/google/uuid"

	entschema "entgo.io/ent/schema"
)


// StoryNode Node in a lazily-generated story tree. Stores the cumulative content-pool IDs inherited from all ancestor nodes.
type StoryNode struct {
	ent.Schema
}

func (StoryNode) Annotations() []entschema.Annotation {
	return []entschema.Annotation{
		entsql.Annotation{Table: "story_nodes"},
		entsql.WithComments(true),
	}
}

func (StoryNode) Mixin() []ent.Mixin {
	return []ent.Mixin{
		WorldOwned{},
	}
}

func (StoryNode) Fields() []ent.Field {
	return []ent.Field{
		field.Int32("depth").
			Default(0).
			Comment("Depth of this node in the story tree - root is 0."),
		field.JSON("pool", map[string]any{}).
			Comment("Content pool inherited from all ancestors."),
		field.JSON("new_content", map[string]any{}).
			Comment("Content introduced by this specific node."),
		field.JSON("child_ids", map[string]any{}).
			Comment("IDs of lazily-expanded child nodes."),
		field.JSON("tags", []string{}).
			Comment("Searchable labels attached to the node for branch discovery."),
		field.UUID("parent_id", uuid.UUID{}).
			Optional().
			Nillable(),
	}
}

func (StoryNode) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("world", World.Type).
			Field("world_id").
			Unique().
			Required().
			Annotations(entsql.OnDelete(entsql.Cascade)),
		edge.From("parent", StoryNode.Type).
			Ref("children").
			Field("parent_id").
			Unique().
			Annotations(entsql.OnDelete(entsql.Cascade)),
		edge.To("children", StoryNode.Type).
			StorageKey(edge.Column("parent_id")).
			Annotations(entsql.OnDelete(entsql.Cascade)),
	}
}

func (StoryNode) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("depth"),
		index.Fields("world_id", "depth"),
	}
}
