// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"

	entschema "entgo.io/ent/schema"
)


// Tag Tag used to classify and filter content pool entries. The (world_id, name) pair is unique per world.
type Tag struct {
	ent.Schema
}

func (Tag) Annotations() []entschema.Annotation {
	return []entschema.Annotation{
		entsql.Annotation{Table: "tags"},
		entsql.WithComments(true),
	}
}

func (Tag) Mixin() []ent.Mixin {
	return []ent.Mixin{
		WorldOwned{},
	}
}

func (Tag) Fields() []ent.Field {
	return []ent.Field{
		field.String("name").
			MaxLen(100).
			Comment("Tag name - unique within a world."),
		field.String("category").
			MaxLen(50).
			Comment("Category used to group related tags."),
	}
}

func (Tag) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("world", World.Type).
			Field("world_id").
			Unique().
			Required().
			Annotations(entsql.OnDelete(entsql.Cascade)),
	}
}

func (Tag) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("category"),
		index.Fields("world_id", "name").
			Unique(),
	}
}
