// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package schema

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
	"entgo.io/ent/schema/mixin"
	"github.com/google/uuid"
)


// Timestamped Base model with common timestamp fields for audit trails. This is a reusable table mixin and is never emitted by itself.
type Timestamped struct {
	mixin.Schema
}

func (Timestamped) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.UUID{}).
			Default(uuid.New).
			Comment("Unique identifier shared by most persisted records.").
			Immutable(),
		field.Time("created_at").
			SchemaType(map[string]string{dialect.Postgres: "timestamptz"}).
			Default(time.Now).
			Immutable().
			Comment("Timestamp when the record was created."),
		field.Time("updated_at").
			SchemaType(map[string]string{dialect.Postgres: "timestamptz"}).
			Comment("Timestamp of the last update.").
			Optional().
			Nillable(),
		field.Time("deleted_at").
			SchemaType(map[string]string{dialect.Postgres: "timestamptz"}).
			Comment("Soft delete marker for archival workflows.").
			Optional().
			Nillable(),
	}
}

func (Timestamped) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("deleted_at"),
	}
}
