# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from uuid import UUID

from pydantic import BaseModel, Field


class CommitFileVersionRequest(BaseModel):
    """CommitFileVersionRequest"""

    file_id: UUID = Field(...)
    storage_object_id: UUID = Field(...)
    size_bytes: int = Field(...)
    sha256: str = Field(...)
    actor_id: UUID = Field(...)
