# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from uuid import UUID

from pydantic import BaseModel, Field


class CreateFileDraftRequest(BaseModel):
    """CreateFileDraftRequest"""

    vault_id: UUID = Field(...)
    parent_id: UUID | None = Field(None)
    name: str = Field(...)
    media_type: str = Field(...)
    expected_size_bytes: int = Field(...)
    actor_id: UUID = Field(...)
