# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from uuid import UUID

from pydantic import BaseModel, Field


class CreateFolderRequest(BaseModel):
    """CreateFolderRequest"""

    vault_id: UUID = Field(...)
    parent_id: UUID | None = Field(None)
    name: str = Field(...)
    actor_id: UUID = Field(...)
