# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from typing import TYPE_CHECKING
from uuid import UUID

from sqlalchemy import Column, ForeignKey, UniqueConstraint
from sqlmodel import Field, Relationship, SQLModel
from ..shared.entity import Entity


if TYPE_CHECKING:
    from .file_metadata import FileMetadata
    from ..identity.user_account import UserAccount


class FileVersion(Entity, table=True):
    """Immutable file version. Storage service owns the actual object."""

    __tablename__ = "file_versions"  # type: ignore
    __table_args__ = (
        UniqueConstraint(
            "file_id",
            "version_number",
            name="file_versions_file_id_version_number_unique",
        ),
    )

    file_id: UUID = Field(
        sa_column=Column(
            ForeignKey("file_metadata.id", ondelete="CASCADE"),
            nullable=False,
            index=True,
        )
    )
    version_number: int = Field(sa_column_kwargs={"nullable": False})
    storage_object_id: UUID = Field(index=True, sa_column_kwargs={"nullable": False})
    size_bytes: int = Field(sa_column_kwargs={"nullable": False})
    sha256: str = Field(max_length=128, sa_column_kwargs={"nullable": False})
    created_by: UUID = Field(
        index=True, foreign_key="user_accounts.id", sa_column_kwargs={"nullable": False}
    )

    # ─── Relationships ─────────────────────
    file: FileMetadata | None = Relationship()
    creator: UserAccount | None = Relationship()
