# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from uuid import UUID

from pydantic import BaseModel, Field


class FileVersionView(BaseModel):
    """FileVersionView"""

    id: UUID = Field(...)
    file_id: UUID = Field(...)
    version_number: int = Field(...)
    storage_object_id: UUID = Field(...)
    size_bytes: int = Field(...)
    sha256: str = Field(...)
    created_at_iso: str = Field(...)
