# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from typing import TYPE_CHECKING
from uuid import UUID
from enum import Enum

from sqlalchemy import Column, Enum as SAEnum, ForeignKey
from sqlmodel import Field, Relationship, SQLModel
from ..shared.entity import Entity


if TYPE_CHECKING:
    from .vault_node import VaultNode


class FileCategory(str, Enum):
    """Auto-generated enum for file_category."""

    unspecified = "unknown"
    document = "document"
    image = "image"
    audio = "audio"
    video = "video"
    archive = "archive"


class FileMetadata(Entity, table=True):
    """Metadata attached to file nodes."""

    __tablename__ = "file_metadata"  # type: ignore

    node_id: UUID = Field(
        sa_column=Column(
            ForeignKey("vault_nodes.id", ondelete="CASCADE"),
            nullable=False,
            index=True,
            unique=True,
        )
    )
    current_version_id: UUID | None = Field(default=None, index=True)
    category: FileCategory = Field(
        sa_column=Column(SAEnum(FileCategory), nullable=False, server_default="unknown")
    )
    media_type: str = Field(max_length=160, sa_column_kwargs={"nullable": False})
    extension: str | None = Field(default=None, max_length=32)
    size_bytes: int = Field(sa_column_kwargs={"nullable": False})
    sha256: str = Field(max_length=128, sa_column_kwargs={"nullable": False})

    # ─── Relationships ─────────────────────
    node: VaultNode | None = Relationship()
