# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from uuid import UUID
from enum import Enum

from pydantic import BaseModel, Field
from .node_view import NodeView


class FileCategoryCode(int, Enum):
    """Auto-generated enum for file_category_code."""

    unspecified = 0
    document = 1
    image = 2
    audio = 3
    video = 4
    archive = 5


class FileView(BaseModel):
    """FileView"""

    node: NodeView = Field(...)
    category: FileCategoryCode = Field(...)
    media_type: str = Field(...)
    extension: str | None = Field(None)
    size_bytes: int = Field(...)
    sha256: str = Field(...)
    current_version_id: UUID | None = Field(None)
    labels: list[str] = Field(...)
