# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from uuid import UUID

from pydantic import BaseModel, Field


class GetNodeRequest(BaseModel):
    """GetNodeRequest"""

    node_id: UUID = Field(...)
    requester_id: UUID = Field(...)
