# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from pydantic import BaseModel, Field
from .node_view import NodeView
from ..shared.page_info import PageInfo


class ListFolderResponse(BaseModel):
    """ListFolderResponse"""

    nodes: list[NodeView] = Field(...)
    page: PageInfo = Field(...)
