# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from uuid import UUID

from pydantic import BaseModel, Field
from ..shared.page_request import PageRequest


class ListFolderRequest(BaseModel):
    """ListFolderRequest"""

    folder_id: UUID = Field(...)
    requester_id: UUID = Field(...)
    page: PageRequest = Field(...)
