# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from uuid import UUID

from pydantic import BaseModel, Field


class MoveNodeRequest(BaseModel):
    """MoveNodeRequest"""

    node_id: UUID = Field(...)
    new_parent_id: UUID | None = Field(None)
    actor_id: UUID = Field(...)
