# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from uuid import UUID
from enum import Enum

from pydantic import BaseModel, Field


class NodeKindCode(int, Enum):
    """Auto-generated enum for node_kind_code."""

    unspecified = 0
    folder = 1
    file = 2


class NodeStateCode(int, Enum):
    """Auto-generated enum for node_state_code."""

    unspecified = 0
    active = 1
    trashed = 2
    deleted = 3


class VisibilityCode(int, Enum):
    """Auto-generated enum for visibility_code."""

    unspecified = 0
    private = 1
    shared = 2
    public_link = 3


class NodeView(BaseModel):
    """NodeView"""

    id: UUID = Field(...)
    vault_id: UUID = Field(...)
    parent_id: UUID | None = Field(None)
    kind: NodeKindCode = Field(...)
    name: str = Field(...)
    path: str = Field(...)
    state: NodeStateCode = Field(...)
    visibility: VisibilityCode = Field(...)
