# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from uuid import UUID

from pydantic import BaseModel, Field


class RenameNodeRequest(BaseModel):
    """RenameNodeRequest"""

    node_id: UUID = Field(...)
    name: str = Field(...)
    actor_id: UUID = Field(...)
