# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from uuid import UUID

from pydantic import BaseModel, Field


class TrashNodeRequest(BaseModel):
    """TrashNodeRequest"""

    node_id: UUID = Field(...)
    actor_id: UUID = Field(...)
