# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from typing import TYPE_CHECKING
from uuid import UUID
from datetime import datetime
from enum import Enum

from sqlalchemy import (
    Column,
    DateTime,
    Enum as SAEnum,
    ForeignKey,
    Text,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlmodel import Field, Relationship, SQLModel
from ..shared.soft_deletable_entity import SoftDeletableEntity


if TYPE_CHECKING:
    from ..identity.user_account import UserAccount
    from .vault_space import VaultSpace


class VaultNodeKind(str, Enum):
    """Auto-generated enum for vault_node_kind."""

    folder = "folder"
    file = "file"


class VaultNodeState(str, Enum):
    """Auto-generated enum for vault_node_state."""

    active = "active"
    trashed = "trashed"
    deleted = "deleted"


class Visibility(str, Enum):
    """Auto-generated enum for visibility."""

    private = "private"
    shared = "shared"
    public_link = "public_link"


class VaultNode(SoftDeletableEntity, table=True):
    """Folder/file node in a vault tree. File-specific metadata lives separately."""

    __tablename__ = "vault_nodes"  # type: ignore
    __table_args__ = (
        UniqueConstraint(
            "vault_id",
            "parent_id",
            "normalized_name",
            name="vault_nodes_vault_id_parent_id_normalized_name_unique",
        ),
    )

    vault_id: UUID = Field(
        sa_column=Column(
            PG_UUID(as_uuid=True),
            ForeignKey("vault_spaces.id", ondelete="CASCADE"),
            nullable=False,
            index=True,
        )
    )
    parent_id: UUID | None = Field(
        default=None, sa_column=Column(PG_UUID(as_uuid=True), index=True)
    )
    kind: VaultNodeKind = Field(sa_column=Column(SAEnum(VaultNodeKind), nullable=False))
    name: str = Field(max_length=240, sa_column_kwargs={"nullable": False})
    normalized_name: str = Field(max_length=240, sa_column_kwargs={"nullable": False})
    path: str = Field(sa_column=Column(Text, nullable=False))
    depth: int = Field(sa_column_kwargs={"nullable": False})
    state: VaultNodeState = Field(
        sa_column=Column(
            SAEnum(VaultNodeState), nullable=False, index=True, server_default="active"
        )
    )
    visibility: Visibility = Field(
        sa_column=Column(SAEnum(Visibility), nullable=False, server_default="private")
    )
    trashed_at: datetime | None = Field(
        default=None, sa_column=Column(DateTime(timezone=True))
    )
    created_by: UUID = Field(
        sa_column=Column(
            PG_UUID(as_uuid=True),
            ForeignKey("user_accounts.id"),
            nullable=False,
            index=True,
        )
    )
    updated_by: UUID | None = Field(
        default=None, sa_column=Column(PG_UUID(as_uuid=True))
    )

    # ─── Relationships ─────────────────────
    vault: VaultSpace | None = Relationship()
    creator: UserAccount | None = Relationship()
