# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from uuid import UUID

from pydantic import BaseModel, Field
from ..shared.actor_ref import ActorRef


class VaultView(BaseModel):
    """VaultView"""

    id: UUID = Field(...)
    owner: ActorRef = Field(...)
    name: str = Field(...)
    quota_bytes: int = Field(...)
    used_bytes: int = Field(...)
