// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package metadata

import (
	"github.com/google/uuid"
)

// CreateFileDraftRequest CreateFileDraftRequest
type CreateFileDraftRequest struct {
	VaultID           uuid.UUID  `validate:"required" json:"vaultId"`
	ParentID          *uuid.UUID `validate:"omitempty" json:"parentId,omitempty"`
	Name              string     `validate:"required" json:"name"`
	MediaType         string     `validate:"required" json:"mediaType"`
	ExpectedSizeBytes int64      `validate:"required" json:"expectedSizeBytes"`
	ActorID           uuid.UUID  `validate:"required" json:"actorId"`
}
