// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package metadata

// FileCategoryCode represents the file_category_code enum.
type FileCategoryCode int32

const (
	FileCategoryCodeUnspecified FileCategoryCode = 0
	FileCategoryCodeDocument    FileCategoryCode = 1
	FileCategoryCodeImage       FileCategoryCode = 2
	FileCategoryCodeAudio       FileCategoryCode = 3
	FileCategoryCodeVideo       FileCategoryCode = 4
	FileCategoryCodeArchive     FileCategoryCode = 5
)

// NodeKindCode represents the node_kind_code enum.
type NodeKindCode int32

const (
	NodeKindCodeUnspecified NodeKindCode = 0
	NodeKindCodeFolder      NodeKindCode = 1
	NodeKindCodeFile        NodeKindCode = 2
)

// NodeStateCode represents the node_state_code enum.
type NodeStateCode int32

const (
	NodeStateCodeUnspecified NodeStateCode = 0
	NodeStateCodeActive      NodeStateCode = 1
	NodeStateCodeTrashed     NodeStateCode = 2
	NodeStateCodeDeleted     NodeStateCode = 3
)

// VisibilityCode represents the visibility_code enum.
type VisibilityCode int32

const (
	VisibilityCodeUnspecified VisibilityCode = 0
	VisibilityCodePrivate     VisibilityCode = 1
	VisibilityCodeShared      VisibilityCode = 2
	VisibilityCodePublicLink  VisibilityCode = 3
)
