// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package metadata

import (
	"github.com/google/uuid"
)

// FileView FileView
type FileView struct {
	Node             NodeView         `json:"node"`
	Category         FileCategoryCode `validate:"oneof=0 1 2 3 4 5" json:"category"`
	MediaType        string           `validate:"required" json:"mediaType"`
	Extension        *string          `validate:"omitempty" json:"extension,omitempty"`
	SizeBytes        int64            `validate:"required" json:"sizeBytes"`
	Sha256           string           `validate:"required" json:"sha256"`
	CurrentVersionID *uuid.UUID       `validate:"omitempty" json:"currentVersionId,omitempty"`
	Labels           []string         `json:"labels"`
}
