// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package metadata

import (
	"github.com/google/uuid"

	file_vault_shared "github.com/example/file-vault/file_vault/shared"
)

// ListFolderRequest ListFolderRequest
type ListFolderRequest struct {
	FolderID    uuid.UUID                     `validate:"required" json:"folderId"`
	RequesterID uuid.UUID                     `validate:"required" json:"requesterId"`
	Page        file_vault_shared.PageRequest `json:"page"`
}
