// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package metadata

import (
	"github.com/google/uuid"
)

// MoveNodeRequest MoveNodeRequest
type MoveNodeRequest struct {
	NodeID      uuid.UUID  `validate:"required" json:"nodeId"`
	NewParentID *uuid.UUID `validate:"omitempty" json:"newParentId,omitempty"`
	ActorID     uuid.UUID  `validate:"required" json:"actorId"`
}
