// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package metadata

import (
	"github.com/google/uuid"
)

// TrashNodeRequest TrashNodeRequest
type TrashNodeRequest struct {
	NodeID  uuid.UUID `validate:"required" json:"nodeId"`
	ActorID uuid.UUID `validate:"required" json:"actorId"`
}
