// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package metadata

import (
	"github.com/google/uuid"

	file_vault_shared "github.com/example/file-vault/file_vault/shared"
)

// VaultView VaultView
type VaultView struct {
	ID         uuid.UUID                  `validate:"required" json:"id"`
	Owner      file_vault_shared.ActorRef `json:"owner"`
	Name       string                     `validate:"required" json:"name"`
	QuotaBytes int64                      `validate:"required" json:"quotaBytes"`
	UsedBytes  int64                      `validate:"required" json:"usedBytes"`
}
