import {
  type EmitContext,
  type Enum,
  type Model,
  type ModelProperty,
  type Type,
} from "@typespec/compiler";
import { resolvePath, joinPaths } from "@typespec/compiler";
import { reportDiagnostic, type ProtoEmitterOptions } from "./lib.js";
import { collectPackages, filterBuckets, type PackageBucket } from "./walker/collect-packages.js";
import { buildPackageGraph, type PackageGraph } from "./walker/package-graph.js";
import { buildNamingContext, refNamedType } from "./walker/cross-package-refs.js";
import type { ImportPathStyle } from "./walker/import-planner.js";
import { renderProtoMessage } from "./writer/proto-message.js";
import { renderProtoEnum } from "./writer/proto-enum.js";
import { renderProtoService } from "./writer/proto-service.js";
import { renderProtoFile } from "./writer/proto-file.js";
import { renderProtoComment } from "./writer/proto-comment.js";

const DEFAULT_HEADER = "Generated by @qninhdt/typespec-protobuf-openlet. DO NOT EDIT.";

/**
 * TypeSpec emitter entry. Walks every `@package` namespace, builds a package
 * graph, and writes one `.proto` file per package under `emitterOutputDir`
 * named after the package's slash-separated path (e.g. `openlet/user/v1.proto`).
 *
 * Cross-package references (Phase 4) resolve to qualified proto names + an
 * `import` statement when `emit-imports` is on (default). `emit-only`
 * restricts which packages are WRITTEN while keeping all packages in the
 * graph so imports still resolve.
 */
export async function $onEmit(context: EmitContext<ProtoEmitterOptions>): Promise<void> {
  const { program, options } = context;
  if (program.compilerOptions.noEmit) return;
  const outputDir = options["output-dir"] ?? context.emitterOutputDir;

  const allBuckets = collectPackages(program);
  if (allBuckets.length === 0) return;

  // Build the graph over ALL packages (not just the emitted subset) so
  // cross-package references can resolve even when emit-only is set.
  const outputPaths = options["output-paths"];
  const graph = buildPackageGraph(program, allBuckets, { outputPaths });
  const importStyle = (options["import-path-style"] ?? "package-path") as ImportPathStyle;
  const emitImports = options["emit-imports"] !== false;

  // Cycle detection across the package import graph.
  const cycle = detectImportCycle(program, graph, allBuckets);
  if (cycle) {
    reportDiagnostic(program, {
      code: "cyclic-import" as any,
      target: program.getGlobalNamespaceType(),

      format: { cycle: cycle.join(" → ") } as any,
    });
    return;
  }

  // Which packages to actually WRITE.
  const emitOnly = options["emit-only"];
  const writeBuckets = emitOnly
    ? allBuckets.filter((b) => emitOnly.includes(b.spec.name))
    : filterBuckets(allBuckets);

  const headerLines = renderProtoComment(options.header ?? DEFAULT_HEADER);
  const fieldNameStyle = options["field-name-style"] ?? "snake_case";
  const emptyRequestRewrite = options["empty-request-rewrite"] !== false;
  const resolverOptions = {
    wellKnown: {
      timestamp: options["well-known"]?.timestamp,
      duration: options["well-known"]?.duration,
      date: options["well-known"]?.date,
      time: options["well-known"]?.time,
      decimal: options["well-known"]?.decimal,
    },
  };

  for (const bucket of writeBuckets) {
    const naming = emitImports
      ? buildNamingContext({
          graph,
          currentPackage: bucket.spec.name,
          style: importStyle,
          outputPaths,
        })
      : undefined;

    const imports: string[] = [];
    const bodyBlocks: string[][] = [];

    for (const model of bucket.messages) {
      const {
        lines,
        imports: msgImports,
        diagnostics,
      } = renderProtoMessage(program, model, {
        fieldNameStyle,
        resolverOptions,
        naming,
      });
      imports.push(...msgImports);
      bodyBlocks.push(lines);
      reportAll(program, diagnostics);
    }

    for (const e of bucket.enums) {
      const { lines, diagnostics } = renderProtoEnum(program, e);
      bodyBlocks.push(lines);
      reportAll(program, diagnostics);
    }

    for (const iface of bucket.services) {
      const {
        lines,
        imports: svcImports,
        diagnostics,
      } = renderProtoService(program, iface, {
        emptyRequestRewrite,
        naming,
      });
      imports.push(...svcImports);
      bodyBlocks.push(lines);
      reportAll(program, diagnostics);
    }

    const content = renderProtoFile({
      header: headerLines,
      package: bucket.spec,
      imports,
      bodyBlocks,
    });

    const relativePath = graph.filePathOf(bucket.spec.name) ?? `${bucket.spec.name}.proto`;
    const targetPath = resolvePath(joinPaths(outputDir, relativePath));
    await program.host.writeFile(targetPath, content);
  }
}

/** Report a batch of structured writer diagnostics. */
function reportAll(
  program: EmitContext<ProtoEmitterOptions>["program"],
  diagnostics: Array<{ code: string; target: unknown; args: Record<string, unknown> }>,
): void {
  for (const d of diagnostics) {
    reportDiagnostic(program, {
      code: d.code as any,

      target: d.target as any,

      format: d.args as any,
    });
  }
}

/**
 * Detect a cycle in the package → package import graph. Builds the edge set
 * by inspecting every message/service field's resolved named type and
 * recording cross-package dependencies, then runs a DFS cycle check.
 *
 * Returns the cycle path (package names) when a cycle exists, else undefined.
 */
function detectImportCycle(
  program: EmitContext<ProtoEmitterOptions>["program"],
  graph: PackageGraph,
  buckets: PackageBucket[],
): string[] | undefined {
  const edges = new Map<string, Set<string>>();
  for (const bucket of buckets) {
    const from = bucket.spec.name;
    if (!edges.has(from)) edges.set(from, new Set());
    for (const model of bucket.messages) {
      for (const prop of model.properties.values()) {
        const namedType = propNamedType(prop);
        if (!namedType) continue;
        const entry = graph.entryOf(namedType);
        if (entry && entry.packageName !== from) {
          edges.get(from)!.add(entry.packageName);
        }
      }
    }
  }

  const WHITE = 0;
  const GRAY = 1;
  const BLACK = 2;
  const color = new Map<string, number>();
  const stack: string[] = [];
  for (const node of edges.keys()) color.set(node, WHITE);

  function dfs(node: string): string[] | undefined {
    color.set(node, GRAY);
    stack.push(node);
    for (const next of edges.get(node) ?? []) {
      const c = color.get(next) ?? WHITE;
      if (c === GRAY) {
        const idx = stack.indexOf(next);
        return [...stack.slice(idx), next];
      }
      if (c === WHITE) {
        const found = dfs(next);
        if (found) return found;
      }
    }
    color.set(node, BLACK);
    stack.pop();
    return undefined;
  }

  for (const node of edges.keys()) {
    if (color.get(node) === WHITE) {
      const found = dfs(node);
      if (found) return found;
    }
  }
  return undefined;
}

/**
 * Unwrap a property's type to its named Model / Enum (through arrays + maps)
 * for cycle detection. Operates on the raw TypeSpec property type so we don't
 * pay for a full resolve pass during cycle detection.
 */
function propNamedType(prop: ModelProperty): Model | Enum | undefined {
  let t: Type = prop.type;
  // Unwrap array / record indexers.
  while (t.kind === "Model" && t.indexer) {
    t = t.indexer.value;
  }
  if ((t.kind === "Model" || t.kind === "Enum") && t.name) {
    return t;
  }
  return undefined;
}

// re-exported for tests
export { refNamedType };
