// ─── Library + state keys ──────────────────────────────────────────────────

export { $lib } from "./lib.js";
export type { ProtoEmitterOptions } from "./lib.js";

// ─── Emitter entry ─────────────────────────────────────────────────────────

export { $onEmit } from "./emitter.js";

export {
  PROTO_NAMESPACE,
  reportDiagnostic,
  MessageKey,
  FieldNumberKey,
  ReservedKey,
  OneofKey,
  ServiceKey,
  RpcKey,
  KeepEmptyRequestKey,
  IgnoreKey,
  RenameKey,
  GoTypeKey,
  MapKey,
  PackageKey,
} from "./lib.js";

// ─── Public types ──────────────────────────────────────────────────────────

export type { ProtoReservation } from "./decorators-message.js";
export type { ProtoPackageDetails, ProtoPackageSpec } from "./decorators-service.js";
export type { ProtoGoTypeSpec, ProtoMapSpec } from "./decorators-field.js";

// ─── Accessors (getter helpers consumed by emitters) ───────────────────────

export {
  isProtoMessage,
  getProtoMessageOverrideName,
  getProtoFieldNumber,
  getProtoReservations,
  getProtoOneof,
  isProtoService,
  getProtoRpcOverrideName,
  isKeepEmptyRequest,
  isProtoIgnored,
  getProtoFieldName,
  getProtoGoType,
  getProtoMap,
  getProtoPackage,
} from "./state-accessors.js";

// ─── Type system (Phase 2) ──────────────────────────────────────────────────

export type { ProtoScalar, ProtoTypeRef } from "./types/scalars.js";
export { PROTO_MAP_KEY_SCALARS } from "./types/scalars.js";
export {
  PROTO_ANY,
  PROTO_EMPTY,
  WELL_KNOWN_BY_TYPESPEC_NAME,
  WELL_KNOWN_TOGGLE_NAMES,
} from "./types/well-known.js";
export { BUILTIN_SCALAR_TO_PROTO } from "./types/builtin-scalars.js";
export { ORM_SCALAR_TO_PROTO, STORAGE_ONLY_ORM_SCALARS } from "./types/orm-scalars.js";
export { getScalarChain, getQualifiedTypeName } from "./types/utils.js";
export { resolveProtoType, resolveTypeRef } from "./types/resolver.js";
export type {
  ProtoTypeResolution,
  ProtoTypeResolutionWarning,
  ResolveProtoTypeOptions,
} from "./types/resolver.js";

// ─── Decorator namespace registration ──────────────────────────────────────
// TypeSpec resolves extern dec implementations via the $decorators export map.
// Individual $name functions must NOT be re-exported as top-level named exports
// to avoid "duplicate-symbol" errors with the extern dec declarations in the
// .tsp file.

import {
  $message,
  $field,
  $reserve,
  $oneof,
  $service,
  $rpc,
  $keepEmptyRequest,
  $package,
  $ignore,
  $rename,
  $goType,
  $map,
} from "./decorators.js";

export const $decorators = {
  "Openlet.Proto": {
    message: $message,
    field: $field,
    reserve: $reserve,
    oneof: $oneof,
    service: $service,
    rpc: $rpc,
    keepEmptyRequest: $keepEmptyRequest,
    package: $package,
    ignore: $ignore,
    rename: $rename,
    goType: $goType,
    map: $map,
  },
};

/**
 * Emitter name used for the "Code generated by X. DO NOT EDIT." header that
 * the Phase 3+ emitter writes into every generated `.proto` file. Mirrors
 * `@qninhdt/typespec-orm`'s `generatedHeader` so downstream tooling can detect
 * generated files consistently across the suite.
 */
export const generatedHeader = "Code generated by @qninhdt/typespec-protobuf-openlet. DO NOT EDIT.";
