# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from typing import TYPE_CHECKING

from sqlmodel import Field, Relationship, SQLModel

from game_platform.__associations__ import user_badges
from ..shared.timestamped import Timestamped


if TYPE_CHECKING:
    from .user import User


class Badge(Timestamped, table=True):
    """Account badge or achievement marker attached to player profiles."""

    __tablename__ = "badges"  # type: ignore

    # Stable badge code used by tooling and migration scripts.
    code: str = Field(
        unique=True,
        max_length=80,
        sa_column_kwargs={
            "nullable": False,
            "comment": "Stable badge code used by tooling and migration scripts.",
        },
    )
    # Human-readable badge name rendered in the UI.
    label: str = Field(
        max_length=160,
        sa_column_kwargs={
            "nullable": False,
            "comment": "Human-readable badge name rendered in the UI.",
        },
    )

    # ─── Relationships ─────────────────────
    # Users who have earned this badge.
    users: list[User] = Relationship(
        back_populates="badges", sa_relationship_kwargs={"secondary": user_badges}
    )
