import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const ReindexFileRequestSchema = z.object({
  fileId: z.uuid(),
  requestedBy: z.uuid(),
})
export type ReindexFileRequest = z.infer<typeof ReindexFileRequestSchema>;
