import { z } from "zod";
import { SearchQuerySchema } from "../../_scalars.js";
import { PageRequestSchema } from "../shared/PageRequest.js";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const SearchFilesRequestSchema = z.object({
  ownerId: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  query: SearchQuerySchema,
  mediaTypes: z.array(z.string()),
  labels: z.array(z.string()),
  page: PageRequestSchema,
})
export type SearchFilesRequest = z.infer<typeof SearchFilesRequestSchema>;
