import { z } from "zod";
import { FileViewSchema } from "../metadata/FileView.js";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const SearchHitSchema = z.object({
  file: FileViewSchema,
  snippet: z.string().optional(),
  score: z.number(),
})
export type SearchHit = z.infer<typeof SearchHitSchema>;
