import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const SuggestLabelsResponseSchema = z.object({
  labels: z.array(z.string()),
})
export type SuggestLabelsResponse = z.infer<typeof SuggestLabelsResponseSchema>;
