// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package shared

// Ack Ack
type Ack struct {
	Ok      bool    `json:"ok"`
	Message *string `validate:"omitempty" json:"message,omitempty"`
}
