sonar.organization=qninhdt
sonar.projectKey=qninhdt_typespec-libraries
sonar.projectName=typespec-libraries

sonar.sources=packages
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/dist/**,**/temp/**,**/examples/**/*,**/outputs/**/*
sonar.test.exclusions=**/test/**/*

sonar.typescript.links=typescript:
