sonar.organization=qninhdt
sonar.projectKey=qninhdt_typespec-libraries
sonar.projectName=typespec-libraries

sonar.sources=packages
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/dist/**,**/temp/**,**/examples/**/*,**/outputs/**/*,**/test/**/*,**/*.test.ts,**/*.test.tsx
sonar.javascript.lcov.reportPaths=packages/typespec-orm/coverage/lcov.info,packages/typespec-dbml/coverage/lcov.info,packages/typespec-gorm/coverage/lcov.info,packages/typespec-sqlmodel/coverage/lcov.info,packages/typespec-zod/coverage/lcov.info

sonar.typescript.links=typescript:
