sonar.organization=qninhdt
sonar.projectKey=qninhdt_typespec-libraries
sonar.projectName=typespec-libraries

sonar.sources=packages
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/dist/**,**/temp/**,**/examples/**/*,**/outputs/**/*,**/test/**/*,**/*.test.ts,**/*.test.tsx
sonar.coverage.exclusions=**/test/**/*,**/*.test.ts,**/*.test.tsx,**/coverage/**
sonar.javascript.lcov.reportPaths=packages/typespec-orm/coverage/sonar-lcov.info,packages/typespec-dbml/coverage/sonar-lcov.info,packages/typespec-gorm/coverage/sonar-lcov.info,packages/typespec-sqlmodel/coverage/sonar-lcov.info,packages/typespec-zod/coverage/sonar-lcov.info

sonar.typescript.links=typescript:
