output-dir: "{project-root}/outputs"
emit:
  - "@qninhdt/typespec-gorm"
  - "@qninhdt/typespec-sqlmodel"
  - "@qninhdt/typespec-dbml"
  - "@qninhdt/typespec-zod"
options:
  "@qninhdt/typespec-zod":
    output-dir: "./outputs/zod"
    standalone: true
    library-name: "demo"
  "@qninhdt/typespec-gorm":
    output-dir: "./outputs/gorm"
    standalone: true
    library-name: "github.com/demo-user/demo"
    collection-strategy: "jsonb"
  "@qninhdt/typespec-sqlmodel":
    output-dir: "./outputs/sqlmodel"
    standalone: true
    library-name: "demo"
    collection-strategy: "jsonb"
  "@qninhdt/typespec-dbml":
    output-dir: "./outputs/dbml"
    split-by-namespace: true
