// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package identity

import (
	"github.com/google/uuid"
)

// AccountView AccountView
type AccountView struct {
	ID          uuid.UUID         `validate:"required" json:"id"`
	Email       string            `validate:"required,email" json:"email"`
	DisplayName string            `validate:"required" json:"displayName"`
	AvatarURL   *string           `validate:"omitempty" json:"avatarUrl,omitempty"`
	Locale      *string           `validate:"omitempty" json:"locale,omitempty"`
	Status      AccountStatusCode `validate:"oneof=0 1 2 3" json:"status"`
}
