// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package identity

import (
	"github.com/google/uuid"
)

// GetAccountRequest GetAccountRequest
type GetAccountRequest struct {
	AccountID uuid.UUID `validate:"required" json:"accountId"`
}
