// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package identity

import (
	file_vault_shared "github.com/example/file-vault/file_vault/shared"
)

// ListSessionsResponse ListSessionsResponse
type ListSessionsResponse struct {
	Sessions []SessionView              `json:"sessions"`
	Page     file_vault_shared.PageInfo `json:"page"`
}
