// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package accounts

// GetUserRequest GetUserRequest
type GetUserRequest struct {
	ID string `validate:"required" json:"id"`
}
