// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package accounts

// UserView UserView
type UserView struct {
	ID string `validate:"required" json:"id"`
	Username string `validate:"required" json:"username"`
	Email string `validate:"required" json:"email"`
	DisplayName string `validate:"required" json:"displayName"`
}
