# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from pydantic import BaseModel, EmailStr, Field


class CreateInvitationForm(BaseModel):
    """Form payload for creating an invitation. Uses `@data`, so no DB schema is generated."""

    # Email address of the invited collaborator. Inherits validators from Accounts.User.email.
    invitee_email: EmailStr = Field(
        ...,
        max_length=320,
        title="Invitee Email",
        description="Email address of the invited collaborator. Inherits validators from Accounts.User.email.",
        json_schema_extra={"placeholder": "friend@example.com"},
    )
    # Name of the world to share. Inherits validators from Worlds.World.name.
    world_name: str = Field(
        ...,
        max_length=200,
        title="World Name",
        description="Name of the world to share. Inherits validators from Worlds.World.name.",
        json_schema_extra={"placeholder": "Choose a world"},
    )
    # Prompt preview pulled from Worlds.World.prompt.
    world_prompt: str = Field(
        ...,
        title="World Prompt",
        description="Prompt preview pulled from Worlds.World.prompt.",
    )
    # Optional personal note included with the invitation.
    message: str | None = Field(
        None,
        title="Personal Message",
        description="Optional personal note included with the invitation.",
        json_schema_extra={"placeholder": "Add a short note for the invitee"},
    )
