# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from typing import TYPE_CHECKING
from uuid import UUID

from sqlalchemy import Column, ForeignKey
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlmodel import Field, Relationship, SQLModel
from ..shared.soft_deletable_entity import SoftDeletableEntity


if TYPE_CHECKING:
    from ..identity.user_account import UserAccount


class VaultSpace(SoftDeletableEntity, table=True):
    """Top-level vault owned by one account."""

    __tablename__ = "vault_spaces" # type: ignore

    owner_id: UUID = Field(sa_column=Column(PG_UUID(as_uuid=True), ForeignKey("user_accounts.id", ondelete="CASCADE"), nullable=False, index=True))
    name: str = Field(max_length=120, sa_column_kwargs={"nullable": False})
    quota_bytes: int = Field(sa_column_kwargs={"nullable": False})
    used_bytes: int = Field(sa_column_kwargs={"nullable": False, "server_default": "0"})

    # ─── Relationships ─────────────────────
    owner: UserAccount | None = Relationship()
