/**
 * DbmlTable - Generate DBML table definitions.
 */

import type { Model, Program } from "@typespec/compiler";
import {
  classifyProperties,
  collectCompositeTypeFields,
  getCompositeFields,
  isKey,
  isUnique,
  isIndex,
  getColumnName,
  getDoc,
  getSchemaName,
} from "@qninhdt/typespec-orm";
import { generateColumnLine, hasUniqueNameOverride } from "./DbmlColumn.jsx";
import { formatDbmlNote, quoteDbmlIdentifier } from "./DbmlConstants.js";

export interface DbmlTableProps {
  readonly program: Program;
  readonly model: Model;
  readonly tableName: string;
}

/**
 * JSX component: generates a DBML table definition.
 */
export function DbmlTable(props: DbmlTableProps): string {
  const { program, model, tableName } = props;

  const { ignored, fields: regularProps } = classifyProperties(program, model);

  const lines: string[] = [];
  const indexes: string[] = [];
  const trailingComments: string[] = [];

  // Generate columns (all fields including enum types)
  for (const { prop } of regularProps) {
    const colLine = generateColumnLine(program, prop);
    if (colLine) {
      lines.push(colLine);
    }
  }

  // Surface @ignore field docs as a trailing comment block AFTER the table.
  // Injecting them mid-table between columns and the indexes block was
  // visually noisy and made the column list look discontinuous.
  for (const { prop } of ignored) {
    const doc = getDoc(program, prop);
    if (doc) {
      trailingComments.push(`// ${prop.name}: ${doc}`);
    }
  }

  const compositeFields = collectCompositeTypeFields(program, model, tableName);

  indexes.push(...compositeFields.map(buildCompositeIndexLine));

  // Add single-column indexes and unique constraints
  for (const { prop } of regularProps) {
    // Skip composite type configuration properties
    if (getCompositeFields(program, prop)) continue;

    const colName = quoteDbmlIdentifier(getColumnName(program, prop));

    if (isIndex(program, prop) && !isUnique(program, prop)) {
      indexes.push(`    ${colName}`);
    } else if (isUnique(program, prop) && !isKey(program, prop)) {
      // Unnamed `@unique` renders inline as column-level `[unique]` (handled
      // in DbmlColumn) so dbdiagram.io shows the badge inline. Only keep the
      // indexes-block entry when there's a `@unique("name")` override that
      // would otherwise lose the constraint name (DBML has no column-level
      // name surface).
      if (hasUniqueNameOverride(program, prop)) {
        indexes.push(`    ${colName} [unique]`);
      }
    }
  }

  const schemaName = getSchemaName(program, model);
  const qualifiedName = schemaName
    ? `${quoteDbmlIdentifier(schemaName)}.${quoteDbmlIdentifier(tableName)}`
    : quoteDbmlIdentifier(tableName);
  const tableLines = [`Table ${qualifiedName} {`, ...lines];

  // Surface @doc on the model as a DBML table-level Note.
  const tableDoc = getDoc(program, model);
  if (tableDoc) {
    if (tableLines.length > 1) {
      tableLines.push("");
    }
    tableLines.push(`  Note: ${formatDbmlNote(tableDoc)}`);
  }

  if (indexes.length > 0) {
    tableLines.push("", "  indexes {", ...indexes, "  }");
  }
  tableLines.push("}");

  if (trailingComments.length > 0) {
    tableLines.push(...trailingComments);
  }

  return tableLines.join("\n");
}

function buildCompositeIndexLine(ct: {
  name: string;
  columns: string[];
  isUnique: boolean;
  isPrimary: boolean;
}): string {
  // Composite primary keys never carry a user-defined name surface in DBML —
  // `[pk]` alone is enough. For non-pk indexes, preserve the constraint name
  // generated by `collectCompositeTypeFields` (which honors `@@tableIndex(name)`
  // / `@@tableUnique(name)` overrides) via `[name: '...']` so dbdocs shows the
  // explicit identifier the schema author chose.
  const attrs: string[] = [];
  if (ct.isPrimary) {
    attrs.push("pk");
  } else {
    if (ct.name) {
      attrs.push(`name: '${ct.name.replaceAll("'", "\\'")}'`);
    }
    if (ct.isUnique) {
      attrs.push("unique");
    }
  }
  const suffix = attrs.length > 0 ? ` [${attrs.join(", ")}]` : "";
  return `    (${ct.columns.join(", ")})${suffix}`;
}
