# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from uuid import UUID

from pydantic import AnyUrl, BaseModel, EmailStr, Field


class PublicUser(BaseModel):
    """Public user record with sensitive and operational fields removed. Kept explicit so generated form schemas stay free of table-only relations."""

    # Unique identifier shared by most persisted records.
    id: UUID = Field(
        ..., description="Unique identifier shared by most persisted records."
    )
    # Email address used for login and invitations. Other namespaces reference this via lookup types.
    email: EmailStr = Field(
        ...,
        max_length=320,
        description="Email address used for login and invitations. Other namespaces reference this via lookup types.",
    )
    # Display name shown throughout the UI.
    display_name: str = Field(
        ..., max_length=100, description="Display name shown throughout the UI."
    )
    # Public avatar URL rendered in lists and profile cards.
    avatar_url: AnyUrl | None = Field(
        None,
        max_length=512,
        description="Public avatar URL rendered in lists and profile cards.",
    )
    # Optional locale preference for formatting and localization.
    preferred_locale: str | None = Field(
        None,
        max_length=16,
        description="Optional locale preference for formatting and localization.",
    )
    # Entitlement credits or consumable balance.
    credits: int = Field(..., description="Entitlement credits or consumable balance.")
    # Whether the account is currently active.
    is_active: bool = Field(..., description="Whether the account is currently active.")
