# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from pydantic import BaseModel


class UserProfile(BaseModel):
    """Lightweight user profile view for public surfaces. Demonstrates a default form model in a nested namespace."""
