// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package audit

import (
	"github.com/google/uuid"

	file_vault_shared "github.com/example/file-vault/audit-svc/file_vault/shared"
)

// QueryAuditEventsRequest QueryAuditEventsRequest
type QueryAuditEventsRequest struct {
	ActorID *uuid.UUID `validate:"omitempty" json:"actorId,omitempty"`
	ResourceType *string `validate:"omitempty" json:"resourceType,omitempty"`
	ResourceID *uuid.UUID `validate:"omitempty" json:"resourceId,omitempty"`
	ActionPrefix *string `validate:"omitempty" json:"actionPrefix,omitempty"`
	Page file_vault_shared.PageRequest `json:"page"`
}
