import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const UserProfileSchema = z
  .object({
    id: z
      .string()
      .describe("Unique identifier shared by most persisted records."),
    email: z
      .string()
      .max(320)
      .email()

        .describe("Email address used for login and invitations. Other namespaces reference this via lookup types."),
    displayName: z
      .string()
      .max(100)
      .describe("Display name shown throughout the UI."),
    avatarUrl: z
      .string()
      .max(512)
      .url()
      .optional()
      .describe("Public avatar URL rendered in lists and profile cards."),
  })

    .describe("Lightweight user profile view for public surfaces. Demonstrates a `@data` model in a nested namespace.")
export type UserProfile = z.infer<typeof UserProfileSchema>;

export const UserProfileMeta = {
  email: { inputType: "email" },
  avatarUrl: { inputType: "url" },
} as const;
