// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package invites

// InvitationView InvitationView
type InvitationView struct {
	ID string `validate:"required" json:"id"`
	WorldSlug string `validate:"required" json:"worldSlug"`
	InviterID string `validate:"required" json:"inviterId"`
	Status string `validate:"required" json:"status"`
}
