// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package invites

// ListInvitationsResponse ListInvitationsResponse
type ListInvitationsResponse struct {
	Invitations []InvitationView `json:"invitations"`
}
