// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package accounts

import (
	"github.com/google/uuid"
)

// PublicUser Public user record with sensitive and operational fields removed. Kept explicit so generated form schemas stay free of table-only relations.
type PublicUser struct {
	// Unique identifier shared by most persisted records.
	ID uuid.UUID `validate:"required" json:"id"`
	// Email address used for login and invitations. Other namespaces reference this via lookup types.
	Email string `validate:"required,max=320,email" json:"email"`
	// Display name shown throughout the UI.
	DisplayName string `validate:"required,max=100" json:"displayName"`
	// Public avatar URL rendered in lists and profile cards.
	AvatarURL *string `validate:"omitempty,max=512,url" json:"avatarUrl,omitempty"`
	// Optional locale preference for formatting and localization.
	PreferredLocale *string `validate:"omitempty,max=16" json:"preferredLocale,omitempty"`
	// Entitlement credits or consumable balance.
	Credits int32 `validate:"required" json:"credits"`
	// Whether the account is currently active.
	IsActive bool `json:"isActive"`
}
