// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package accounts

import (
	"github.com/google/uuid"
)

// UserProfile Lightweight user profile view for public surfaces. Demonstrates a `@data` model in a nested namespace.
type UserProfile struct {
	// Unique identifier shared by most persisted records.
	ID uuid.UUID `json:"id"`
	// Email address used for login and invitations. Other namespaces reference this via lookup types.
	Email string `validate:"required,max=320,email" json:"email"`
	// Display name shown throughout the UI.
	DisplayName string `validate:"required,max=100" json:"displayName"`
	// Public avatar URL rendered in lists and profile cards.
	AvatarURL *string `validate:"omitempty,max=512,url" json:"avatarUrl,omitempty"`
}
