import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const TimestampedSchema = z
  .object({
    id: z
      .uuid()
      .describe("Unique identifier shared by most persisted records."),
    createdAt: z.coerce
      .date()
      .describe("Timestamp when the record was created."),
    updatedAt: z.coerce
      .date()
      .optional()
      .describe("Timestamp of the last update."),
    deletedAt: z.coerce
      .date()
      .optional()
      .describe("Soft delete marker for archival workflows."),
  })

    .describe("Base model with common timestamp fields for audit trails. This is a reusable table mixin and is never emitted by itself.")
export type Timestamped = z.infer<typeof TimestampedSchema>;
