import { z } from "zod";
import { TimestampedSchema } from "./Timestamped.js";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const WorldOwnedSchema = TimestampedSchema
  .extend({
    worldId: z.uuid().describe("Foreign key to the owning world."),
  })

    .describe("Shared mixin for content that belongs to a specific world. Demonstrates mixin-to-mixin inheritance.")
export type WorldOwned = z.infer<typeof WorldOwnedSchema>;
