# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from uuid import UUID
from enum import Enum

from pydantic import BaseModel, EmailStr, Field


class AccountStatusCode(int, Enum):
    """Auto-generated enum for account_status_code."""

    unspecified = 0
    active = 1
    disabled = 2
    pending_verification = 3


class AccountView(BaseModel):
    """AccountView"""

    id: UUID = Field(...)
    email: EmailStr = Field(...)
    display_name: str = Field(...)
    avatar_url: str | None = Field(None)
    locale: str | None = Field(None)
    status: AccountStatusCode = Field(...)
