# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from typing import TYPE_CHECKING
from uuid import UUID
from datetime import datetime

from sqlalchemy import Column, DateTime, ForeignKey
from sqlmodel import Field, Relationship, SQLModel
from ..shared.entity import Entity


if TYPE_CHECKING:
    from .user_account import UserAccount


class AuthSession(Entity, table=True):
    """Long-lived refresh-session family. Access tokens stay outside the DB."""

    __tablename__ = "auth_sessions"  # type: ignore

    account_id: UUID = Field(
        sa_column=Column(
            ForeignKey("user_accounts.id", ondelete="CASCADE"),
            nullable=False,
            index=True,
        )
    )
    refresh_token_hash: str = Field(
        unique=True, max_length=255, sa_column_kwargs={"nullable": False}
    )
    device_label: str | None = Field(default=None, max_length=80)
    ip_address_hash: str | None = Field(default=None, max_length=128)
    user_agent_hash: str | None = Field(default=None, max_length=128)
    expires_at: datetime = Field(
        sa_column=Column(DateTime(timezone=True), nullable=False)
    )
    revoked_at: datetime | None = Field(
        default=None, sa_column=Column(DateTime(timezone=True))
    )

    # ─── Relationships ─────────────────────
    account: UserAccount | None = Relationship()
