# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from uuid import UUID

from pydantic import BaseModel, Field


class GetAccountRequest(BaseModel):
    """GetAccountRequest"""

    account_id: UUID = Field(...)
