# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from uuid import UUID

from pydantic import BaseModel, Field


class SessionView(BaseModel):
    """SessionView"""

    id: UUID = Field(...)
    account_id: UUID = Field(...)
    device_label: str | None = Field(None)
    expires_at_iso: str = Field(...)
    revoked_at_iso: str | None = Field(None)
