# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from pydantic import BaseModel, EmailStr, Field
from .._scalars import StrongPassword


class SignInRequest(BaseModel):
    """SignInRequest"""

    email: EmailStr = Field(...)
    password: StrongPassword = Field(...)
    device_label: str | None = Field(None)
