# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from pydantic import AnyUrl, EmailStr
from datetime import datetime
from enum import Enum

from sqlalchemy import Column, DateTime, Enum as SAEnum
from sqlmodel import Field, SQLModel
from ..shared.soft_deletable_entity import SoftDeletableEntity


class AccountStatus(str, Enum):
    """Auto-generated enum for account_status."""

    active = "active"
    disabled = "disabled"
    pending_verification = "pending_verification"


class UserAccount(SoftDeletableEntity, table=True):
    """Primary account record owned by the identity service."""

    __tablename__ = "user_accounts"  # type: ignore

    email: EmailStr = Field(
        unique=True, max_length=320, sa_column_kwargs={"nullable": False}
    )
    display_name: str = Field(max_length=120, sa_column_kwargs={"nullable": False})
    avatar_url: AnyUrl | None = Field(default=None, max_length=512)
    locale: str | None = Field(default=None, max_length=16)
    status: AccountStatus = Field(
        sa_column=Column(
            SAEnum(AccountStatus),
            nullable=False,
            index=True,
            server_default="pending_verification",
        )
    )
    email_verified_at: datetime | None = Field(
        default=None, sa_column=Column(DateTime(timezone=True))
    )
    last_login_at: datetime | None = Field(
        default=None, sa_column=Column(DateTime(timezone=True))
    )
    disabled_at: datetime | None = Field(
        default=None, sa_column=Column(DateTime(timezone=True))
    )
