// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package audit

import (
	"github.com/google/uuid"

	file_vault_shared "github.com/example/file-vault/file_vault/shared"
)

// AuditEventView AuditEventView
type AuditEventView struct {
	ID           uuid.UUID                      `validate:"required" json:"id"`
	ActorID      *uuid.UUID                     `validate:"omitempty" json:"actorId,omitempty"`
	Action       string                         `validate:"required" json:"action"`
	ResourceType string                         `validate:"required" json:"resourceType"`
	ResourceID   *uuid.UUID                     `validate:"omitempty" json:"resourceId,omitempty"`
	Severity     AuditSeverityCode              `validate:"oneof=0 1 2 3 4 5" json:"severity"`
	CreatedAtIso string                         `validate:"required" json:"createdAtIso"`
	Metadata     []file_vault_shared.StringPair `json:"metadata"`
}
