// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	entschema "entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

// AssistantConversation User-facing conversation. Tool calls are runtime events, not primary tables.
type AssistantConversation struct {
	ent.Schema
}

func (AssistantConversation) Annotations() []entschema.Annotation {
	return []entschema.Annotation{
		entsql.Annotation{Table: "assistant_conversations"},
		entsql.WithComments(true),
	}
}

func (AssistantConversation) Mixin() []ent.Mixin {
	return []ent.Mixin{
		OwnedEntity{},
	}
}

func (AssistantConversation) Fields() []ent.Field {
	return []ent.Field{
		field.String("title").
			MaxLen(200),
		field.Enum("state").Values("active", "archived").
			Default("active"),
		field.Time("last_message_at").
			Optional().
			Nillable(),
	}
}

func (AssistantConversation) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("owner", UserAccount.Type).
			Field("owner_id").
			Unique().
			Required().
			Annotations(entsql.OnDelete(entsql.Cascade)),
	}
}
