// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
	"github.com/google/uuid"

	entschema "entgo.io/ent/schema"
)

// AssistantApproval Approval gate before an assistant mutates or shares vault content.
type AssistantApproval struct {
	ent.Schema
}

func (AssistantApproval) Annotations() []entschema.Annotation {
	return []entschema.Annotation{
		entsql.Annotation{Table: "assistant_approvals"},
		entsql.WithComments(true),
	}
}

func (AssistantApproval) Mixin() []ent.Mixin {
	return []ent.Mixin{
		Entity{},
	}
}

func (AssistantApproval) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("task_id", uuid.UUID{}),
		field.String("action").
			MaxLen(160),
		field.String("resource_type").
			MaxLen(80),
		field.UUID("resource_id", uuid.UUID{}),
		field.JSON("proposal_json", map[string]any{}),
		field.Enum("decision").Values("pending", "approved", "rejected").
			Default("pending"),
		field.UUID("decided_by", uuid.UUID{}).
			Optional().
			Nillable(),
		field.Time("decided_at").
			Optional().
			Nillable(),
	}
}

func (AssistantApproval) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("task", AssistantTask.Type).
			Field("task_id").
			Unique().
			Required().
			Annotations(entsql.OnDelete(entsql.Cascade)),
	}
}

func (AssistantApproval) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("task_id"),
	}
}
