// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
	"github.com/google/uuid"

	entschema "entgo.io/ent/schema"
)

// AssistantMessage Persisted conversation message for product history and context rebuild.
type AssistantMessage struct {
	ent.Schema
}

func (AssistantMessage) Annotations() []entschema.Annotation {
	return []entschema.Annotation{
		entsql.Annotation{Table: "assistant_messages"},
		entsql.WithComments(true),
	}
}

func (AssistantMessage) Mixin() []ent.Mixin {
	return []ent.Mixin{
		Entity{},
	}
}

func (AssistantMessage) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("conversation_id", uuid.UUID{}),
		field.Enum("role").Values("user", "assistant", "system"),
		field.Text("content"),
		field.String("model_name").
			MaxLen(120).
			Optional().
			Nillable(),
		field.Int32("token_count").
			Optional().
			Nillable(),
	}
}

func (AssistantMessage) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("conversation", AssistantConversation.Type).
			Field("conversation_id").
			Unique().
			Required().
			Annotations(entsql.OnDelete(entsql.Cascade)),
	}
}

func (AssistantMessage) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("conversation_id"),
	}
}
