// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	entschema "entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
	"github.com/google/uuid"
)

// AssistantTask Durable user-requested task that may call file services internally.
type AssistantTask struct {
	ent.Schema
}

func (AssistantTask) Annotations() []entschema.Annotation {
	return []entschema.Annotation{
		entsql.Annotation{Table: "assistant_tasks"},
		entsql.WithComments(true),
	}
}

func (AssistantTask) Mixin() []ent.Mixin {
	return []ent.Mixin{
		Entity{},
	}
}

func (AssistantTask) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("conversation_id", uuid.UUID{}),
		field.UUID("requested_by", uuid.UUID{}),
		field.String("task_type").
			MaxLen(120),
		field.Text("objective"),
		field.Enum("status").Values("queued", "running", "waiting_for_approval", "completed", "failed", "canceled").
			Default("queued"),
		field.UUID("target_node_id", uuid.UUID{}).
			Optional().
			Nillable(),
		field.Text("result_summary").
			Optional().
			Nillable(),
		field.Time("started_at").
			Optional().
			Nillable(),
		field.Time("finished_at").
			Optional().
			Nillable(),
	}
}

func (AssistantTask) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("conversation", AssistantConversation.Type).
			Field("conversation_id").
			Unique().
			Required().
			Annotations(entsql.OnDelete(entsql.Cascade)),
		edge.To("requester", UserAccount.Type).
			Field("requested_by").
			Unique().
			Required(),
	}
}

func (AssistantTask) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("conversation_id"),
		index.Fields("requested_by"),
	}
}
