// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
	"github.com/google/uuid"

	entschema "entgo.io/ent/schema"
)

// AuthSession Long-lived refresh-session family. Access tokens stay outside the DB.
type AuthSession struct {
	ent.Schema
}

func (AuthSession) Annotations() []entschema.Annotation {
	return []entschema.Annotation{
		entsql.Annotation{Table: "auth_sessions"},
		entsql.WithComments(true),
	}
}

func (AuthSession) Mixin() []ent.Mixin {
	return []ent.Mixin{
		Entity{},
	}
}

func (AuthSession) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("account_id", uuid.UUID{}),
		field.String("refresh_token_hash").
			Unique(),
		field.String("device_label").
			MaxLen(80).
			Optional().
			Nillable(),
		field.String("ip_address_hash").
			MaxLen(128).
			Optional().
			Nillable(),
		field.String("user_agent_hash").
			MaxLen(128).
			Optional().
			Nillable(),
		field.Time("expires_at"),
		field.Time("revoked_at").
			Optional().
			Nillable(),
	}
}

func (AuthSession) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("account", UserAccount.Type).
			Field("account_id").
			Unique().
			Required().
			Annotations(entsql.OnDelete(entsql.Cascade)),
	}
}

func (AuthSession) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("account_id"),
	}
}
