// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
	"github.com/google/uuid"

	entschema "entgo.io/ent/schema"
)

// ExternalIdentity External login identity linked to an account.
type ExternalIdentity struct {
	ent.Schema
}

func (ExternalIdentity) Annotations() []entschema.Annotation {
	return []entschema.Annotation{
		entsql.Annotation{Table: "external_identities"},
		entsql.WithComments(true),
	}
}

func (ExternalIdentity) Mixin() []ent.Mixin {
	return []ent.Mixin{
		Entity{},
	}
}

func (ExternalIdentity) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("account_id", uuid.UUID{}),
		field.Enum("provider").Values("google", "github", "apple", "microsoft"),
		field.String("provider_subject").
			MaxLen(256),
		field.String("email_at_provider").
			MaxLen(320).
			Optional().
			Nillable(),
		field.Time("linked_at"),
	}
}

func (ExternalIdentity) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("account", UserAccount.Type).
			Field("account_id").
			Unique().
			Required().
			Annotations(entsql.OnDelete(entsql.Cascade)),
	}
}

func (ExternalIdentity) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("account_id"),
		index.Fields("provider", "provider_subject").
			Unique(),
	}
}
