// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"

	entschema "entgo.io/ent/schema"
)

// ExtractedText Extracted searchable text. Large blobs may be stored externally.
type ExtractedText struct {
	ent.Schema
}

func (ExtractedText) Annotations() []entschema.Annotation {
	return []entschema.Annotation{
		entsql.Annotation{Table: "extracted_texts"},
		entsql.WithComments(true),
	}
}

func (ExtractedText) Mixin() []ent.Mixin {
	return []ent.Mixin{
		Entity{},
	}
}

func (ExtractedText) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("file_id", uuid.UUID{}).
			Unique(),
		field.String("language").
			Optional().
			Nillable(),
		field.Text("content"),
		field.Int32("extraction_version").
			Default(1),
	}
}

func (ExtractedText) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("file", FileMetadata.Type).
			Field("file_id").
			Unique().
			Required().
			Annotations(entsql.OnDelete(entsql.Cascade)),
	}
}
