// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
	"github.com/google/uuid"

	entschema "entgo.io/ent/schema"
)

// FileMetadata Metadata attached to file nodes.
type FileMetadata struct {
	ent.Schema
}

func (FileMetadata) Annotations() []entschema.Annotation {
	return []entschema.Annotation{
		entsql.Annotation{Table: "file_metadata"},
		entsql.WithComments(true),
	}
}

func (FileMetadata) Mixin() []ent.Mixin {
	return []ent.Mixin{
		Entity{},
	}
}

func (FileMetadata) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("node_id", uuid.UUID{}).
			Unique(),
		field.UUID("current_version_id", uuid.UUID{}).
			Optional().
			Nillable(),
		field.Enum("category").Values("unknown", "document", "image", "audio", "video", "archive").
			Default("unknown"),
		field.String("media_type").
			MaxLen(160),
		field.String("extension").
			MaxLen(32).
			Optional().
			Nillable(),
		field.Int64("size_bytes"),
		field.String("sha256").
			MaxLen(128),
	}
}

func (FileMetadata) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("node", VaultNode.Type).
			Field("node_id").
			Unique().
			Required().
			Annotations(entsql.OnDelete(entsql.Cascade)),
	}
}

func (FileMetadata) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("current_version_id"),
	}
}
