// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
	"github.com/google/uuid"

	entschema "entgo.io/ent/schema"
)

// FileVersion Immutable file version. Storage service owns the actual object.
type FileVersion struct {
	ent.Schema
}

func (FileVersion) Annotations() []entschema.Annotation {
	return []entschema.Annotation{
		entsql.Annotation{Table: "file_versions"},
		entsql.WithComments(true),
	}
}

func (FileVersion) Mixin() []ent.Mixin {
	return []ent.Mixin{
		Entity{},
	}
}

func (FileVersion) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("file_id", uuid.UUID{}),
		field.Int32("version_number"),
		field.UUID("storage_object_id", uuid.UUID{}),
		field.Int64("size_bytes"),
		field.String("sha256").
			MaxLen(128),
		field.UUID("created_by", uuid.UUID{}),
	}
}

func (FileVersion) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("file", FileMetadata.Type).
			Field("file_id").
			Unique().
			Required().
			Annotations(entsql.OnDelete(entsql.Cascade)),
		edge.To("creator", UserAccount.Type).
			Field("created_by").
			Unique().
			Required(),
	}
}

func (FileVersion) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("file_id"),
		index.Fields("storage_object_id"),
		index.Fields("created_by"),
		index.Fields("file_id", "version_number").
			Unique(),
	}
}
