// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	entschema "entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// FileSummaryRecord Latest summary surfaced in file details and search snippets.
type FileSummaryRecord struct {
	ent.Schema
}

func (FileSummaryRecord) Annotations() []entschema.Annotation {
	return []entschema.Annotation{
		entsql.Annotation{Table: "file_summaries"},
		entsql.WithComments(true),
	}
}

func (FileSummaryRecord) Mixin() []ent.Mixin {
	return []ent.Mixin{
		Entity{},
	}
}

func (FileSummaryRecord) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("file_id", uuid.UUID{}).
			Unique(),
		field.Text("summary"),
		field.String("model_name"),
		field.Time("generated_at"),
	}
}

func (FileSummaryRecord) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("file", FileMetadata.Type).
			Field("file_id").
			Unique().
			Required().
			Annotations(entsql.OnDelete(entsql.Cascade)),
	}
}
