// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	entschema "entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
	"github.com/google/uuid"
)

// NotificationPreference User preference per notification channel.
type NotificationPreference struct {
	ent.Schema
}

func (NotificationPreference) Annotations() []entschema.Annotation {
	return []entschema.Annotation{
		entsql.Annotation{Table: "notification_preferences"},
		entsql.WithComments(true),
	}
}

func (NotificationPreference) Mixin() []ent.Mixin {
	return []ent.Mixin{
		Entity{},
	}
}

func (NotificationPreference) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("account_id", uuid.UUID{}),
		field.Enum("channel").Values("in_app", "email", "webhook"),
		field.Bool("enabled").
			Default(true),
		field.JSON("quiet_hours_json", map[string]any{}).
			Optional(),
	}
}

func (NotificationPreference) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("account", UserAccount.Type).
			Field("account_id").
			Unique().
			Required().
			Annotations(entsql.OnDelete(entsql.Cascade)),
	}
}

func (NotificationPreference) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("account_id"),
		index.Fields("account_id", "channel").
			Unique(),
	}
}
