// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
	"github.com/google/uuid"

	entschema "entgo.io/ent/schema"
)

// Notification Notification visible in the product.
type Notification struct {
	ent.Schema
}

func (Notification) Annotations() []entschema.Annotation {
	return []entschema.Annotation{
		entsql.Annotation{Table: "notifications"},
		entsql.WithComments(true),
	}
}

func (Notification) Mixin() []ent.Mixin {
	return []ent.Mixin{
		Entity{},
	}
}

func (Notification) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("recipient_id", uuid.UUID{}),
		field.String("subject").
			MaxLen(160),
		field.Text("body"),
		field.String("resource_type").
			Optional().
			Nillable(),
		field.UUID("resource_id", uuid.UUID{}).
			Optional().
			Nillable(),
		field.Time("read_at").
			Optional().
			Nillable(),
	}
}

func (Notification) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("recipient", UserAccount.Type).
			Field("recipient_id").
			Unique().
			Required().
			Annotations(entsql.OnDelete(entsql.Cascade)),
	}
}

func (Notification) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("recipient_id"),
	}
}
