// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
	"entgo.io/ent/schema/mixin"
	"github.com/google/uuid"
)

// OwnedEntity Base for rows owned by an account.
type OwnedEntity struct {
	mixin.Schema
}

func (OwnedEntity) Mixin() []ent.Mixin {
	return []ent.Mixin{
		SoftDeletableEntity{},
	}
}

func (OwnedEntity) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("owner_id", uuid.UUID{}),
	}
}

func (OwnedEntity) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("owner_id"),
	}
}
