// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	entschema "entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// PasswordCredential Password credential for accounts using local authentication.
type PasswordCredential struct {
	ent.Schema
}

func (PasswordCredential) Annotations() []entschema.Annotation {
	return []entschema.Annotation{
		entsql.Annotation{Table: "password_credentials"},
		entsql.WithComments(true),
	}
}

func (PasswordCredential) Mixin() []ent.Mixin {
	return []ent.Mixin{
		Entity{},
	}
}

func (PasswordCredential) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("account_id", uuid.UUID{}).
			Unique(),
		field.String("password_hash"),
		field.String("password_algorithm").
			MaxLen(64),
		field.Time("password_updated_at"),
		field.Time("compromised_at").
			Optional().
			Nillable(),
	}
}

func (PasswordCredential) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("account", UserAccount.Type).
			Field("account_id").
			Unique().
			Required().
			Annotations(entsql.OnDelete(entsql.Cascade)),
	}
}
