// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
	"github.com/google/uuid"

	entschema "entgo.io/ent/schema"
)

// ProcessingJob Durable background job for content processing workers.
type ProcessingJob struct {
	ent.Schema
}

func (ProcessingJob) Annotations() []entschema.Annotation {
	return []entschema.Annotation{
		entsql.Annotation{Table: "processing_jobs"},
		entsql.WithComments(true),
	}
}

func (ProcessingJob) Mixin() []ent.Mixin {
	return []ent.Mixin{
		Entity{},
	}
}

func (ProcessingJob) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("file_id", uuid.UUID{}),
		field.UUID("version_id", uuid.UUID{}).
			Optional().
			Nillable(),
		field.Enum("kind").Values("classify", "extract_text", "summarize", "generate_preview", "scan_malware"),
		field.Enum("status").Values("queued", "running", "succeeded", "failed", "canceled").
			Default("queued"),
		field.Int32("priority").
			Default(100),
		field.Int32("attempts").
			Default(0),
		field.Time("scheduled_at"),
		field.Time("started_at").
			Optional().
			Nillable(),
		field.Time("finished_at").
			Optional().
			Nillable(),
		field.String("error_message").
			MaxLen(512).
			Optional().
			Nillable(),
		field.JSON("parameters_json", map[string]any{}).
			Optional(),
	}
}

func (ProcessingJob) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("file", FileMetadata.Type).
			Field("file_id").
			Unique().
			Required().
			Annotations(entsql.OnDelete(entsql.Cascade)),
	}
}

func (ProcessingJob) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("file_id"),
		index.Fields("version_id"),
		index.Fields("status"),
	}
}
