// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema/field"

	entschema "entgo.io/ent/schema"
)

// SearchIndexCheckpoint Checkpoint for async index workers.
type SearchIndexCheckpoint struct {
	ent.Schema
}

func (SearchIndexCheckpoint) Annotations() []entschema.Annotation {
	return []entschema.Annotation{
		entsql.Annotation{Table: "search_index_checkpoints"},
		entsql.WithComments(true),
	}
}

func (SearchIndexCheckpoint) Mixin() []ent.Mixin {
	return []ent.Mixin{
		Entity{},
	}
}

func (SearchIndexCheckpoint) Fields() []ent.Field {
	return []ent.Field{
		field.String("shard_key").
			Unique(),
		field.String("last_processed_event_id").
			Optional().
			Nillable(),
		field.Time("last_processed_at").
			Optional().
			Nillable(),
	}
}
