// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	entschema "entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
	"github.com/google/uuid"
)

// ShareLink Public or restricted link token. Token secret is stored hashed.
type ShareLink struct {
	ent.Schema
}

func (ShareLink) Annotations() []entschema.Annotation {
	return []entschema.Annotation{
		entsql.Annotation{Table: "share_links"},
		entsql.WithComments(true),
	}
}

func (ShareLink) Mixin() []ent.Mixin {
	return []ent.Mixin{
		Entity{},
	}
}

func (ShareLink) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("resource_node_id", uuid.UUID{}),
		field.UUID("created_by", uuid.UUID{}),
		field.String("token_hash").
			Unique(),
		field.Enum("role").Values("viewer", "commenter", "editor").
			Default("viewer"),
		field.String("password_hash").
			Optional().
			Nillable(),
		field.Int32("max_downloads").
			Optional().
			Nillable(),
		field.Int32("download_count").
			Default(0),
		field.Time("expires_at").
			Optional().
			Nillable(),
		field.Time("revoked_at").
			Optional().
			Nillable(),
	}
}

func (ShareLink) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("resource", VaultNode.Type).
			Field("resource_node_id").
			Unique().
			Required().
			Annotations(entsql.OnDelete(entsql.Cascade)),
		edge.To("creator", UserAccount.Type).
			Field("created_by").
			Unique().
			Required(),
	}
}

func (ShareLink) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("resource_node_id"),
		index.Fields("created_by"),
	}
}
