// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	entschema "entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
	"github.com/google/uuid"
)

// ShareGrant Direct grant from an owner to another principal.
type ShareGrant struct {
	ent.Schema
}

func (ShareGrant) Annotations() []entschema.Annotation {
	return []entschema.Annotation{
		entsql.Annotation{Table: "share_grants"},
		entsql.WithComments(true),
	}
}

func (ShareGrant) Mixin() []ent.Mixin {
	return []ent.Mixin{
		Entity{},
	}
}

func (ShareGrant) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("resource_node_id", uuid.UUID{}),
		field.UUID("granted_by", uuid.UUID{}),
		field.Enum("subject_kind").Values("account", "email", "organization"),
		field.String("subject").
			MaxLen(320),
		field.Enum("role").Values("viewer", "commenter", "editor"),
		field.Time("expires_at").
			Optional().
			Nillable(),
		field.Time("revoked_at").
			Optional().
			Nillable(),
	}
}

func (ShareGrant) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("resource", VaultNode.Type).
			Field("resource_node_id").
			Unique().
			Required().
			Annotations(entsql.OnDelete(entsql.Cascade)),
		edge.To("grantor", UserAccount.Type).
			Field("granted_by").
			Unique().
			Required(),
	}
}

func (ShareGrant) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("resource_node_id"),
		index.Fields("granted_by"),
	}
}
