// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
	"entgo.io/ent/schema/mixin"
)

// SoftDeletableEntity Base for rows that should support soft deletion.
type SoftDeletableEntity struct {
	mixin.Schema
}

func (SoftDeletableEntity) Mixin() []ent.Mixin {
	return []ent.Mixin{
		Entity{},
	}
}

func (SoftDeletableEntity) Fields() []ent.Field {
	return []ent.Field{
		field.Time("deleted_at").
			Optional().
			Nillable(),
	}
}

func (SoftDeletableEntity) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("deleted_at"),
	}
}
