// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	entschema "entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
	"github.com/google/uuid"
)

// StorageObject Physical object. Metadata service references this by id.
type StorageObject struct {
	ent.Schema
}

func (StorageObject) Annotations() []entschema.Annotation {
	return []entschema.Annotation{
		entsql.Annotation{Table: "storage_objects"},
		entsql.WithComments(true),
	}
}

func (StorageObject) Mixin() []ent.Mixin {
	return []ent.Mixin{
		Entity{},
	}
}

func (StorageObject) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("bucket_id", uuid.UUID{}),
		field.String("object_key").
			Unique(),
		field.Int64("size_bytes"),
		field.String("sha256").
			MaxLen(128),
		field.String("media_type").
			MaxLen(160),
		field.Enum("state").Values("pending", "available", "quarantined", "deleted").
			Default("pending"),
		field.String("encryption_key_ref").
			Optional().
			Nillable(),
	}
}

func (StorageObject) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("bucket", StorageBucket.Type).
			Field("bucket_id").
			Unique().
			Required().
			Annotations(entsql.OnDelete(entsql.Restrict)),
	}
}

func (StorageObject) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("bucket_id"),
	}
}
