// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"

	entschema "entgo.io/ent/schema"
)

// UserAccount Primary account record owned by the identity service.
type UserAccount struct {
	ent.Schema
}

func (UserAccount) Annotations() []entschema.Annotation {
	return []entschema.Annotation{
		entsql.Annotation{Table: "user_accounts"},
		entsql.WithComments(true),
	}
}

func (UserAccount) Mixin() []ent.Mixin {
	return []ent.Mixin{
		SoftDeletableEntity{},
	}
}

func (UserAccount) Fields() []ent.Field {
	return []ent.Field{
		field.String("email").
			MaxLen(320).
			Unique(),
		field.String("display_name").
			MaxLen(120),
		field.String("avatar_url").
			MaxLen(512).
			Optional().
			Nillable(),
		field.String("locale").
			MaxLen(16).
			Optional().
			Nillable(),
		field.Enum("status").Values("active", "disabled", "pending_verification").
			Default("pending_verification"),
		field.Time("email_verified_at").
			Optional().
			Nillable(),
		field.Time("last_login_at").
			Optional().
			Nillable(),
		field.Time("disabled_at").
			Optional().
			Nillable(),
	}
}

func (UserAccount) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("status"),
	}
}
