# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from pydantic import BaseModel, Field
from ..shared.page_info import PageInfo
from .search_hit import SearchHit


class SearchFilesResponse(BaseModel):
    """SearchFilesResponse"""

    hits: list[SearchHit] = Field(...)
    page: PageInfo = Field(...)
