# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from pydantic import BaseModel, Field
from ..metadata.file_view import FileView


class SearchHit(BaseModel):
    """SearchHit"""

    file: FileView = Field(...)
    snippet: str | None = Field(None)
    score: float = Field(...)
