// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
	"github.com/google/uuid"

	entschema "entgo.io/ent/schema"
)


// UploadPart Chunk or multipart part recorded for resumable uploads.
type UploadPart struct {
	ent.Schema
}

func (UploadPart) Annotations() []entschema.Annotation {
	return []entschema.Annotation{
		entsql.Annotation{Table: "upload_parts"},
		entsql.WithComments(true),
	}
}

func (UploadPart) Mixin() []ent.Mixin {
	return []ent.Mixin{
		Entity{},
	}
}

func (UploadPart) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("upload_session_id", uuid.UUID{}),
		field.Int32("part_number"),
		field.Int64("offset_bytes"),
		field.Int64("size_bytes"),
		field.String("sha256").
			MaxLen(128),
	}
}

func (UploadPart) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("upload_session", UploadSession.Type).
			Field("upload_session_id").
			Unique().
			Required().
			Annotations(entsql.OnDelete(entsql.Cascade)),
	}
}

func (UploadPart) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("upload_session_id"),
		index.Fields("upload_session_id", "part_number").
			Unique(),
	}
}
