// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
	"github.com/google/uuid"

	entschema "entgo.io/ent/schema"
)


// UploadSession Durable upload session for chunked or signed-url uploads.
type UploadSession struct {
	ent.Schema
}

func (UploadSession) Annotations() []entschema.Annotation {
	return []entschema.Annotation{
		entsql.Annotation{Table: "upload_sessions"},
		entsql.WithComments(true),
	}
}

func (UploadSession) Mixin() []ent.Mixin {
	return []ent.Mixin{
		Entity{},
	}
}

func (UploadSession) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("account_id", uuid.UUID{}),
		field.UUID("bucket_id", uuid.UUID{}),
		field.UUID("storage_object_id", uuid.UUID{}).
			Optional().
			Nillable(),
		field.String("file_name").
			MaxLen(240),
		field.Int64("expected_size_bytes"),
		field.Enum("state").Values("initiated", "receiving", "completed", "aborted", "expired").
			Default("initiated"),
		field.Time("expires_at"),
		field.Time("completed_at").
			Optional().
			Nillable(),
	}
}

func (UploadSession) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("account", UserAccount.Type).
			Field("account_id").
			Unique().
			Required().
			Annotations(entsql.OnDelete(entsql.Cascade)),
		edge.To("bucket", StorageBucket.Type).
			Field("bucket_id").
			Unique().
			Required(),
	}
}

func (UploadSession) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("account_id"),
		index.Fields("bucket_id"),
		index.Fields("storage_object_id"),
	}
}
