import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const AccountViewSchema = z.object({
  id: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  email: z.string().email(),
  displayName: z.string(),
  avatarUrl: z.string().optional(),
  locale: z.string().optional(),
  status: z.union([z.literal(0), z.literal(1), z.literal(2), z.literal(3)]),
})
export type AccountView = z.infer<typeof AccountViewSchema>;

export const AccountViewMeta = {
  email: { inputType: "email" },
} as const;
