import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const GetAccountRequestSchema = z.object({
  accountId: z.uuid(),
})
export type GetAccountRequest = z.infer<typeof GetAccountRequestSchema>;
