import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const GetAccountRequestSchema = z.object({
  accountId: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
})
export type GetAccountRequest = z.infer<typeof GetAccountRequestSchema>;
