import { z } from "zod";
import { SessionViewSchema } from "./SessionView.js";
import { PageInfoSchema } from "../shared/PageInfo.js";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const ListSessionsResponseSchema = z.object({
  sessions: z.array(SessionViewSchema),
  page: PageInfoSchema,
})
export type ListSessionsResponse = z.infer<typeof ListSessionsResponseSchema>;
