import { z } from "zod";
import { PageRequestSchema } from "../shared/PageRequest.js";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const ListSessionsRequestSchema = z.object({
  accountId: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  page: PageRequestSchema,
})
export type ListSessionsRequest = z.infer<typeof ListSessionsRequestSchema>;
