import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const RefreshSessionRequestSchema = z.object({
  refreshToken: z.string(),
})
export type RefreshSessionRequest = z.infer<typeof RefreshSessionRequestSchema>;
