import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const RevokeSessionRequestSchema = z.object({
  sessionId: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  accountId: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
})
export type RevokeSessionRequest = z.infer<typeof RevokeSessionRequestSchema>;
