import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const SessionViewSchema = z.object({
  id: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  accountId: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  deviceLabel: z.string().optional(),
  expiresAtIso: z.string(),
  revokedAtIso: z.string().optional(),
})
export type SessionView = z.infer<typeof SessionViewSchema>;
