import { z } from "zod";
import { AccountViewSchema } from "./AccountView.js";
import { SessionViewSchema } from "./SessionView.js";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const SignInResponseSchema = z.object({
  account: AccountViewSchema,
  session: SessionViewSchema,
  accessToken: z.string(),
  refreshToken: z.string(),
})
export type SignInResponse = z.infer<typeof SignInResponseSchema>;
