// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

// Package demo contains generated GORM models.
package demo

import (
	demo_game_platform_accounts "github.com/demo-user/demo/demo/game_platform/accounts"
	demo_game_platform_audit "github.com/demo-user/demo/demo/game_platform/audit"
	demo_game_platform_collaboration_invites "github.com/demo-user/demo/demo/game_platform/collaboration/invites"
	demo_game_platform_content_characters "github.com/demo-user/demo/demo/game_platform/content/characters"
	demo_game_platform_content_events "github.com/demo-user/demo/demo/game_platform/content/events"
	demo_game_platform_content_places "github.com/demo-user/demo/demo/game_platform/content/places"
	demo_game_platform_content_stories "github.com/demo-user/demo/demo/game_platform/content/stories"
	demo_game_platform_content_taxonomy "github.com/demo-user/demo/demo/game_platform/content/taxonomy"
	demo_game_platform_worlds "github.com/demo-user/demo/demo/game_platform/worlds"
	"gorm.io/gorm"
)

// Init initializes all models with GORM.
// Returns a slice of all registered models for auto-migration.
func Init(db *gorm.DB) error {
	return db.AutoMigrate(
		&demo_game_platform_accounts.Badge{},
		&demo_game_platform_accounts.Subscription{},
		&demo_game_platform_accounts.User{},
		&demo_game_platform_audit.AuditLog{},
		&demo_game_platform_collaboration_invites.Invitation{},
		&demo_game_platform_content_characters.Npc{},
		&demo_game_platform_content_events.GameEvent{},
		&demo_game_platform_content_places.Location{},
		&demo_game_platform_content_stories.StoryNode{},
		&demo_game_platform_content_taxonomy.Tag{},
		&demo_game_platform_worlds.World{},
	)
}
