# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from pydantic import BaseModel, Field


class Ack(BaseModel):
    """Ack"""

    ok: bool = Field(...)
    message: str | None = Field(None)
