# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from pydantic import BaseModel, Field
from .._scalars import PageSize


class PageRequest(BaseModel):
    """PageRequest"""

    page_size: PageSize = Field(...)
    page_token: str | None = Field(None)
