# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from typing import TYPE_CHECKING
from datetime import datetime
from uuid import UUID
from enum import Enum

from sqlalchemy import Column, DateTime, Enum as SAEnum, ForeignKey, Index, Text
from sqlmodel import Field, Relationship, SQLModel
from ...shared.timestamped import Timestamped


if TYPE_CHECKING:
    from ...accounts.user import User
    from ...worlds.world import World


class InvitationStatus(str, Enum):
    """Auto-generated enum for invitation_status."""

    pending = "pending"
    accepted = "accepted"
    revoked = "revoked"
    expired = "expired"


class Invitation(Timestamped, table=True):
    """Invitation record linking a user email to a shared world. Demonstrates cross-namespace lookup types and relations on the same table."""

    __tablename__ = "world_invitations"  # type: ignore
    __table_args__ = (
        Index("world_invitations_inviter_id_status_idx", "inviter_id", "status"),
    )

    # Email of the invitee - inherits validators from Accounts.User.email.
    invitee_email: str = Field(
        max_length=320,
        sa_column_kwargs={
            "nullable": False,
            "comment": "Email of the invitee - inherits validators from Accounts.User.email.",
        },
    )
    # Unique redeem code sent through email or copied in the UI.
    redeem_code: str = Field(
        unique=True,
        max_length=64,
        sa_column_kwargs={
            "nullable": False,
            "comment": "Unique redeem code sent through email or copied in the UI.",
        },
    )
    # Current lifecycle state for the invitation.
    status: InvitationStatus = Field(
        sa_column=Column(
            SAEnum(InvitationStatus),
            nullable=False,
            index=True,
            server_default="pending",
            comment="Current lifecycle state for the invitation.",
        )
    )
    # Optional personal note from the inviter.
    message: str | None = Field(
        default=None,
        max_length=1000,
        sa_column=Column(Text, comment="Optional personal note from the inviter."),
    )
    # When the invitation expires, if at all.
    expires_at: datetime | None = Field(
        default=None,
        sa_column=Column(
            DateTime(timezone=True), comment="When the invitation expires, if at all."
        ),
    )
    # When the invitation was accepted by the recipient.
    accepted_at: datetime | None = Field(
        default=None,
        sa_column=Column(
            DateTime(timezone=True),
            comment="When the invitation was accepted by the recipient.",
        ),
    )
    inviter_id: UUID = Field(
        sa_column=Column(
            ForeignKey("users.id", ondelete="CASCADE", onupdate="CASCADE"),
            nullable=False,
            index=True,
        )
    )
    world_id: UUID = Field(
        sa_column=Column(
            ForeignKey("worlds.id", ondelete="CASCADE", onupdate="CASCADE"),
            nullable=False,
            index=True,
        )
    )

    # ─── Relationships ─────────────────────
    # User who created the invitation.
    inviter: User | None = Relationship()
    # World the invite grants access to.
    world: World | None = Relationship()
