/**
 * @qninhdt/typespec-gorm
 *
 * TypeSpec emitter that generates GORM (Go) model structs from
 * models decorated with @table and related decorators from @qninhdt/typespec-orm.
 */

import type { EmitContext, Enum, Model, ModelProperty, Program } from "@typespec/compiler";
import type { EnumMemberInfo, ResolvedRelation } from "@qninhdt/typespec-orm";
import {
  collectTableModels,
  collectDataModels,
  getTitle,
  getPlaceholder,
  getColumnName,
  getCompositeIndexes,
  getCompositeUniques,
  getDefaultValue,
  getDoc,
  getForeignKey,
  getFormat,
  getIndexName,
  getMaxLength,
  getMinLength,
  getMinValue,
  getMaxValue,
  getOnDelete,
  getOnUpdate,
  getPattern,
  getPrecision,
  getPropertyEnum,
  isAutoCreateTime,
  isAutoIncrement,
  isAutoUpdateTime,
  isId,
  isIndex,
  isSoftDelete,
  isUnique,
  resolveDbType,
  camelToPascal,
  camelToSnake,
  // Shared emitter utilities
  NUMERIC_TYPES,
  deduplicateParts,
  classifyProperties,
} from "@qninhdt/typespec-orm";
import { reportDiagnostic, type GormEmitterOptions } from "./lib.js";
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

// ─── Constants ───────────────────────────────────────────────────────────────

const FILE_HEADER =
  "// Code generated by @qninhdt/typespec-gorm. DO NOT EDIT.\n// Source: https://github.com/qninhdt/typespec-libraries\n\n";

/** Maps canonical DB type names → Go types */
const GO_TYPE_MAP: Record<string, { goType: string; gormType: string; imports?: string[] }> = {
  uuid: {
    goType: "uuid.UUID",
    gormType: "uuid",
    imports: ["github.com/google/uuid"],
  },
  string: { goType: "string", gormType: "varchar(255)" },
  text: { goType: "string", gormType: "text" },
  boolean: { goType: "bool", gormType: "boolean" },
  int8: { goType: "int8", gormType: "smallint" },
  int16: { goType: "int16", gormType: "smallint" },
  int32: { goType: "int32", gormType: "integer" },
  int64: { goType: "int64", gormType: "bigint" },
  uint8: { goType: "uint8", gormType: "smallint" },
  uint16: { goType: "uint16", gormType: "integer" },
  uint32: { goType: "uint32", gormType: "bigint" },
  uint64: { goType: "uint64", gormType: "bigint" },
  float32: { goType: "float32", gormType: "real" },
  float64: { goType: "float64", gormType: "double precision" },
  decimal: {
    goType: "decimal.Decimal",
    gormType: "numeric",
    imports: ["github.com/shopspring/decimal"],
  },
  serial: { goType: "int32", gormType: "serial" },
  bigserial: { goType: "int64", gormType: "bigserial" },
  utcDateTime: {
    goType: "time.Time",
    gormType: "timestamptz",
    imports: ["time"],
  },
  date: { goType: "time.Time", gormType: "date", imports: ["time"] },
  time: { goType: "time.Time", gormType: "time", imports: ["time"] },
  duration: {
    goType: "time.Duration",
    gormType: "interval",
    imports: ["time"],
  },
  bytes: { goType: "[]byte", gormType: "bytea" },
  jsonb: {
    goType: "datatypes.JSON",
    gormType: "jsonb",
    imports: ["gorm.io/datatypes"],
  },
};

// ─── Types ───────────────────────────────────────────────────────────────────

/** Maps @format values → go-playground/validator v10 tag names */
const GO_FORMAT_VALIDATORS: Record<string, string> = {
  email: "email",
  uri: "url",
  url: "url",
  uuid: "uuid",
  ipv4: "ipv4",
  ipv6: "ipv6",
  ip: "ip",
  cidr: "cidr",
  mac: "mac",
  base64: "base64",
  hostname: "hostname",
  latitude: "latitude",
  longitude: "longitude",
};

interface CompositeFieldTag {
  /** "index" or "uniqueIndex" */
  kind: "index" | "uniqueIndex";
  /** Name of the composite constraint */
  name: string;
  /** 1-based position in the column list */
  priority: number;
}

interface GoTypeResult {
  goType: string;
  gormTag: string;
  requiredImports: string[];
  /** @doc text (if any) - used for both gorm comment: tag and // line comment */
  doc: string | undefined;
}

// ─── Emitter entry point ─────────────────────────────────────────────────────

export async function emit(context: EmitContext<GormEmitterOptions>): Promise<void> {
  const { program } = context;
  const outputDir = context.emitterOutputDir;
  const packageName = context.options["package-name"] ?? "models";

  const tables = collectTableModels(program);
  const dataModels = collectDataModels(program);

  if (tables.length === 0 && dataModels.length === 0) {
    reportDiagnostic(program, {
      code: "no-tables-found",
      target: program.getGlobalNamespaceType(),
    });
    return;
  }

  await mkdir(outputDir, { recursive: true });

  for (const { model, tableName } of tables) {
    const code = generateGormModel(program, model, tableName, packageName);
    const fileName = camelToSnake(model.name) + ".go";
    try {
      await writeFile(join(outputDir, fileName), code);
    } catch (err) {
      reportDiagnostic(program, {
        code: "emit-write-failed",
        messageId: "default",
        format: { fileName, error: String(err) },
        target: model,
      });
    }
  }

  for (const { model, label } of dataModels) {
    const code = generateDataGoStruct(program, model, label, packageName);
    const fileName = camelToSnake(model.name) + ".go";
    try {
      await writeFile(join(outputDir, fileName), code);
    } catch (err) {
      reportDiagnostic(program, {
        code: "emit-write-failed",
        messageId: "default",
        format: { fileName, error: String(err) },
        target: model,
      });
    }
  }
}

// ─── Composite map builder ──────────────────────────────────────────────────

/**
 * Build a lookup from column name → composite index/unique tags for that field.
 */
function buildCompositeMap(
  indexes: { name: string; columns: string[] }[],
  uniques: { name: string; columns: string[] }[],
): Map<string, CompositeFieldTag[]> {
  const map = new Map<string, CompositeFieldTag[]>();

  const addEntries = (
    constraints: { name: string; columns: string[] }[],
    kind: CompositeFieldTag["kind"],
  ) => {
    for (const c of constraints) {
      for (let i = 0; i < c.columns.length; i++) {
        const col = c.columns[i];
        const tags = map.get(col) ?? [];
        tags.push({ kind, name: c.name, priority: i + 1 });
        map.set(col, tags);
      }
    }
  };

  addEntries(indexes, "index");
  addEntries(uniques, "uniqueIndex");
  return map;
}

// ─── Enum code generation ───────────────────────────────────────────────────

/**
 * Generate Go `type X string` + `const` block for an enum type.
 */
function generateEnumBlock(enumName: string, members: EnumMemberInfo[]): string {
  const goTypeName = camelToPascal(enumName);
  let code = `// ${goTypeName} represents the ${camelToSnake(enumName)} enum.\n`;
  code += `type ${goTypeName} string\n\n`;
  code += "const (\n";
  for (const m of members) {
    const constName = `${goTypeName}${camelToPascal(m.name)}`;
    code += `\t${constName} ${goTypeName} = "${m.value}"\n`;
  }
  code += ")\n";
  return code;
}

// ─── @data model code generation ────────────────────────────────────────────

/**
 * Generate a single struct field for a @data model.
 * Emits validate + json tags only (no gorm tag).
 */
function generateDataGoField(program: Program, prop: ModelProperty, imports: Set<string>): string {
  const fieldName = camelToPascal(prop.name);
  const dbType = resolveDbType(prop.type);
  const mapping = dbType ? GO_TYPE_MAP[dbType] : undefined;

  const enumInfo = getPropertyEnum(prop);
  let goType = mapping?.goType ?? "interface{}";
  if (enumInfo) {
    goType = camelToPascal(enumInfo.enumType.name);
  }
  if (mapping?.imports) {
    for (const imp of mapping.imports) imports.add(imp);
  }

  const isOpt = prop.optional;
  const finalGoType =
    isOpt && !goType.startsWith("*") && !goType.startsWith("[]") ? `*${goType}` : goType;

  const validateTag = buildValidateTag(program, prop);
  const jsonOmit = isOpt ? ",omitempty" : "";
  const doc = getDoc(program, prop);
  const docComment = doc ? `\t// ${doc}\n` : "";

  const title = getTitle(program, prop);
  const placeholder = getPlaceholder(program, prop);
  const labelTag =
    title || placeholder
      ? ` form:"${prop.name}${title ? `,title=${title}` : ""}${placeholder ? `,placeholder=${placeholder}` : ""}"`
      : "";

  const structTags = validateTag
    ? `validate:"${validateTag}" json:"${prop.name}${jsonOmit}"${labelTag}`
    : `json:"${prop.name}${jsonOmit}"${labelTag}`;

  return `${docComment}\t${fieldName} ${finalGoType} \`${structTags}\`\n`;
}

/**
 * Generate a Go struct for a @data model (form payload / DTO).
 * No gorm tags, no TableName() - just validate + json struct tags.
 */
function generateDataGoStruct(
  program: Program,
  model: Model,
  label: string,
  packageName: string,
): string {
  const imports = new Set<string>();
  const fields: string[] = [];
  const enumTypes = new Map<string, EnumMemberInfo[]>();

  for (const [, prop] of model.properties) {
    const enumInfo = getPropertyEnum(prop);
    if (enumInfo && !enumTypes.has(enumInfo.enumType.name)) {
      enumTypes.set(enumInfo.enumType.name, enumInfo.members);
    }
    fields.push(generateDataGoField(program, prop, imports));
  }

  const structName = model.name;
  const sortedImports = [...imports].sort();

  let code = FILE_HEADER;
  code += `package ${packageName}\n\n`;

  if (sortedImports.length > 0) {
    code += "import (\n";
    const stdImports = sortedImports.filter((i) => !i.includes("."));
    const extImports = sortedImports.filter((i) => i.includes("."));
    for (const imp of stdImports) code += `\t"${imp}"\n`;
    if (stdImports.length > 0 && extImports.length > 0) code += "\n";
    for (const imp of extImports) code += `\t"${imp}"\n`;
    code += ")\n\n";
  }

  for (const [enumName, members] of enumTypes) {
    code += generateEnumBlock(enumName, members);
    code += "\n";
  }

  const modelDoc = getDoc(program, model);
  code += `// ${structName} ${modelDoc ?? label}\n`;
  code += `type ${structName} struct {\n`;
  for (const field of fields) {
    code += field;
  }
  code += "}\n";

  return code;
}

// ─── Code generation ─────────────────────────────────────────────────────────

function generateGormModel(
  program: Program,
  model: Model,
  tableName: string,
  packageName: string,
): string {
  const imports = new Set<string>();
  const fields: string[] = [];
  const relationFields: string[] = [];

  // Build composite constraint map for field-level GORM tags
  const compIdxs = getCompositeIndexes(program, model);
  const compUnqs = getCompositeUniques(program, model);
  const compositeMap = buildCompositeMap(compIdxs, compUnqs);

  // Classify properties using shared utility
  const {
    enumTypes,
    ignored,
    relations,
    fields: regularProps,
  } = classifyProperties(program, model);

  // Ignored fields → gorm:"-"
  for (const { prop, enumInfo } of ignored) {
    const fieldName = camelToPascal(prop.name);
    const dbType = resolveDbType(prop.type);
    const mapping = dbType ? GO_TYPE_MAP[dbType] : undefined;
    let goType = mapping?.goType ?? "interface{}";
    if (enumInfo) {
      goType = camelToPascal(enumInfo.enumType.name);
    }
    if (mapping?.imports) {
      for (const imp of mapping.imports) imports.add(imp);
    }
    const isOpt = prop.optional;
    const finalGoType =
      isOpt && !goType.startsWith("*") && !goType.startsWith("[]") ? `*${goType}` : goType;
    const jsonOmit = isOpt ? ",omitempty" : "";
    const doc = getDoc(program, prop);
    const docComment = doc ? `\t// ${doc}\n` : "";
    fields.push(
      `${docComment}\t${fieldName} ${finalGoType} \`gorm:"-" json:"${prop.name}${jsonOmit}"\`\n`,
    );
  }

  // Relation navigation properties (no DB column, just GORM struct reference)
  for (const { prop, resolved } of relations) {
    if (resolved.autoInjectFk) {
      fields.push(generateAutoFkField(program, prop, resolved, imports, compositeMap));
    }
    relationFields.push(generateResolvedRelationField(program, prop, resolved));
  }

  // Regular DB-mapped fields
  for (const { prop } of regularProps) {
    fields.push(generateField(program, prop, imports, compositeMap));
  }

  const structName = model.name;
  const sortedImports = [...imports].sort();

  let code = FILE_HEADER;
  code += `package ${packageName}\n\n`;

  if (sortedImports.length > 0) {
    code += "import (\n";
    const stdImports = sortedImports.filter((i) => !i.includes("."));
    const extImports = sortedImports.filter((i) => i.includes("."));

    for (const imp of stdImports) {
      code += `\t"${imp}"\n`;
    }
    if (stdImports.length > 0 && extImports.length > 0) {
      code += "\n";
    }
    for (const imp of extImports) {
      code += `\t"${imp}"\n`;
    }
    code += ")\n\n";
  }

  // Emit enum type definitions before the struct
  for (const [enumName, members] of enumTypes) {
    code += generateEnumBlock(enumName, members);
    code += "\n";
  }

  // Model-level @doc as comment, or default
  const modelDoc = getDoc(program, model);
  if (modelDoc) {
    code += `// ${structName} ${modelDoc}\n`;
  } else {
    code += `// ${structName} represents the ${tableName} table.\n`;
  }

  code += `type ${structName} struct {\n`;
  for (const field of fields) {
    code += field;
  }
  if (relationFields.length > 0) {
    code += "\n\t// ─── Relationships ─────────────────────\n";
    for (const rf of relationFields) {
      code += rf;
    }
  }
  code += "}\n\n";

  code += `// TableName returns the table name for ${structName}.\n`;
  code += `func (${structName}) TableName() string {\n`;
  code += `\treturn "${tableName}"\n`;
  code += "}\n";

  return code;
}

/**
 * Generate a GORM struct field for an auto-injected foreign key column.
 * Called for many-to-one / one-to-one relations where the FK is auto-derived.
 */
function generateAutoFkField(
  program: Program,
  relationProp: ModelProperty,
  rel: ResolvedRelation,
  imports: Set<string>,
  compositeMap: Map<string, CompositeFieldTag[]>,
): string {
  const goFieldName = camelToPascal(relationProp.name + "Id");
  const columnName = rel.fkColumnName;

  const mapping = rel.fkDbType ? GO_TYPE_MAP[rel.fkDbType] : GO_TYPE_MAP["uuid"];
  const goType = mapping?.goType ?? "interface{}";
  if (mapping?.imports) {
    for (const imp of mapping.imports) imports.add(imp);
  }

  const isOpt = relationProp.optional;
  const finalGoType =
    isOpt && !goType.startsWith("*") && !goType.startsWith("[]") ? `*${goType}` : goType;

  const tagParts: string[] = [];
  tagParts.push(`column:${columnName}`);
  if (mapping?.gormType) tagParts.push(`type:${mapping.gormType}`);
  if (!isOpt) tagParts.push("not null");

  // Composite index tags (FK column may appear in composite constraints)
  const compositeTags = compositeMap.get(columnName);

  // FK columns always need an index for join performance
  if (isUnique(program, relationProp)) {
    // @unique → uniqueIndex covers the lookup; no standalone index needed
    tagParts.push("uniqueIndex");
  } else if (rel.autoInjectIndex) {
    const idxName = getIndexName(program, relationProp);
    tagParts.push(idxName ? `index:${idxName}` : "index");
  }

  if (compositeTags) {
    for (const ct of compositeTags) {
      tagParts.push(`${ct.kind}:${ct.name},priority:${ct.priority}`);
    }
  }

  // Note: ON DELETE / ON UPDATE constraints are emitted on the navigation field, not here.

  // @doc on relation → comment on FK column
  const doc = getDoc(program, relationProp);
  if (doc) {
    tagParts.push(`comment:${doc.replace(/;/g, ",").replace(/"/g, "'")}`);
  }

  const gormTag = deduplicateParts(tagParts).join(";");
  const jsonName = relationProp.name + "Id";
  const jsonOmit = isOpt ? ",omitempty" : "";

  const docComment = doc ? `\t// ${doc}\n` : "";
  return `${docComment}\t${goFieldName} ${finalGoType} \`gorm:"${gormTag}" json:"${jsonName}${jsonOmit}"\`\n`;
}

/**
 * Generate a GORM struct field for a relation navigation property.
 * - many-to-one: `Owner *User` (GORM auto-detects FK by naming convention)
 * - one-to-many: `StoryNodes []StoryNode` with `foreignKey:XID` tag
 */
function generateResolvedRelationField(
  program: Program,
  prop: ModelProperty,
  rel: ResolvedRelation,
): string {
  const fieldName = camelToPascal(prop.name);
  const goRefType = rel.targetModel.name;

  const gormParts: string[] = [];

  // Always specify foreignKey explicitly - prevents GORM from guessing the wrong field
  if (rel.kind === "many-to-one" || rel.kind === "one-to-one") {
    // FK column lives on this model; reference the auto-injected Go field name
    const goFkFieldName = camelToPascal(prop.name + "Id");
    gormParts.push(`foreignKey:${goFkFieldName}`);
  } else if (rel.kind === "one-to-many") {
    if (rel.inverseFkFieldName) {
      gormParts.push(`foreignKey:${rel.inverseFkFieldName}`);
    } else {
      reportDiagnostic(program, {
        code: "missing-back-reference",
        format: {
          propName: prop.name,
          modelName: (prop.model as Model)?.name ?? "<unknown>",
          targetModel: rel.targetModel.name,
        },
        target: prop,
      });
    }
  }

  // Cascade constraints belong on the navigation field (GORM best practice)
  const constraintParts: string[] = [];
  if (rel.onDelete) constraintParts.push(`OnDelete:${rel.onDelete}`);
  if (rel.onUpdate) constraintParts.push(`OnUpdate:${rel.onUpdate}`);
  if (constraintParts.length > 0) {
    gormParts.push(`constraint:${constraintParts.join(",")}`);
  }

  const gormTag = gormParts.length > 0 ? gormParts.join(";") : "";

  const isMany = rel.kind === "one-to-many" || rel.kind === "many-to-many";
  const finalType = isMany ? `[]${goRefType}` : goRefType;
  // Navigation properties: pointer for optional singular refs (GORM nullable FK), value type otherwise
  const wrappedType = !isMany && prop.optional ? `*${finalType}` : finalType;

  const doc = getDoc(program, prop);
  const docComment = doc ? `\t// ${doc}\n` : "";
  if (gormTag) {
    return `${docComment}\t${fieldName} ${wrappedType} \`gorm:"${gormTag}" json:"${prop.name},omitempty"\`\n`;
  }
  return `${docComment}\t${fieldName} ${wrappedType} \`json:"${prop.name},omitempty"\`\n`;
}

function generateField(
  program: Program,
  prop: ModelProperty,
  imports: Set<string>,
  compositeMap: Map<string, CompositeFieldTag[]>,
): string {
  const fieldName = camelToPascal(prop.name);
  const columnName = getColumnName(program, prop);
  const isSoft = isSoftDelete(program, prop);

  // Soft delete gets special GORM type
  if (isSoft) {
    imports.add("gorm.io/gorm");
    const gormTag = `column:${columnName};index`;
    return `\t${fieldName} gorm.DeletedAt \`gorm:"${gormTag}" json:"${prop.name}"\`\n`;
  }

  const { goType, gormTag, requiredImports, doc } = resolveGoType(
    program,
    prop,
    columnName,
    compositeMap,
  );

  for (const imp of requiredImports) {
    imports.add(imp);
  }

  const isOpt = prop.optional;
  const finalGoType =
    isOpt && !goType.startsWith("*") && !goType.startsWith("[]") ? `*${goType}` : goType;

  const validateTag = buildValidateTag(program, prop);
  const jsonOmit = isOpt ? ",omitempty" : "";
  const structTag = validateTag
    ? `gorm:"${gormTag}" validate:"${validateTag}" json:"${prop.name}${jsonOmit}"`
    : `gorm:"${gormTag}" json:"${prop.name}${jsonOmit}"`;

  const docComment = doc ? `\t// ${doc}\n` : "";
  return `${docComment}\t${fieldName} ${finalGoType} \`${structTag}\`\n`;
}

// ─── Go type resolution ─────────────────────────────────────────────────────

function resolveGoType(
  program: Program,
  prop: ModelProperty,
  columnName: string,
  compositeMap: Map<string, CompositeFieldTag[]>,
): GoTypeResult {
  // Enum types get their own resolution path
  const enumInfo = getPropertyEnum(prop);
  if (enumInfo) {
    return resolveEnumGoType(program, prop, columnName, enumInfo, compositeMap);
  }

  const dbType = resolveDbType(prop.type);
  const mapping = dbType ? GO_TYPE_MAP[dbType] : undefined;

  if (!mapping) {
    reportDiagnostic(program, {
      code: "unsupported-type",
      format: { typeName: dbType ?? prop.type.kind, propName: prop.name },
      target: prop,
    });
  }

  const goType = mapping?.goType ?? "interface{}";
  const requiredImports = mapping?.imports ? [...mapping.imports] : [];

  // Build GORM tag parts
  const tagParts: string[] = [];
  tagParts.push(`column:${columnName}`);

  // Type
  let gormTypeName = mapping?.gormType ?? "";

  // Apply maxLength for string types
  const maxLen = getMaxLength(program, prop);
  if (maxLen !== undefined && (dbType === "string" || gormTypeName === "varchar(255)")) {
    gormTypeName = `varchar(${maxLen})`;
  }

  // Apply precision for decimal types
  const prec = getPrecision(program, prop);
  if (prec && (dbType === "decimal" || dbType === "float64")) {
    gormTypeName = `numeric(${prec.precision},${prec.scale})`;
  }

  if (gormTypeName) {
    tagParts.push(`type:${gormTypeName}`);
  }

  // Primary key
  if (isId(program, prop)) {
    tagParts.push("primaryKey");

    if (dbType === "uuid") {
      const customDefault = getDefaultValue(program, prop);
      tagParts.push(`default:${customDefault ?? "gen_random_uuid()"}`);
    }
  }

  // Auto increment
  if (isAutoIncrement(program, prop) || dbType === "serial" || dbType === "bigserial") {
    tagParts.push("autoIncrement");
  }

  // AutoCreateTime / AutoUpdateTime
  if (isAutoCreateTime(program, prop)) {
    tagParts.push("autoCreateTime");
  }
  if (isAutoUpdateTime(program, prop)) {
    tagParts.push("autoUpdateTime");
  }

  // Not null, unique, index, composite, default (shared with enum path)
  appendCommonGormTags(program, prop, columnName, compositeMap, tagParts);

  // @doc → GORM comment tag
  const doc = getDoc(program, prop);
  if (doc) {
    tagParts.push(`comment:${doc.replace(/;/g, ",").replace(/"/g, "'")}`);
  }

  // Foreign key - index + constraint tag
  const fk = getForeignKey(program, prop);
  if (fk) {
    const compositeTags = compositeMap.get(columnName);
    // Only add index if not already present from @index or composite
    if (!isIndex(program, prop) && !compositeTags?.some((ct) => ct.kind === "index")) {
      tagParts.push("index");
    }

    const onDel = getOnDelete(program, prop);
    const onUpd = getOnUpdate(program, prop);
    const constraintParts: string[] = [];
    if (onDel) constraintParts.push(`OnDelete:${onDel}`);
    if (onUpd) constraintParts.push(`OnUpdate:${onUpd}`);
    if (constraintParts.length > 0) {
      tagParts.push(`constraint:${constraintParts.join(",")}`);
    }
  }

  const deduped = deduplicateParts(tagParts);

  return {
    goType,
    gormTag: deduped.join(";"),
    requiredImports,
    doc,
  };
}

/**
 * Resolve Go type info for an enum property.
 * Generates GORM tag with varchar type and appropriate constraints.
 */
function resolveEnumGoType(
  program: Program,
  prop: ModelProperty,
  columnName: string,
  enumInfo: { enumType: Enum; members: EnumMemberInfo[] },
  compositeMap: Map<string, CompositeFieldTag[]>,
): GoTypeResult {
  const goType = camelToPascal(enumInfo.enumType.name);
  const maxValueLen = Math.max(...enumInfo.members.map((m) => m.value.length), 20);
  const gormTypeName = `varchar(${maxValueLen})`;

  const tagParts: string[] = [];
  tagParts.push(`column:${columnName}`);
  tagParts.push(`type:${gormTypeName}`);

  appendCommonGormTags(program, prop, columnName, compositeMap, tagParts);

  const doc = getDoc(program, prop);
  if (doc) {
    tagParts.push(`comment:${doc.replace(/;/g, ",").replace(/"/g, "'")}`);
  }

  return {
    goType,
    gormTag: deduplicateParts(tagParts).join(";"),
    requiredImports: [],
    doc,
  };
}

/**
 * Append GORM tag parts shared between scalar and enum fields:
 * not null, uniqueIndex, index, composite tags, default value.
 */
function appendCommonGormTags(
  program: Program,
  prop: ModelProperty,
  columnName: string,
  compositeMap: Map<string, CompositeFieldTag[]>,
  tagParts: string[],
): void {
  if (!prop.optional && !isId(program, prop)) {
    tagParts.push("not null");
  }

  if (isUnique(program, prop)) {
    tagParts.push("uniqueIndex");
  }

  if (isIndex(program, prop)) {
    const idxName = getIndexName(program, prop);
    tagParts.push(idxName ? `index:${idxName}` : "index");
  }

  const compositeTags = compositeMap.get(columnName);
  if (compositeTags) {
    for (const ct of compositeTags) {
      tagParts.push(`${ct.kind}:${ct.name},priority:${ct.priority}`);
    }
  }

  if (!isId(program, prop)) {
    const defaultVal = getDefaultValue(program, prop);
    if (defaultVal) {
      tagParts.push(`default:${defaultVal}`);
    }
  }
}

// ─── Validator tag builder ──────────────────────────────────────────────────

/**
 * Build a go-playground/validator v10 validate tag string for a property.
 * Uses gte/lte for numeric bounds (not min/max which are for string length).
 */
function buildValidateTag(program: Program, prop: ModelProperty): string {
  const parts: string[] = [];
  const dbType = resolveDbType(prop.type);
  const isOptional = prop.optional;
  const isPk = isId(program, prop);
  const isSoft = isSoftDelete(program, prop);

  // omitempty must be first for optional fields
  if (isOptional) {
    parts.push("omitempty");
  }

  // required - non-optional, non-PK, non-soft-delete, non-bool, non-numeric,
  // non-auto-timestamp.
  // go-playground/validator 'required' rejects zero values:
  // bool zero = false (valid), int zero = 0 (valid e.g. credits=0),
  // time.Time zero = IsZero() true (GORM populates autoCreateTime/autoUpdateTime for us)
  const isBoolType = dbType === "boolean";
  const isNumericForRequired = dbType !== undefined && NUMERIC_TYPES.has(dbType);
  const isAutoTimestamp = isAutoCreateTime(program, prop) || isAutoUpdateTime(program, prop);
  if (!isOptional && !isPk && !isSoft && !isBoolType && !isNumericForRequired && !isAutoTimestamp) {
    parts.push("required");
  }

  // Enum → oneof validator (short-circuit, other validations don't apply)
  const enumInfo = getPropertyEnum(prop);
  if (enumInfo) {
    const values = enumInfo.members.map((m) => m.value).join(" ");
    parts.push(`oneof=${values}`);
    return parts.join(",");
  }

  // String validations (min/max = length for strings in go-validator)
  const isStringType = dbType === "string" || dbType === "text" || dbType === "uuid";
  if (isStringType || dbType === undefined) {
    const minLen = getMinLength(program, prop);
    const maxLen = getMaxLength(program, prop);
    if (minLen !== undefined) parts.push(`min=${minLen}`);
    if (maxLen !== undefined) parts.push(`max=${maxLen}`);
  }

  // Numeric validations (gte/lte = value bounds for numbers in go-validator)
  const isNumericType = dbType !== undefined && NUMERIC_TYPES.has(dbType);
  if (isNumericType) {
    const minVal = getMinValue(program, prop);
    const maxVal = getMaxValue(program, prop);
    if (minVal !== undefined) parts.push(`gte=${minVal}`);
    if (maxVal !== undefined) parts.push(`lte=${maxVal}`);
  }

  // Format-based validators
  const format = getFormat(program, prop);
  if (format) {
    const validator = GO_FORMAT_VALIDATORS[format];
    if (validator) {
      parts.push(validator);
    } else {
      reportDiagnostic(program, {
        code: "unknown-format",
        target: prop,
        format: { format, propName: prop.name },
      });
    }
  }

  // Pattern
  const pattern = getPattern(program, prop);
  if (pattern) {
    parts.push(`regexp=${pattern}`);
  }

  // Solo "omitempty" is a no-op - don't emit a useless validate tag
  if (parts.length === 1 && parts[0] === "omitempty") {
    return "";
  }

  return parts.join(",");
}
