# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from uuid import UUID

from pydantic import BaseModel, Field


class ReindexFileRequest(BaseModel):
    """ReindexFileRequest"""

    file_id: UUID = Field(...)
    requested_by: UUID = Field(...)
