# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from datetime import datetime

from sqlalchemy import Column, DateTime
from sqlmodel import Field, SQLModel
from ..shared.entity import Entity



class SearchIndexCheckpoint(Entity, table=True):
    """Checkpoint for async index workers."""

    __tablename__ = "search_index_checkpoints" # type: ignore

    shard_key: str = Field(unique=True, max_length=255, sa_column_kwargs={"nullable": False})
    last_processed_event_id: str | None = Field(default=None, max_length=255)
    last_processed_at: datetime | None = Field(default=None, sa_column=Column(DateTime(timezone=True)))
