# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from uuid import UUID

from pydantic import BaseModel, Field


class SearchHit(BaseModel):
    """SearchHit"""

    file_id: UUID = Field(...)
    snippet: str | None = Field(None)
    score: float = Field(...)
