# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from pydantic import BaseModel, Field


class SuggestLabelsResponse(BaseModel):
    """SuggestLabelsResponse"""

    labels: list[str] = Field(...)
