# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from uuid import UUID

from pydantic import BaseModel, Field


class SuggestLabelsRequest(BaseModel):
    """SuggestLabelsRequest"""

    owner_id: UUID = Field(...)
    prefix: str = Field(...)
    limit: int = Field(...)
