# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from uuid import UUID

from pydantic import AnyUrl, BaseModel, EmailStr, Field


class UserProfile(BaseModel):
    """Lightweight user profile view for public surfaces. Demonstrates a `@data` model in a nested namespace."""

    # Unique identifier shared by most persisted records.
    id: UUID = Field(
        ..., description="Unique identifier shared by most persisted records."
    )
    # Email address used for login and invitations. Other namespaces reference this via lookup types.
    email: EmailStr = Field(
        ...,
        max_length=320,
        description="Email address used for login and invitations. Other namespaces reference this via lookup types.",
    )
    # Display name shown throughout the UI.
    display_name: str = Field(
        ..., max_length=100, description="Display name shown throughout the UI."
    )
    # Public avatar URL rendered in lists and profile cards.
    avatar_url: AnyUrl | None = Field(
        None,
        max_length=512,
        description="Public avatar URL rendered in lists and profile cards.",
    )
