// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package shared

import (
	"github.com/google/uuid"
)

// ActorRef ActorRef
type ActorRef struct {
	ID uuid.UUID `validate:"required" json:"id"`
	DisplayName string `validate:"required,max=255,min=1" json:"displayName"`
	Email *string `validate:"omitempty,email" json:"email,omitempty"`
}
