output-dir: "{cwd}/outputs/file-vault"
emit:
  - "@qninhdt/typespec-ent"
  - "@qninhdt/typespec-sqlmodel"
  - "@qninhdt/typespec-dbml"
  - "@qninhdt/typespec-zod"
  - "@qninhdt/typespec-protobuf"
options:
  "@qninhdt/typespec-zod":
    output-dir: "{cwd}/outputs/file-vault/zod"
    standalone: true
    library-name: "file-vault-example"
  "@qninhdt/typespec-ent":
    output-dir: "{cwd}/outputs/file-vault/ent"
    standalone: true
    library-name: "github.com/example/file-vault"
    collection-strategy: "jsonb"
  "@qninhdt/typespec-sqlmodel":
    output-dir: "{cwd}/outputs/file-vault/sqlmodel"
    standalone: true
    library-name: "file-vault-example"
    collection-strategy: "jsonb"
  "@qninhdt/typespec-dbml":
    output-dir: "{cwd}/outputs/file-vault/dbml"
    split-by-namespace: false
  "@qninhdt/typespec-protobuf":
    output-dir: "{cwd}/outputs/file-vault/protobuf"
