# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from typing import TYPE_CHECKING
from uuid import UUID, uuid4
from datetime import datetime

from sqlalchemy import Column, DateTime, func
from sqlmodel import Field, Relationship, SQLModel

from demo.__associations__ import user_badges

if TYPE_CHECKING:
    from .user import User


class Badge(SQLModel, table=True):
    """Account badge or achievement marker attached to player profiles."""

    __tablename__ = "badges"  # type: ignore

    # Unique identifier shared by most persisted records.
    id: UUID = Field(
        default_factory=uuid4,
        primary_key=True,
        sa_column_kwargs={
            "comment": "Unique identifier shared by most persisted records."
        },
    )
    # Timestamp when the record was created.
    created_at: datetime = Field(
        sa_column=Column(
            DateTime(timezone=True),
            nullable=False,
            server_default=func.now(),
            comment="Timestamp when the record was created.",
        )
    )
    # Timestamp of the last update.
    updated_at: datetime | None = Field(
        default=None,
        sa_column=Column(
            DateTime(timezone=True), comment="Timestamp of the last update."
        ),
    )
    # Soft delete marker for archival workflows.
    deleted_at: datetime | None = Field(
        default=None,
        sa_column=Column(
            DateTime(timezone=True),
            comment="Soft delete marker for archival workflows.",
            index=True,
        ),
    )
    # Stable badge code used by tooling and migration scripts.
    code: str = Field(
        unique=True,
        max_length=80,
        sa_column_kwargs={
            "nullable": False,
            "comment": "Stable badge code used by tooling and migration scripts.",
        },
    )
    # Human-readable badge name rendered in the UI.
    label: str = Field(
        max_length=160,
        sa_column_kwargs={
            "nullable": False,
            "comment": "Human-readable badge name rendered in the UI.",
        },
    )

    # ─── Relationships ─────────────────────
    # Users who have earned this badge.
    users: list[User] = Relationship(
        back_populates="badges", sa_relationship_kwargs={"secondary": user_badges}
    )
