# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from typing import ClassVar, TYPE_CHECKING
from uuid import UUID, uuid4
from datetime import datetime
from pydantic import AnyUrl, EmailStr
from enum import Enum

from sqlalchemy import Column, DateTime, Enum as SAEnum, UniqueConstraint, func
from sqlmodel import Field, Relationship, SQLModel

if TYPE_CHECKING:
    from .subscription import Subscription


class UserRole(str, Enum):
    """Auto-generated enum for user_role."""

    player = "player"
    moderator = "moderator"
    admin = "admin"


class User(SQLModel, table=True):
    """Registered player account."""

    __tablename__ = "users"  # type: ignore
    __table_args__ = (
        UniqueConstraint("email", "deleted_at", name="users_email_deleted_at_unique"),
    )

    # Example of a computed UI field excluded from persistence.
    full_title: ClassVar[str | None]  # @ignore - not persisted
    # Unique identifier shared by most persisted records.
    id: UUID = Field(
        default_factory=uuid4,
        primary_key=True,
        sa_column_kwargs={
            "comment": "Unique identifier shared by most persisted records."
        },
    )
    # Timestamp when the record was created.
    created_at: datetime = Field(
        sa_column=Column(
            DateTime(timezone=True),
            nullable=False,
            server_default=func.now(),
            comment="Timestamp when the record was created.",
        )
    )
    # Timestamp of the last update.
    updated_at: datetime | None = Field(
        default=None,
        sa_column=Column(
            DateTime(timezone=True), comment="Timestamp of the last update."
        ),
    )
    # Soft delete marker for archival workflows.
    deleted_at: datetime | None = Field(
        default=None,
        sa_column=Column(
            DateTime(timezone=True),
            comment="Soft delete marker for archival workflows.",
            index=True,
        ),
    )
    # Email address used for login and invitations. Other namespaces reference this via lookup types.
    email: EmailStr = Field(
        max_length=320,
        sa_column_kwargs={
            "nullable": False,
            "comment": "Email address used for login and invitations. Other namespaces reference this via lookup types.",
        },
    )
    # Hashed password - never expose or store plain text credentials.
    password_hash: str = Field(
        max_length=255,
        sa_column_kwargs={
            "nullable": False,
            "comment": "Hashed password - never expose or store plain text credentials.",
        },
    )
    # Display name shown throughout the UI.
    display_name: str = Field(
        max_length=100,
        sa_column_kwargs={
            "nullable": False,
            "comment": "Display name shown throughout the UI.",
        },
    )
    # Public avatar URL rendered in lists and profile cards.
    avatar_url: AnyUrl | None = Field(
        default=None,
        max_length=512,
        sa_column_kwargs={
            "comment": "Public avatar URL rendered in lists and profile cards."
        },
    )
    # Optional locale preference for formatting and localization.
    preferred_locale: str | None = Field(
        default=None,
        max_length=16,
        sa_column_kwargs={
            "comment": "Optional locale preference for formatting and localization."
        },
    )
    # Entitlement credits or consumable balance.
    credits: int = Field(
        sa_column_kwargs={
            "nullable": False,
            "server_default": "0",
            "comment": "Entitlement credits or consumable balance.",
        }
    )
    # Role used by moderation features and internal tooling.
    role: UserRole = Field(
        sa_column=Column(
            SAEnum(UserRole),
            nullable=False,
            index=True,
            server_default="player",
            comment="Role used by moderation features and internal tooling.",
        )
    )
    # Whether the account is currently active.
    is_active: bool = Field(
        sa_column_kwargs={
            "nullable": False,
            "server_default": "true",
            "comment": "Whether the account is currently active.",
        }
    )

    # ─── Relationships ─────────────────────
    # Billing subscriptions tied to the account.
    subscriptions: list[Subscription] = Relationship(
        back_populates="user", sa_relationship_kwargs={"cascade": "all, delete-orphan"}
    )
