// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
	"github.com/google/uuid"

	entschema "entgo.io/ent/schema"
)


// VaultNode Folder/file node in a vault tree. File-specific metadata lives separately.
type VaultNode struct {
	ent.Schema
}

func (VaultNode) Annotations() []entschema.Annotation {
	return []entschema.Annotation{
		entsql.Annotation{Table: "vault_nodes"},
		entsql.WithComments(true),
	}
}

func (VaultNode) Mixin() []ent.Mixin {
	return []ent.Mixin{
		SoftDeletableEntity{},
	}
}

func (VaultNode) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("vault_id", uuid.UUID{}),
		field.UUID("parent_id", uuid.UUID{}).
			Optional().
			Nillable(),
		field.Enum("kind").Values("folder", "file"),
		field.String("name").
			MaxLen(240),
		field.String("normalized_name").
			MaxLen(240),
		field.Text("path"),
		field.Int32("depth"),
		field.Enum("state").Values("active", "trashed", "deleted").
			Default("active"),
		field.Enum("visibility").Values("private", "shared", "public_link").
			Default("private"),
		field.Time("trashed_at").
			Optional().
			Nillable(),
		field.UUID("created_by", uuid.UUID{}),
		field.UUID("updated_by", uuid.UUID{}).
			Optional().
			Nillable(),
	}
}

func (VaultNode) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("vault", VaultSpace.Type).
			Field("vault_id").
			Unique().
			Required().
			Annotations(entsql.OnDelete(entsql.Cascade)),
		edge.To("creator", UserAccount.Type).
			Field("created_by").
			Unique().
			Required(),
	}
}

func (VaultNode) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("vault_id"),
		index.Fields("parent_id"),
		index.Fields("state"),
		index.Fields("created_by"),
		index.Fields("vault_id", "parent_id", "normalized_name").
			Unique(),
	}
}
