# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from typing import Any, TYPE_CHECKING
from uuid import UUID

from sqlalchemy import Column, ForeignKey, Index
from sqlalchemy.dialects.postgresql import JSONB, UUID as PG_UUID
from sqlmodel import Field, Relationship, SQLModel
from ...shared.world_owned import WorldOwned


if TYPE_CHECKING:
    from .story_node import StoryNode
    from ...worlds.world import World


class StoryNode(WorldOwned, table=True):
    """Node in a lazily-generated story tree. Stores the cumulative content-pool IDs inherited from all ancestor nodes."""

    __tablename__ = "story_nodes"  # type: ignore
    __table_args__ = (Index("story_nodes_world_id_depth_idx", "world_id", "depth"),)

    # Depth of this node in the story tree - root is 0.
    depth: int = Field(
        index=True,
        sa_column_kwargs={
            "nullable": False,
            "server_default": "0",
            "comment": "Depth of this node in the story tree - root is 0.",
        },
    )
    # Content pool inherited from all ancestors.
    pool: Any = Field(
        sa_column=Column(
            JSONB, nullable=False, comment="Content pool inherited from all ancestors."
        )
    )
    # Content introduced by this specific node.
    new_content: Any = Field(
        sa_column=Column(
            JSONB, nullable=False, comment="Content introduced by this specific node."
        )
    )
    # IDs of lazily-expanded child nodes.
    child_ids: Any = Field(
        sa_column=Column(
            JSONB, nullable=False, comment="IDs of lazily-expanded child nodes."
        )
    )
    # Searchable labels attached to the node for branch discovery.
    tags: list[str] = Field(
        sa_column=Column(
            JSONB,
            nullable=False,
            comment="Searchable labels attached to the node for branch discovery.",
        )
    )
    parent_id: UUID | None = Field(
        default=None,
        sa_column=Column(
            PG_UUID(as_uuid=True),
            ForeignKey("story_nodes.id", ondelete="CASCADE"),
            index=True,
        ),
    )

    # ─── Relationships ─────────────────────
    # Owning world.
    world: World | None = Relationship()
    # Parent story node.
    parent: StoryNode | None = Relationship(
        back_populates="children",
        sa_relationship_kwargs={"remote_side": "StoryNode.id"},
    )
    # Child nodes reachable from this node.
    children: list[StoryNode] = Relationship(back_populates="parent")
