// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package shared

// StringPair StringPair
type StringPair struct {
	Key string `validate:"required" json:"key"`
	Value string `validate:"required" json:"value"`
}
