// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package search

import (
	"github.com/google/uuid"
)

// ReindexFileRequest ReindexFileRequest
type ReindexFileRequest struct {
	FileID      uuid.UUID `validate:"required" json:"fileId"`
	RequestedBy uuid.UUID `validate:"required" json:"requestedBy"`
}
