// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package search

import (
	file_vault_shared "github.com/example/file-vault/file_vault/shared"
)

// SearchFilesResponse SearchFilesResponse
type SearchFilesResponse struct {
	Hits []SearchHit                `json:"hits"`
	Page file_vault_shared.PageInfo `json:"page"`
}
