// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package search

import (
	file_vault_metadata "github.com/example/file-vault/file_vault/metadata"
)

// SearchHit SearchHit
type SearchHit struct {
	File    file_vault_metadata.FileView `json:"file"`
	Snippet *string                      `validate:"omitempty" json:"snippet,omitempty"`
	Score   float32                      `validate:"required" json:"score"`
}
