// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package search

import (
	"github.com/google/uuid"
)

// SuggestLabelsRequest SuggestLabelsRequest
type SuggestLabelsRequest struct {
	OwnerID uuid.UUID `validate:"required" json:"ownerId"`
	Prefix  string    `validate:"required" json:"prefix"`
	Limit   int32     `validate:"required" json:"limit"`
}
