// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

// Package ent hosts the generated Ent schema package.
//
// Typical workflow after regenerating from TypeSpec:
//
//   1. go generate ./ent          # regenerate Ent client from ./schema
//   2. atlas migrate diff --env ent
//   3. atlas migrate apply --env ent
//
// The atlas.hcl at the module root defines the "ent" environment used above;
// run `atlas migrate diff --help` for additional flags (e.g. --to / --baseline).

package ent

//go:generate go run -mod=mod entgo.io/ent/cmd/ent generate ./schema
