import { z } from "zod";
import { ProcessingJobViewSchema } from "./ProcessingJobView.js";
import { PageInfoSchema } from "../shared/PageInfo.js";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const ListProcessingJobsResponseSchema = z.object({
  jobs: z.array(ProcessingJobViewSchema),
  page: PageInfoSchema,
})
export type ListProcessingJobsResponse = z.infer<typeof ListProcessingJobsResponseSchema>;
