import { z } from "zod";
import { PageRequestSchema } from "../shared/PageRequest.js";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const ListProcessingJobsRequestSchema = z.object({
  fileId: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  page: PageRequestSchema,
})
export type ListProcessingJobsRequest = z.infer<typeof ListProcessingJobsRequestSchema>;
