import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const ProcessingJobViewSchema = z.object({
  id: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  fileId: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  versionId: z
    .string()
    .uuid()
    .optional()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  kind: z.union([
    z.literal(0),
    z.literal(1),
    z.literal(2),
    z.literal(3),
    z.literal(4),
    z.literal(5)
  ]),
  status: z.union([
    z.literal(0),
    z.literal(1),
    z.literal(2),
    z.literal(3),
    z.literal(4),
    z.literal(5)
  ]),
  startedAtIso: z.string().optional(),
  finishedAtIso: z.string().optional(),
  errorMessage: z.string().optional(),
})
export type ProcessingJobView = z.infer<typeof ProcessingJobViewSchema>;
