import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const ProcessingArtifactViewSchema = z.object({
  id: z.uuid(),
  jobId: z.uuid(),
  fileId: z.uuid(),
  kind: z.union([
    z.literal(0),
    z.literal(1),
    z.literal(2),
    z.literal(3),
    z.literal(4)
  ]),
  storageObjectId: z.uuid().optional(),
  textValue: z.string().optional(),
})
export type ProcessingArtifactView = z.infer<typeof ProcessingArtifactViewSchema>;
