import { z } from "zod";
import { StringPairSchema } from "../shared/StringPair.js";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const SubmitProcessingJobRequestSchema = z.object({
  fileId: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  versionId: z
    .string()
    .uuid()
    .optional()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  kind: z.union([
    z.literal(0),
    z.literal(1),
    z.literal(2),
    z.literal(3),
    z.literal(4),
    z.literal(5)
  ]),
  requestedBy: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  parameters: z.array(StringPairSchema),
})
export type SubmitProcessingJobRequest = z.infer<typeof SubmitProcessingJobRequestSchema>;
