import { z } from "zod";
import { StringPairSchema } from "../shared/StringPair.js";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const SubmitProcessingJobRequestSchema = z.object({
  fileId: z.uuid(),
  versionId: z.uuid().optional(),
  kind: z.union([
    z.literal(0),
    z.literal(1),
    z.literal(2),
    z.literal(3),
    z.literal(4),
    z.literal(5)
  ]),
  requestedBy: z.uuid(),
  parameters: z.array(StringPairSchema),
})
export type SubmitProcessingJobRequest = z.infer<typeof SubmitProcessingJobRequestSchema>;
