import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const CreateWorldFormSchema = z
  .object({
    name: z.string().max(200),
    prompt: z.string(),
    ownerEmail: z.string().max(320).email(),
    starterTag: z.string().max(100),
    featuredNpc: z.string().max(200),
    summary: z
      .string()
      .optional()
      .describe("Unlimited text - maps to TEXT column (vs VARCHAR for string)"),
  })

    .describe("Form payload for creating or editing a world. Demonstrates cross-namespace lookup types pulled from multiple bounded contexts.")
export type CreateWorldForm = z.infer<typeof CreateWorldFormSchema>;

export const CreateWorldFormMeta = {
  name: { title: "World Name", placeholder: "Chronicles of Emberfall" },
  prompt: { title: "World Prompt", inputType: "textarea" },
  ownerEmail: { title: "Owner Email", inputType: "email" },
  starterTag: { title: "Starter Tag" },
  featuredNpc: { title: "Featured NPC" },
  summary: { title: "Summary", placeholder: "Describe the setting, themes, and tone.", inputType: "textarea" },
} as const;
