# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from typing import TYPE_CHECKING
from uuid import UUID
from datetime import datetime

from sqlalchemy import Column, DateTime, ForeignKey, Text
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlmodel import Field, Relationship, SQLModel
from ..shared.entity import Entity


if TYPE_CHECKING:
    from ..metadata.file_metadata import FileMetadata


class FileSummaryRecord(Entity, table=True):
    """Latest summary surfaced in file details and search snippets."""

    __tablename__ = "file_summaries" # type: ignore

    file_id: UUID = Field(sa_column=Column(PG_UUID(as_uuid=True), ForeignKey("file_metadata.id", ondelete="CASCADE"), nullable=False, index=True, unique=True))
    summary: str = Field(sa_column=Column(Text, nullable=False))
    model_name: str = Field(max_length=255, sa_column_kwargs={"nullable": False})
    generated_at: datetime = Field(sa_column=Column(DateTime(timezone=True), nullable=False))

    # ─── Relationships ─────────────────────
    file: FileMetadata | None = Relationship()
