# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from pydantic import BaseModel, Field
from .processing_artifact_view import ProcessingArtifactView
from .processing_job_view import ProcessingJobView



class ProcessingEvent(BaseModel):
    """ProcessingEvent"""

    job: ProcessingJobView = Field(...)
    artifacts: list[ProcessingArtifactView] = Field(...)
