# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from typing import Any, TYPE_CHECKING
from uuid import UUID
from enum import Enum

from sqlalchemy import Column, Enum as SAEnum, ForeignKey, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID as PG_UUID
from sqlmodel import Field, Relationship, SQLModel
from ..shared.entity import Entity


if TYPE_CHECKING:
    from ..metadata.file_metadata import FileMetadata
    from .processing_job import ProcessingJob


class ArtifactKind(str, Enum):
    """Auto-generated enum for artifact_kind."""

    extracted_text = "extracted_text"
    summary = "summary"
    preview_image = "preview_image"
    thumbnail = "thumbnail"
    classification = "classification"


class ProcessingArtifact(Entity, table=True):
    """Artifact produced by a processing job."""

    __tablename__ = "processing_artifacts" # type: ignore

    job_id: UUID = Field(sa_column=Column(PG_UUID(as_uuid=True), ForeignKey("processing_jobs.id", ondelete="CASCADE"), nullable=False, index=True))
    file_id: UUID = Field(sa_column=Column(PG_UUID(as_uuid=True), ForeignKey("file_metadata.id", ondelete="CASCADE"), nullable=False, index=True))
    kind: ArtifactKind = Field(sa_column=Column(SAEnum(ArtifactKind), nullable=False))
    storage_object_id: UUID | None = Field(default=None, sa_column=Column(PG_UUID(as_uuid=True)))
    text_value: str | None = Field(default=None, sa_column=Column(Text))
    metadata_json: Any | None = Field(default=None, sa_column=Column(JSONB))

    # ─── Relationships ─────────────────────
    job: ProcessingJob | None = Relationship()
    file: FileMetadata | None = Relationship()
