# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from uuid import UUID
from enum import Enum

from pydantic import BaseModel, Field


class ArtifactKindCode(int, Enum):
    """Auto-generated enum for artifact_kind_code."""

    artifact_kind_unspecified = 0
    text_extraction = 1
    summary = 2
    preview_image = 3
    embedding = 4


class ProcessingArtifactView(BaseModel):
    """ProcessingArtifactView"""

    id: UUID = Field(...)
    job_id: UUID = Field(...)
    file_id: UUID = Field(...)
    kind: ArtifactKindCode = Field(...)
    storage_object_id: UUID | None = Field(None)
    text_value: str | None = Field(None)
