// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package accounts

// UserProfile Lightweight user profile view for public surfaces. Demonstrates a default form model in a nested namespace.
type UserProfile struct {
}
