// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package identity

// RefreshSessionRequest RefreshSessionRequest
type RefreshSessionRequest struct {
	RefreshToken string `validate:"required" json:"refreshToken"`
}
