// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package identity

import (
	"github.com/google/uuid"
)

// SessionView SessionView
type SessionView struct {
	ID uuid.UUID `validate:"required" json:"id"`
	AccountID uuid.UUID `validate:"required" json:"accountId"`
	DeviceLabel *string `validate:"omitempty" json:"deviceLabel,omitempty"`
	ExpiresAtIso string `validate:"required" json:"expiresAtIso"`
	RevokedAtIso *string `validate:"omitempty" json:"revokedAtIso,omitempty"`
}
