// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package identity

// SignInResponse SignInResponse
type SignInResponse struct {
	Account AccountView `json:"account"`
	Session SessionView `json:"session"`
	AccessToken string `validate:"required" json:"accessToken"`
	RefreshToken string `validate:"required" json:"refreshToken"`
}
