// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package identity

// TokenPair TokenPair
type TokenPair struct {
	AccessToken string `validate:"required" json:"accessToken"`
	RefreshToken string `validate:"required" json:"refreshToken"`
}
