// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package processing

import (
	"github.com/google/uuid"
)

// GetProcessingJobRequest GetProcessingJobRequest
type GetProcessingJobRequest struct {
	JobID uuid.UUID `validate:"required" json:"jobId"`
}
