// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package processing

import (
	file_vault_shared "github.com/example/file-vault/file_vault/shared"
)

// ListProcessingJobsResponse ListProcessingJobsResponse
type ListProcessingJobsResponse struct {
	Jobs []ProcessingJobView        `json:"jobs"`
	Page file_vault_shared.PageInfo `json:"page"`
}
