// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package processing

import (
	"github.com/google/uuid"

	file_vault_shared "github.com/example/file-vault/file_vault/shared"
)

// ListProcessingJobsRequest ListProcessingJobsRequest
type ListProcessingJobsRequest struct {
	FileID uuid.UUID                     `validate:"required" json:"fileId"`
	Page   file_vault_shared.PageRequest `json:"page"`
}
