// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package processing

import (
	"github.com/google/uuid"
)

// ProcessingArtifactView ProcessingArtifactView
type ProcessingArtifactView struct {
	ID              uuid.UUID        `validate:"required" json:"id"`
	JobID           uuid.UUID        `validate:"required" json:"jobId"`
	FileID          uuid.UUID        `validate:"required" json:"fileId"`
	Kind            ArtifactKindCode `validate:"oneof=0 1 2 3 4" json:"kind"`
	StorageObjectID *uuid.UUID       `validate:"omitempty" json:"storageObjectId,omitempty"`
	TextValue       *string          `validate:"omitempty" json:"textValue,omitempty"`
}
