// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package processing

import (
	"github.com/google/uuid"
)

// ProcessingJobView ProcessingJobView
type ProcessingJobView struct {
	ID            uuid.UUID            `validate:"required" json:"id"`
	FileID        uuid.UUID            `validate:"required" json:"fileId"`
	VersionID     *uuid.UUID           `validate:"omitempty" json:"versionId,omitempty"`
	Kind          ProcessingKindCode   `validate:"oneof=0 1 2 3 4 5" json:"kind"`
	Status        ProcessingStatusCode `validate:"oneof=0 1 2 3 4 5" json:"status"`
	StartedAtIso  *string              `validate:"omitempty" json:"startedAtIso,omitempty"`
	FinishedAtIso *string              `validate:"omitempty" json:"finishedAtIso,omitempty"`
	ErrorMessage  *string              `validate:"omitempty" json:"errorMessage,omitempty"`
}
