// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package processing

// ProcessingEvent ProcessingEvent
type ProcessingEvent struct {
	Job       ProcessingJobView        `json:"job"`
	Artifacts []ProcessingArtifactView `json:"artifacts"`
}
