// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package sharing

import (
	"github.com/google/uuid"

	file_vault_shared "github.com/example/file-vault/file_vault/shared"
)

// ListSharesRequest ListSharesRequest
type ListSharesRequest struct {
	ResourceNodeID uuid.UUID                     `validate:"required" json:"resourceNodeId"`
	RequesterID    uuid.UUID                     `validate:"required" json:"requesterId"`
	Page           file_vault_shared.PageRequest `json:"page"`
}
