# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
from typing import Annotated

from pydantic import Field


PageSize = Annotated[int, Field(ge=1, le=100)]
SearchQuery = Annotated[str, Field(max_length=512, min_length=1)]
