import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const CreateShareGrantRequestSchema = z.object({
  resourceNodeId: z.uuid(),
  grantedBy: z.uuid(),
  subjectKind: z.union([
    z.literal(0),
    z.literal(1),
    z.literal(2),
    z.literal(3)
  ]),
  subject: z.string(),
  role: z.union([
    z.literal(0),
    z.literal(1),
    z.literal(2),
    z.literal(3),
    z.literal(4)
  ]),
  expiresAtIso: z.string().optional(),
})
export type CreateShareGrantRequest = z.infer<typeof CreateShareGrantRequestSchema>;
