import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const CreateShareLinkRequestSchema = z.object({
  resourceNodeId: z.uuid(),
  createdBy: z.uuid(),
  role: z.union([
    z.literal(0),
    z.literal(1),
    z.literal(2),
    z.literal(3),
    z.literal(4)
  ]),
  expiresAtIso: z.string().optional(),
  password: z.string().optional(),
})
export type CreateShareLinkRequest = z.infer<typeof CreateShareLinkRequestSchema>;
