import { z } from "zod";
import { PageInfoSchema } from "../shared/PageInfo.js";
import { ShareGrantViewSchema } from "./ShareGrantView.js";
import { ShareLinkViewSchema } from "./ShareLinkView.js";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const ListSharesResponseSchema = z.object({
  grants: z.array(ShareGrantViewSchema),
  links: z.array(ShareLinkViewSchema),
  page: PageInfoSchema,
})
export type ListSharesResponse = z.infer<typeof ListSharesResponseSchema>;
