import { z } from "zod";
import { PageRequestSchema } from "../shared/PageRequest.js";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const ListSharesRequestSchema = z.object({
  resourceNodeId: z.uuid(),
  requesterId: z.uuid(),
  page: PageRequestSchema,
})
export type ListSharesRequest = z.infer<typeof ListSharesRequestSchema>;
