import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const RevokeShareGrantRequestSchema = z.object({
  grantId: z.uuid(),
  revokedBy: z.uuid(),
})
export type RevokeShareGrantRequest = z.infer<typeof RevokeShareGrantRequestSchema>;
