import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const RevokeShareGrantRequestSchema = z.object({
  grantId: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  revokedBy: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
})
export type RevokeShareGrantRequest = z.infer<typeof RevokeShareGrantRequestSchema>;
