import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const ShareLinkViewSchema = z.object({
  id: z.uuid(),
  resourceNodeId: z.uuid(),
  url: z.string(),
  role: z.union([
    z.literal(0),
    z.literal(1),
    z.literal(2),
    z.literal(3),
    z.literal(4)
  ]),
  expiresAtIso: z.string().optional(),
})
export type ShareLinkView = z.infer<typeof ShareLinkViewSchema>;
