// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package assistant

import (
	"encoding/json"

	"github.com/google/uuid"
)

// ApprovalRequestView ApprovalRequestView
type ApprovalRequestView struct {
	ID           uuid.UUID            `validate:"required" json:"id"`
	TaskID       uuid.UUID            `validate:"required" json:"taskId"`
	Action       string               `validate:"required" json:"action"`
	ResourceType string               `validate:"required" json:"resourceType"`
	ResourceID   uuid.UUID            `validate:"required" json:"resourceId"`
	ProposalJSON json.RawMessage      `validate:"required" json:"proposalJson"`
	Decision     ApprovalDecisionCode `validate:"oneof=0 1 2 3" json:"decision"`
}
