// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package assistant

// AssistantReply AssistantReply
type AssistantReply struct {
	Conversation ConversationView `json:"conversation"`
	Messages     []MessageView    `json:"messages"`
}
