// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package assistant

import (
	"github.com/google/uuid"
)

// AssistantTaskView AssistantTaskView
type AssistantTaskView struct {
	ID             uuid.UUID               `validate:"required" json:"id"`
	ConversationID uuid.UUID               `validate:"required" json:"conversationId"`
	TaskType       string                  `validate:"required" json:"taskType"`
	Objective      string                  `validate:"required" json:"objective"`
	Status         AssistantTaskStatusCode `validate:"oneof=0 1 2 3 4 5 6" json:"status"`
	TargetNodeID   *uuid.UUID              `validate:"omitempty" json:"targetNodeId,omitempty"`
	ResultSummary  *string                 `validate:"omitempty" json:"resultSummary,omitempty"`
}
