// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package assistant

import (
	"github.com/google/uuid"
)

// AssistantEvent AssistantEvent
type AssistantEvent struct {
	ConversationID uuid.UUID            `validate:"required" json:"conversationId"`
	Task           *AssistantTaskView   `validate:"omitempty" json:"task,omitempty"`
	Message        *MessageView         `validate:"omitempty" json:"message,omitempty"`
	Approval       *ApprovalRequestView `validate:"omitempty" json:"approval,omitempty"`
}
