// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package assistant

import (
	"github.com/google/uuid"
)

// ConversationView ConversationView
type ConversationView struct {
	ID               uuid.UUID             `validate:"required" json:"id"`
	OwnerID          uuid.UUID             `validate:"required" json:"ownerId"`
	Title            string                `validate:"required" json:"title"`
	State            ConversationStateCode `validate:"oneof=0 1 2" json:"state"`
	LastMessageAtIso *string               `validate:"omitempty" json:"lastMessageAtIso,omitempty"`
}
