// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package assistant

// ApprovalDecisionCode represents the approval_decision_code enum.
type ApprovalDecisionCode int32

const (
	ApprovalDecisionCodeUnspecified ApprovalDecisionCode = 0
	ApprovalDecisionCodePending     ApprovalDecisionCode = 1
	ApprovalDecisionCodeApproved    ApprovalDecisionCode = 2
	ApprovalDecisionCodeRejected    ApprovalDecisionCode = 3
)

// AssistantTaskStatusCode represents the assistant_task_status_code enum.
type AssistantTaskStatusCode int32

const (
	AssistantTaskStatusCodeUnspecified        AssistantTaskStatusCode = 0
	AssistantTaskStatusCodeQueued             AssistantTaskStatusCode = 1
	AssistantTaskStatusCodeRunning            AssistantTaskStatusCode = 2
	AssistantTaskStatusCodeWaitingForApproval AssistantTaskStatusCode = 3
	AssistantTaskStatusCodeCompleted          AssistantTaskStatusCode = 4
	AssistantTaskStatusCodeFailed             AssistantTaskStatusCode = 5
	AssistantTaskStatusCodeCanceled           AssistantTaskStatusCode = 6
)

// ConversationStateCode represents the conversation_state_code enum.
type ConversationStateCode int32

const (
	ConversationStateCodeUnspecified ConversationStateCode = 0
	ConversationStateCodeActive      ConversationStateCode = 1
	ConversationStateCodeArchived    ConversationStateCode = 2
)

// MessageRoleCode represents the message_role_code enum.
type MessageRoleCode int32

const (
	MessageRoleCodeUnspecified MessageRoleCode = 0
	MessageRoleCodeUser        MessageRoleCode = 1
	MessageRoleCodeAssistant   MessageRoleCode = 2
	MessageRoleCodeSystem      MessageRoleCode = 3
)
