// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package assistant

import (
	"github.com/google/uuid"
)

// StartConversationRequest StartConversationRequest
type StartConversationRequest struct {
	OwnerID        uuid.UUID `validate:"required" json:"ownerId"`
	Title          *string   `validate:"omitempty" json:"title,omitempty"`
	InitialMessage *string   `validate:"omitempty" json:"initialMessage,omitempty"`
}
