// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package assistant

import (
	"github.com/google/uuid"
)

// StartAssistantTaskRequest StartAssistantTaskRequest
type StartAssistantTaskRequest struct {
	ConversationID uuid.UUID  `validate:"required" json:"conversationId"`
	RequestedBy    uuid.UUID  `validate:"required" json:"requestedBy"`
	TaskType       string     `validate:"required" json:"taskType"`
	Objective      string     `validate:"required" json:"objective"`
	TargetNodeID   *uuid.UUID `validate:"omitempty" json:"targetNodeId,omitempty"`
}
