// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package assistant

import (
	"github.com/google/uuid"
)

// SubmitApprovalDecisionRequest SubmitApprovalDecisionRequest
type SubmitApprovalDecisionRequest struct {
	ApprovalID uuid.UUID            `validate:"required" json:"approvalId"`
	DecidedBy  uuid.UUID            `validate:"required" json:"decidedBy"`
	Decision   ApprovalDecisionCode `validate:"oneof=0 1 2 3" json:"decision"`
}
