// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package assistant

import (
	"time"
)

// WatchConversationEvent WatchConversationEvent
type WatchConversationEvent struct {
	OccurredAt time.Time      `validate:"required" json:"occurredAt"`
	Event      AssistantEvent `json:"event"`
}
