// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package assistant

import (
	"github.com/google/uuid"
)

// WatchConversationRequest WatchConversationRequest
type WatchConversationRequest struct {
	ConversationID uuid.UUID `validate:"required" json:"conversationId"`
	RequesterID    uuid.UUID `validate:"required" json:"requesterId"`
}
