// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package assistant

// WatchConversationEvent WatchConversationEvent
type WatchConversationEvent struct {
	OccurredAtIso string         `validate:"required" json:"occurredAtIso"`
	Event         AssistantEvent `json:"event"`
}
