import type { EmitContext } from "@typespec/compiler";
import { describe, expect, it } from "vitest";
import { $onEmit } from "@qninhdt/typespec-protobuf-openlet";
import type { ProtoEmitterOptions } from "@qninhdt/typespec-protobuf-openlet";
import { renderProtoComment } from "../../src/writer/proto-comment.js";
import { createEntityTestRunner } from "../utils.js";

const OUTPUT_DIR = "/output";

/**
 * Regression tests for bugs surfaced by compiling the docs/examples/*.tsp
 * files through a real `tsp compile` (the in-memory Map harness masked them).
 */

describe("regression: header escaping (escape: false)", () => {
  it("does NOT backtick-escape @-words when escape is off", () => {
    // The emitter's own file header contains '@qninhdt/...' — it must not be
    // mangled into '`@qninhdt`/...'.
    const lines = renderProtoComment(
      "Generated by @qninhdt/typespec-protobuf-openlet. DO NOT EDIT.",
      { escape: false },
    );
    expect(lines[0]).toBe("// Generated by @qninhdt/typespec-protobuf-openlet. DO NOT EDIT.");
  });

  it("still escapes @-words by default (user doc comments)", () => {
    const lines = renderProtoComment("see @deprecated");
    expect(lines[0]).toBe("// see `@deprecated`");
  });
});

describe("regression: writer skips @Qninhdt.Orm.ignore properties", () => {
  it("does not demand @field(N) on an ORM-only column of an entity", async () => {
    const runner = await createEntityTestRunner();
    await runner.compile(`
      @package("openlet.user.v1")
      namespace Pkg {
        @entity
        model UserProfile {
          @key userId: uuid;
          @Qninhdt.Orm.ignore internalRevision: int64;
        }
      }
    `);
    const program = runner.program;
    expect(program.diagnostics.filter((d) => d.severity === "error")).toHaveLength(0);

    const captured = new Map<string, string>();
    const originalWrite = program.host.writeFile;
    program.host.writeFile = async (path: string, content: string) => {
      captured.set(path, content);
    };
    const ctx: EmitContext<ProtoEmitterOptions> = {
      program,
      emitterOutputDir: OUTPUT_DIR,
      options: {},
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    } as any;
    await $onEmit(ctx);
    program.host.writeFile = originalWrite;

    // No field-number-required diagnostic for the orm-only column.
    const fieldErr = program.diagnostics.find((d) => d.code.includes("field-number-required"));
    expect(fieldErr).toBeUndefined();

    const proto = captured.get(`${OUTPUT_DIR}/openlet/user/v1.proto`)!;
    expect(proto).toContain("string user_id = 1;");
    expect(proto).not.toContain("internal_revision");
  });
});
