# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from typing import Any, TYPE_CHECKING

from sqlalchemy import Column, Text
from sqlalchemy.dialects.postgresql import JSONB
from sqlmodel import Field, Relationship, SQLModel
from ...shared.world_owned import WorldOwned


if TYPE_CHECKING:
    from ...worlds.world import World


class Location(WorldOwned, table=True):
    """Physical or virtual location available inside a world."""

    __tablename__ = "locations"  # type: ignore

    # Name of the location - indexed for lookup.
    name: str = Field(
        index=True,
        max_length=200,
        sa_column_kwargs={
            "nullable": False,
            "comment": "Name of the location - indexed for lookup.",
        },
    )
    # Narrative description used in AI generation.
    description: str = Field(
        sa_column=Column(
            Text, nullable=False, comment="Narrative description used in AI generation."
        )
    )
    # Bounding box or point stored as GeoJSON.
    coordinates: dict[str, Any] | None = Field(
        default=None,
        sa_column=Column(JSONB, comment="Bounding box or point stored as GeoJSON."),
    )

    # ─── Relationships ─────────────────────
    world: World | None = Relationship()
