// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package metadata

import (
	"github.com/google/uuid"
)

// CommitFileVersionRequest CommitFileVersionRequest
type CommitFileVersionRequest struct {
	FileID uuid.UUID `validate:"required" json:"fileId"`
	StorageObjectID uuid.UUID `validate:"required" json:"storageObjectId"`
	SizeBytes int64 `validate:"required" json:"sizeBytes"`
	Sha256 string `validate:"required" json:"sha256"`
	ActorID uuid.UUID `validate:"required" json:"actorId"`
}
