// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package metadata

import (
	"github.com/google/uuid"
)

// CreateFolderRequest CreateFolderRequest
type CreateFolderRequest struct {
	VaultID uuid.UUID `validate:"required" json:"vaultId"`
	ParentID *uuid.UUID `validate:"omitempty" json:"parentId,omitempty"`
	Name string `validate:"required" json:"name"`
	ActorID uuid.UUID `validate:"required" json:"actorId"`
}
