// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package metadata

import (
	"github.com/google/uuid"
)

// CreateFileDraftResponse CreateFileDraftResponse
type CreateFileDraftResponse struct {
	File FileView `json:"file"`
	UploadIntentID uuid.UUID `validate:"required" json:"uploadIntentId"`
}
