// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package metadata

import (
	"github.com/google/uuid"
)

// FileVersionView FileVersionView
type FileVersionView struct {
	ID uuid.UUID `validate:"required" json:"id"`
	FileID uuid.UUID `validate:"required" json:"fileId"`
	VersionNumber int32 `validate:"required" json:"versionNumber"`
	StorageObjectID uuid.UUID `validate:"required" json:"storageObjectId"`
	SizeBytes int64 `validate:"required" json:"sizeBytes"`
	Sha256 string `validate:"required" json:"sha256"`
	CreatedAtIso string `validate:"required" json:"createdAtIso"`
}
