// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package metadata

import (
	"github.com/google/uuid"
)

// GetNodeRequest GetNodeRequest
type GetNodeRequest struct {
	NodeID uuid.UUID `validate:"required" json:"nodeId"`
	RequesterID uuid.UUID `validate:"required" json:"requesterId"`
}
