// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package metadata

import (
	file_vault_shared "github.com/example/file-vault/metadata-svc/file_vault/shared"
)

// ListFileVersionsResponse ListFileVersionsResponse
type ListFileVersionsResponse struct {
	Versions []FileVersionView `json:"versions"`
	Page file_vault_shared.PageInfo `json:"page"`
}
