// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package metadata

import (
	file_vault_shared "github.com/example/file-vault/metadata-svc/file_vault/shared"
)

// ListFolderResponse ListFolderResponse
type ListFolderResponse struct {
	Nodes []NodeView `json:"nodes"`
	Page file_vault_shared.PageInfo `json:"page"`
}
