// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package metadata

import (
	"github.com/google/uuid"

	file_vault_shared "github.com/example/file-vault/metadata-svc/file_vault/shared"
)

// ListFileVersionsRequest ListFileVersionsRequest
type ListFileVersionsRequest struct {
	FileID uuid.UUID `validate:"required" json:"fileId"`
	RequesterID uuid.UUID `validate:"required" json:"requesterId"`
	Page file_vault_shared.PageRequest `json:"page"`
}
