# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from sqlalchemy import Column, ForeignKey, Table
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlmodel import SQLModel


user_badges = Table(
    "user_badges",
    SQLModel.metadata,
    Column("badge_id", PGUUID(as_uuid=True), ForeignKey("badges.id"), primary_key=True),
    Column("user_id", PGUUID(as_uuid=True), ForeignKey("users.id"), primary_key=True),
)

__all__ = [
    "user_badges",
]
