import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const CreateInvitationFormSchema = z
  .object({
    inviteeEmail: z
      .string()
      .max(320)
      .email()

        .describe("Email address of the person being invited. Lookup type: inherits @maxLength(320) and @format(\"email\") from User.email. @title and @placeholder target ModelProperty - apply inline as normal."),
    worldName: z
      .string()
      .max(200)

        .describe("Name of the world to invite into. Lookup type: inherits @maxLength(200) from World.name."),
    worldPrompt: z
      .string()

        .describe("Prompt text for the target world. Lookup type whose source scalar is `text` (custom, not a built-in) - used below to demonstrate `@@inputType` via `World.prompt::type`."),
    message: z
      .string()
      .optional()

        .describe("Optional personal message included in the invitation. Direct custom scalar (`text`) - @inputType applied via `::type` below."),
  })

    .describe("Form payload for creating an invitation. Uses `@data` instead of `@table` - no DB schema is generated. `::type` rule for decorators that require a `Scalar` target (e.g. `@inputType`): - Direct-scalar field  (`message?: text`)  → `@@dec(Form.message::type, ...)` `::type` resolves to the `text` scalar directly. ✓ - Lookup-typed field (`worldPrompt: World.prompt`) → `Form.worldPrompt::type` resolves to the source `ModelProperty` (`World.prompt`), NOT the scalar. Go one level deeper via the source property: `@@dec(World.prompt::type, ...)`. ✓")
export type CreateInvitationForm = z.infer<typeof CreateInvitationFormSchema>;
