import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const UserProfileSchema = z
  .object({
    id: z.string().describe("Unique identifier - use"),
    email: z
      .string()
      .max(320)
      .email()

        .describe("Email address used for login - indexed for fast lookup. Constrained to max 320 characters with @format(\"email\") validation."),
    displayName: z
      .string()
      .max(100)
      .describe("Display name shown in the UI - max 100 characters"),
    avatarUrl: z
      .string()
      .max(512)
      .url()
      .optional()

        .describe("Optional avatar image URL - must be a valid URL, max 512 characters"),
  })

    .describe("Lightweight user profile view. Picks only the identity + display columns from User.")
export type UserProfile = z.infer<typeof UserProfileSchema>;
