import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const DisplayNameSchema = z.string().min(1).max(255).brand("DisplayName")
export const PageSizeSchema = z.number().int().gte(1).lte(100).brand("PageSize")
export const SearchQuerySchema = z.string().min(1).max(512).brand("SearchQuery")
export const StrongPasswordSchema = z
  .string()
  .min(8)
  .max(128)
  .regex(/^(?=.*[A-Z])(?=.*[0-9]).*$/)
  .brand("StrongPassword")
