# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from typing import TYPE_CHECKING
from uuid import UUID, uuid4
from datetime import datetime

from sqlalchemy import Column, DateTime, ForeignKey, UniqueConstraint, func
from sqlmodel import Field, Relationship, SQLModel

if TYPE_CHECKING:
    from ...worlds.world import World


class Tag(SQLModel, table=True):
    """Tag used to classify and filter content pool entries. The (world_id, name) pair is unique per world."""

    __tablename__ = "tags"  # type: ignore
    __table_args__ = (
        UniqueConstraint("world_id", "name", name="tags_world_id_name_unique"),
    )

    # Unique identifier shared by most persisted records.
    id: UUID = Field(
        default_factory=uuid4,
        primary_key=True,
        sa_column_kwargs={
            "comment": "Unique identifier shared by most persisted records."
        },
    )
    # Timestamp when the record was created.
    created_at: datetime = Field(
        sa_column=Column(
            DateTime(timezone=True),
            nullable=False,
            server_default=func.now(),
            comment="Timestamp when the record was created.",
        )
    )
    # Timestamp of the last update.
    updated_at: datetime | None = Field(
        default=None,
        sa_column=Column(
            DateTime(timezone=True), comment="Timestamp of the last update."
        ),
    )
    # Soft delete marker for archival workflows.
    deleted_at: datetime | None = Field(
        default=None,
        sa_column=Column(
            DateTime(timezone=True),
            comment="Soft delete marker for archival workflows.",
            index=True,
        ),
    )
    # Foreign key to the owning world.
    world_id: UUID = Field(
        sa_column=Column(
            ForeignKey("worlds.id", ondelete="CASCADE", onupdate="CASCADE"),
            nullable=False,
            comment="Foreign key to the owning world.",
            index=True,
        )
    )
    # Tag name - unique within a world.
    name: str = Field(
        max_length=100,
        sa_column_kwargs={
            "nullable": False,
            "comment": "Tag name - unique within a world.",
        },
    )
    # Category used to group related tags.
    category: str = Field(
        index=True,
        max_length=50,
        sa_column_kwargs={
            "nullable": False,
            "comment": "Category used to group related tags.",
        },
    )

    # ─── Relationships ─────────────────────
    world: World | None = Relationship()
