# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from typing import Any, TYPE_CHECKING
from uuid import UUID, uuid4
from datetime import datetime

from sqlalchemy import Column, DateTime, ForeignKey, func, Text
from sqlalchemy.dialects.postgresql import JSONB
from sqlmodel import Field, Relationship, SQLModel

if TYPE_CHECKING:
    from ...worlds.world import World


class Location(SQLModel, table=True):
    """Physical or virtual location available inside a world."""

    __tablename__ = "locations"  # type: ignore

    # Unique identifier shared by most persisted records.
    id: UUID = Field(
        default_factory=uuid4,
        primary_key=True,
        sa_column_kwargs={
            "comment": "Unique identifier shared by most persisted records."
        },
    )
    # Timestamp when the record was created.
    created_at: datetime = Field(
        sa_column=Column(
            DateTime(timezone=True),
            nullable=False,
            server_default=func.now(),
            comment="Timestamp when the record was created.",
        )
    )
    # Timestamp of the last update.
    updated_at: datetime | None = Field(
        default=None,
        sa_column=Column(
            DateTime(timezone=True), comment="Timestamp of the last update."
        ),
    )
    # Soft delete marker for archival workflows.
    deleted_at: datetime | None = Field(
        default=None,
        sa_column=Column(
            DateTime(timezone=True),
            comment="Soft delete marker for archival workflows.",
            index=True,
        ),
    )
    # Foreign key to the owning world.
    world_id: UUID = Field(
        sa_column=Column(
            ForeignKey("worlds.id", ondelete="CASCADE", onupdate="CASCADE"),
            nullable=False,
            comment="Foreign key to the owning world.",
            index=True,
        )
    )
    # Name of the location - indexed for lookup.
    name: str = Field(
        index=True,
        max_length=200,
        sa_column_kwargs={
            "nullable": False,
            "comment": "Name of the location - indexed for lookup.",
        },
    )
    # Narrative description used in AI generation.
    description: str = Field(
        sa_column=Column(
            Text, nullable=False, comment="Narrative description used in AI generation."
        )
    )
    # Bounding box or point stored as GeoJSON.
    coordinates: dict[str, Any] | None = Field(
        default=None,
        sa_column=Column(JSONB, comment="Bounding box or point stored as GeoJSON."),
    )

    # ─── Relationships ─────────────────────
    world: World | None = Relationship()
