// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package taxonomy

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"

	demo_game_platform_worlds "github.com/demo-user/demo/demo/game_platform/worlds"
)

// Tag Tag used to classify and filter content pool entries. The (world_id, name) pair is unique per world.
type Tag struct {
	// Unique identifier shared by most persisted records.
	ID uuid.UUID `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid();comment:Unique identifier shared by most persisted records." json:"id"`
	// Timestamp when the record was created.
	CreatedAt time.Time `gorm:"column:created_at;type:timestamptz;autoCreateTime;not null;comment:Timestamp when the record was created." json:"createdAt"`
	// Timestamp of the last update.
	UpdatedAt *time.Time `gorm:"column:updated_at;type:timestamptz;comment:Timestamp of the last update." validate:"omitempty" json:"updatedAt,omitempty"`
	// Soft delete marker for archival workflows.
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;index;comment:Soft delete marker for archival workflows." json:"deletedAt"`
	// Foreign key to the owning world.
	WorldID uuid.UUID `gorm:"column:world_id;type:uuid;not null;index:tags_world_id_idx;uniqueIndex:tags_world_id_name_unique,priority:1;comment:Foreign key to the owning world." validate:"required" json:"worldId"`
	// Tag name - unique within a world.
	Name string `gorm:"column:name;type:varchar(100);not null;uniqueIndex:tags_world_id_name_unique,priority:2;comment:Tag name - unique within a world." validate:"required,max=100" json:"name"`
	// Category used to group related tags.
	Category string `gorm:"column:category;type:varchar(50);not null;index:tags_category_idx;comment:Category used to group related tags." validate:"required,max=50" json:"category"`

	// ─── Relationships ─────────────────────
	World demo_game_platform_worlds.World `gorm:"foreignKey:WorldID;references:ID;constraint:OnDelete:CASCADE,OnUpdate:CASCADE" json:"world"`
}

// TableName returns the table name for Tag.
func (Tag) TableName() string {
	return "tags"
}
