// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package audit

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/datatypes"

	demo_game_platform_accounts "github.com/demo-user/demo/demo/game_platform/accounts"
)

// AuditLog Immutable audit-log entry. Lives in its own namespace even though it references other bounded contexts.
type AuditLog struct {
	// Auto-incrementing surrogate key for stable ordering.
	ID int64 `gorm:"column:id;type:bigserial;primaryKey;autoIncrement;comment:Auto-incrementing surrogate key for stable ordering." json:"id"`
	// Logical type of the changed entity, e.g. "World" or "StoryNode".
	EntityType string `gorm:"column:entity_type;type:varchar(100);not null;index:audit_logs_entity_type_idx;index:audit_logs_entity_type_entity_id_idx,priority:1;comment:Logical type of the changed entity, e.g. 'World' or 'StoryNode'." validate:"required,max=100" json:"entityType"`
	// Primary key of the changed entity.
	EntityID uuid.UUID `gorm:"column:entity_id;type:uuid;not null;index:audit_logs_entity_type_entity_id_idx,priority:2;comment:Primary key of the changed entity." validate:"required" json:"entityId"`
	// Action performed: create, update, or delete.
	Action string `gorm:"column:action;type:varchar(50);not null;comment:Action performed: create, update, or delete." validate:"required,max=50" json:"action"`
	// Optional JSON snapshot or diff.
	Diff *datatypes.JSON `gorm:"column:diff;type:jsonb;comment:Optional JSON snapshot or diff." validate:"omitempty" json:"diff,omitempty"`
	// Nullable so audit history survives account deletion.
	ActorID   *uuid.UUID `gorm:"column:actor_id;type:uuid;index:audit_logs_actor_id_created_at_idx,priority:1;comment:Nullable so audit history survives account deletion." validate:"omitempty" json:"actorId,omitempty"`
	CreatedAt time.Time  `gorm:"column:created_at;type:timestamptz;autoCreateTime;not null;index:audit_logs_actor_id_created_at_idx,priority:2" json:"createdAt"`

	// ─── Relationships ─────────────────────
	// User who performed the action - SET NULL when the account is deleted.
	Actor *demo_game_platform_accounts.User `gorm:"foreignKey:ActorID;constraint:OnDelete:SET NULL,OnUpdate:CASCADE" json:"actor,omitempty"`
}

// TableName returns the table name for AuditLog.
func (AuditLog) TableName() string {
	return "audit_logs"
}
