# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from typing import Any, TYPE_CHECKING
from uuid import UUID
from datetime import datetime

from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy import Column, DateTime, Index, func
from sqlmodel import Field, Relationship, SQLModel

if TYPE_CHECKING:
    from ..accounts.user import User


class AuditLog(SQLModel, table=True):
    """Immutable audit-log entry. Lives in its own namespace even though it references other bounded contexts."""

    __tablename__ = "audit_logs"  # type: ignore
    __table_args__ = (
        Index("audit_logs_entity_type_entity_id_idx", "entity_type", "entity_id"),
        Index("audit_logs_actor_id_created_at_idx", "actor_id", "created_at"),
    )

    # Auto-incrementing surrogate key for stable ordering.
    id: int = Field(
        primary_key=True,
        sa_column_kwargs={
            "comment": "Auto-incrementing surrogate key for stable ordering."
        },
    )
    # Logical type of the changed entity, e.g. "World" or "StoryNode".
    entity_type: str = Field(
        index=True,
        max_length=100,
        sa_column_kwargs={
            "nullable": False,
            "comment": 'Logical type of the changed entity, e.g. "World" or "StoryNode".',
        },
    )
    # Primary key of the changed entity.
    entity_id: UUID = Field(
        sa_column_kwargs={
            "nullable": False,
            "comment": "Primary key of the changed entity.",
        }
    )
    # Action performed: create, update, or delete.
    action: str = Field(
        max_length=50,
        sa_column_kwargs={
            "nullable": False,
            "comment": "Action performed: create, update, or delete.",
        },
    )
    # Optional JSON snapshot or diff.
    diff: dict[str, Any] | None = Field(
        default=None, sa_column=Column(JSONB, comment="Optional JSON snapshot or diff.")
    )
    # Nullable so audit history survives account deletion.
    actor_id: UUID | None = Field(
        default=None,
        foreign_key="users.id",
        sa_column_kwargs={
            "comment": "Nullable so audit history survives account deletion."
        },
    )
    created_at: datetime = Field(
        sa_column=Column(
            DateTime(timezone=True), nullable=False, server_default=func.now()
        )
    )

    # ─── Relationships ─────────────────────
    # User who performed the action - SET NULL when the account is deleted.
    actor: User | None = Relationship()
