/**
 * @qninhdt/typespec-sqlmodel
 *
 * TypeSpec emitter that generates SQLModel (Python) classes from
 * models decorated with @table and related decorators from @qninhdt/typespec-orm.
 */

import type { EmitContext, Enum, Model, ModelProperty, Program } from "@typespec/compiler";
import type { EnumMemberInfo, ResolvedRelation } from "@qninhdt/typespec-orm";
import {
  collectTableModels,
  collectDataModels,
  getTitle,
  getPlaceholder,
  getColumnName,
  getCompositeIndexes,
  getCompositeUniques,
  getDefaultValue,
  getDoc,
  getForeignKey,
  getFormat,
  getMaxLength,
  getMinLength,
  getMinValue,
  getMaxValue,
  getOnDelete,
  getOnUpdate,
  getPattern,
  getPrecision,
  getPropertyEnum,
  isAutoCreateTime,
  isAutoIncrement,
  isAutoUpdateTime,
  isId,
  isIndex,
  isSoftDelete,
  isUnique,
  resolveDbType,
  camelToSnake,
  // Shared emitter utilities
  NUMERIC_TYPES,
  classifyProperties,
} from "@qninhdt/typespec-orm";
import { reportDiagnostic, type SqlModelEmitterOptions } from "./lib.js";
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

// ─── Constants ───────────────────────────────────────────────────────────────

const FILE_HEADER =
  "# Code generated by @qninhdt/typespec-sqlmodel. DO NOT EDIT.\n# Source: https://github.com/qninhdt/typespec-libraries\n\n";

const FOUR_SPACES = "    ";

/** DB types that always need an explicit SA column type in `sa_column=Column(Type, ...)` */
const NEEDS_SA_COLUMN = new Set([
  "text",
  "jsonb",
  "utcDateTime",
  "date",
  "time",
  "bytes",
  "decimal",
]);

/**
 * Convert an array of column-level arguments (e.g. `nullable=False`, `server_default="0"`) into
 * a Python dict literal suitable for `sa_column_kwargs={...}`.
 *
 * **Important**: this serializer only handles simple `key=value` entries. It must NOT be called
 * when `columnArgs` contains callable expressions like `ForeignKey(...)` - those must go through
 * the `sa_column=Column(...)` path.
 */
function serializeColumnKwargs(columnArgs: string[]): string {
  const pairs = columnArgs.map((a) => {
    const eqIdx = a.indexOf("=");
    if (eqIdx === -1) return `"${a}": True`;
    const key = a.substring(0, eqIdx);
    const val = a.substring(eqIdx + 1);
    return `"${key}": ${val}`;
  });
  return `{${pairs.join(", ")}}`;
}

/**
 * Move Field-level `index=True`, `unique=True`, and `foreign_key="ref"` into Column-level args
 * when generating `sa_column=Column(...)`.  Returns a new `fieldArgs` with those entries removed.
 *
 * This is necessary because SQLModel ignores `Field(index=True, sa_column=Column(...))`
 * - the sa_column completely replaces the auto-generated column.
 */
function promoteFieldArgsToColumn(
  fieldArgs: string[],
  columnArgs: string[],
  saImports: Set<string>,
): string[] {
  const filtered: string[] = [];
  for (const a of fieldArgs) {
    if (a === "index=True") {
      columnArgs.push("index=True");
    } else if (a === "unique=True") {
      columnArgs.push("unique=True");
    } else if (a.startsWith("foreign_key=")) {
      // Convert Field-level foreign_key="ref" to Column-level ForeignKey("ref")
      const match = a.match(/^foreign_key="(.+)"$/);
      if (match) {
        saImports.add("sqlalchemy.ForeignKey");
        columnArgs.unshift(`ForeignKey("${match[1]}")`);
      }
    } else if (a.startsWith("nullable=") || a.startsWith("server_default=")) {
      // Already handled by columnArgs
      continue;
    } else {
      filtered.push(a);
    }
  }
  return filtered;
}

/** Maps canonical DB type names → Python type info */
interface PythonTypeMapping {
  pyType: string;
  saColumnType?: string;
  imports: readonly string[];
  saImports: readonly string[];
}

const UNKNOWN_PY_TYPE: PythonTypeMapping = {
  pyType: "Any",
  imports: ["typing.Any"],
  saImports: [],
};

/** Pre-built lookup table - avoids creating fresh Set objects on every call. */
const PYTHON_TYPE_MAP: Record<string, PythonTypeMapping> = {
  uuid: { pyType: "UUID", imports: ["uuid.UUID"], saImports: [] },
  string: { pyType: "str", saColumnType: "String", imports: [], saImports: ["sqlalchemy.String"] },
  text: { pyType: "str", saColumnType: "Text", imports: [], saImports: ["sqlalchemy.Text"] },
  boolean: {
    pyType: "bool",
    saColumnType: "Boolean",
    imports: [],
    saImports: ["sqlalchemy.Boolean"],
  },
  int8: {
    pyType: "int",
    saColumnType: "SmallInteger",
    imports: [],
    saImports: ["sqlalchemy.SmallInteger"],
  },
  int16: {
    pyType: "int",
    saColumnType: "SmallInteger",
    imports: [],
    saImports: ["sqlalchemy.SmallInteger"],
  },
  int32: {
    pyType: "int",
    saColumnType: "Integer",
    imports: [],
    saImports: ["sqlalchemy.Integer"],
  },
  serial: {
    pyType: "int",
    saColumnType: "Integer",
    imports: [],
    saImports: ["sqlalchemy.Integer"],
  },
  int64: {
    pyType: "int",
    saColumnType: "BigInteger",
    imports: [],
    saImports: ["sqlalchemy.BigInteger"],
  },
  bigserial: {
    pyType: "int",
    saColumnType: "BigInteger",
    imports: [],
    saImports: ["sqlalchemy.BigInteger"],
  },
  uint8: {
    pyType: "int",
    saColumnType: "Integer",
    imports: [],
    saImports: ["sqlalchemy.Integer"],
  },
  uint16: {
    pyType: "int",
    saColumnType: "Integer",
    imports: [],
    saImports: ["sqlalchemy.Integer"],
  },
  uint32: {
    pyType: "int",
    saColumnType: "BigInteger",
    imports: [],
    saImports: ["sqlalchemy.BigInteger"],
  },
  uint64: {
    pyType: "int",
    saColumnType: "BigInteger",
    imports: [],
    saImports: ["sqlalchemy.BigInteger"],
  },
  float32: { pyType: "float", saColumnType: "Float", imports: [], saImports: ["sqlalchemy.Float"] },
  float64: {
    pyType: "float",
    saColumnType: "Double",
    imports: [],
    saImports: ["sqlalchemy.Double"],
  },
  decimal: {
    pyType: "Decimal",
    saColumnType: "Numeric",
    imports: ["decimal.Decimal"],
    saImports: ["sqlalchemy.Numeric"],
  },
  utcDateTime: {
    pyType: "datetime",
    saColumnType: "DateTime(timezone=True)",
    imports: ["datetime.datetime"],
    saImports: ["sqlalchemy.DateTime"],
  },
  date: {
    pyType: "date",
    saColumnType: "Date",
    imports: ["datetime.date"],
    saImports: ["sqlalchemy.Date"],
  },
  time: {
    pyType: "time",
    saColumnType: "Time",
    imports: ["datetime.time"],
    saImports: ["sqlalchemy.Time"],
  },
  duration: {
    pyType: "timedelta",
    saColumnType: "Interval",
    imports: ["datetime.timedelta"],
    saImports: ["sqlalchemy.Interval"],
  },
  bytes: {
    pyType: "bytes",
    saColumnType: "LargeBinary",
    imports: [],
    saImports: ["sqlalchemy.LargeBinary"],
  },
  jsonb: {
    pyType: "dict[str, Any]",
    saColumnType: "JSONB",
    imports: ["typing.Any"],
    saImports: ["sqlalchemy.dialects.postgresql.JSONB"],
  },
};

function getPythonTypeMap(dbType: string): PythonTypeMapping {
  return PYTHON_TYPE_MAP[dbType] ?? UNKNOWN_PY_TYPE;
}

// ─── Emitter entry point ─────────────────────────────────────────────────────

export async function emit(context: EmitContext<SqlModelEmitterOptions>): Promise<void> {
  const { program } = context;
  const outputDir = context.emitterOutputDir;
  const moduleName = context.options["module-name"] ?? "models";

  const tables = collectTableModels(program);
  const dataModels = collectDataModels(program);

  if (tables.length === 0 && dataModels.length === 0) {
    reportDiagnostic(program, {
      code: "no-tables-found",
      target: program.getGlobalNamespaceType(),
    });
    return;
  }

  await mkdir(outputDir, { recursive: true });

  const allModelNames: string[] = [];
  const moduleFiles: string[] = [];

  for (const { model, tableName } of tables) {
    const code = generateSqlModel(program, model, tableName);
    const fileName = camelToSnake(model.name) + ".py";
    try {
      await writeFile(join(outputDir, fileName), code);
    } catch (err) {
      reportDiagnostic(program, {
        code: "emit-write-failed",
        messageId: "default",
        format: { fileName, error: String(err) },
        target: model,
      });
    }
    allModelNames.push(model.name);
    moduleFiles.push(fileName.replace(".py", ""));
  }

  for (const { model, label } of dataModels) {
    const code = generatePydanticModel(program, model, label);
    const fileName = camelToSnake(model.name) + ".py";
    try {
      await writeFile(join(outputDir, fileName), code);
    } catch (err) {
      reportDiagnostic(program, {
        code: "emit-write-failed",
        messageId: "default",
        format: { fileName, error: String(err) },
        target: model,
      });
    }
    allModelNames.push(model.name);
    moduleFiles.push(fileName.replace(".py", ""));
  }

  // Generate __init__.py that re-exports all models
  const initCode = generateInit(allModelNames, moduleFiles, moduleName);
  try {
    await writeFile(join(outputDir, "__init__.py"), initCode);
  } catch (err) {
    reportDiagnostic(program, {
      code: "emit-write-failed",
      messageId: "default",
      format: { fileName: "__init__.py", error: String(err) },
      target: program.getGlobalNamespaceType(),
    });
  }
}

// ─── Code generation ─────────────────────────────────────────────────────────

/**
 * Generate a Python `str, enum.Enum` class.
 */
function generateEnumClass(enumName: string, members: EnumMemberInfo[]): string {
  let code = `class ${enumName}(str, Enum):\n`;
  code += `${FOUR_SPACES}"""Auto-generated enum for ${camelToSnake(enumName)}."""\n\n`;
  for (const m of members) {
    code += `${FOUR_SPACES}${camelToSnake(m.name)} = "${m.value}"\n`;
  }
  return code;
}

// ─── @data model → Pydantic BaseModel generation ────────────────────────────

function generatePydanticField(
  program: Program,
  prop: ModelProperty,
  stdImports: Set<string>,
  pydanticImports: Set<string>,
): string {
  const pyFieldName = camelToSnake(prop.name);
  const dbType = resolveDbType(prop.type);
  const mapping = dbType ? getPythonTypeMap(dbType) : getPythonTypeMap("unknown");

  const enumInfo = getPropertyEnum(prop);
  let pyType = mapping.pyType;
  if (enumInfo) {
    pyType = enumInfo.enumType.name;
  } else {
    for (const imp of mapping.imports) stdImports.add(imp);
  }

  // Format-based type overrides (Pydantic v2 semantic types)
  const format = getFormat(program, prop);
  if (format === "email") {
    stdImports.add("pydantic.EmailStr");
    pyType = "EmailStr";
  } else if (format === "url" || format === "uri") {
    stdImports.add("pydantic.AnyUrl");
    pyType = "AnyUrl";
  } else if (format !== undefined && format !== null && format !== "") {
    reportDiagnostic(program, {
      code: "unknown-format",
      target: prop,
      format: { format, propName: prop.name },
    });
  }

  const isOpt = prop.optional;
  if (isOpt) {
    stdImports.add("typing.Optional");
    pyType = `Optional[${pyType}]`;
  }

  const fieldArgs: string[] = [isOpt ? "None" : "..."];

  const maxLen = getMaxLength(program, prop);
  const minLen = getMinLength(program, prop);
  const minVal = getMinValue(program, prop);
  const maxVal = getMaxValue(program, prop);
  const pattern = getPattern(program, prop);

  if (maxLen !== undefined) fieldArgs.push(`max_length=${maxLen}`);
  if (minLen !== undefined) fieldArgs.push(`min_length=${minLen}`);
  if (minVal !== undefined) fieldArgs.push(`ge=${minVal}`);
  if (maxVal !== undefined) fieldArgs.push(`le=${maxVal}`);
  if (pattern !== undefined) fieldArgs.push(`pattern=r"${pattern}"`);

  const label = getTitle(program, prop);
  if (label) fieldArgs.push(`title="${label.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`);

  const doc = getDoc(program, prop);
  if (doc) fieldArgs.push(`description="${doc.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`);

  const placeholder = getPlaceholder(program, prop);
  if (placeholder)
    fieldArgs.push(
      `json_schema_extra={"placeholder": "${placeholder.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"}`,
    );

  pydanticImports.add("Field");

  const docComment = doc ? `${FOUR_SPACES}# ${doc}\n` : "";

  return `${docComment}${FOUR_SPACES}${pyFieldName}: ${pyType} = Field(${fieldArgs.join(", ")})\n`;
}

function generatePydanticModel(program: Program, model: Model, label: string): string {
  const stdImports = new Set<string>();
  const pydanticImports = new Set<string>(["BaseModel"]);
  const enumTypes = new Map<string, EnumMemberInfo[]>();
  const fieldDefs: string[] = [];

  for (const [, prop] of model.properties) {
    const enumInfo = getPropertyEnum(prop);
    if (enumInfo && !enumTypes.has(enumInfo.enumType.name)) {
      enumTypes.set(enumInfo.enumType.name, enumInfo.members);
      stdImports.add("enum.Enum");
    }
    fieldDefs.push(generatePydanticField(program, prop, stdImports, pydanticImports));
  }

  let code = FILE_HEADER;

  const stdImportGroups = groupImports(stdImports);
  for (const [module, names] of stdImportGroups) {
    code += `from ${module} import ${[...names].sort().join(", ")}\n`;
  }
  if (stdImportGroups.size > 0) code += "\n";

  const pydanticList = [...pydanticImports].sort();
  code += `from pydantic import ${pydanticList.join(", ")}\n`;
  code += "\n\n";

  for (const [enumName, members] of enumTypes) {
    code += generateEnumClass(enumName, members);
    code += "\n\n";
  }

  const modelDoc = getDoc(program, model);
  code += `class ${model.name}(BaseModel):\n`;
  code += `${FOUR_SPACES}"""${modelDoc ?? label}"""\n`;
  code += "\n";

  for (const field of fieldDefs) {
    code += field;
  }

  return code;
}

function generateSqlModel(program: Program, model: Model, tableName: string): string {
  // Collect all imports needed
  const stdImports = new Set<string>(); // "from X import Y" style
  const saImports = new Set<string>(); // SQLAlchemy imports
  const sqlmodelImports = new Set<string>(["SQLModel"]); // always need SQLModel
  const needsField = { value: false };
  const needsColumn = { value: false };
  const needsRelationship = { value: false };

  // Classify properties using shared utility
  const {
    enumTypes,
    ignored,
    relations,
    fields: regularProps,
  } = classifyProperties(program, model);

  // Pre-scan properties to determine imports and collect enums
  const fieldDefs: string[] = [];
  const relationDefs: string[] = [];

  // Ignored fields - emit as ClassVar (excluded from DB)
  for (const { prop, enumInfo } of ignored) {
    const dbType = resolveDbType(prop.type);
    const mapping = dbType ? getPythonTypeMap(dbType) : getPythonTypeMap("unknown");
    let pyType = mapping.pyType;
    if (enumInfo) {
      pyType = enumInfo.enumType.name;
    } else {
      for (const imp of mapping.imports) stdImports.add(imp);
    }
    stdImports.add("typing.ClassVar");
    const finalType = prop.optional ? `${pyType} | None` : pyType;
    const doc = getDoc(program, prop);
    const docComment = doc ? `${FOUR_SPACES}# ${doc}\n` : "";
    fieldDefs.push(
      `${docComment}${FOUR_SPACES}${camelToSnake(prop.name)}: ClassVar[${finalType}]  # @ignore - not persisted\n`,
    );
  }

  // Relationship navigation fields
  for (const { prop, resolved } of relations) {
    needsRelationship.value = true;
    if (resolved.autoInjectFk) {
      fieldDefs.push(
        generateAutoFkField(
          program,
          prop,
          resolved,
          stdImports,
          saImports,
          sqlmodelImports,
          needsField,
          needsColumn,
        ),
      );
    }
    relationDefs.push(generateResolvedRelationField(program, prop, resolved));
  }

  // Regular DB-mapped fields
  for (const { prop } of regularProps) {
    fieldDefs.push(
      generateField(program, prop, stdImports, saImports, sqlmodelImports, needsField, needsColumn),
    );
  }

  if (needsField.value) {
    sqlmodelImports.add("Field");
  }
  if (needsColumn.value) {
    saImports.add("sqlalchemy.Column");
  }
  if (needsRelationship.value) {
    sqlmodelImports.add("Relationship");
  }

  // Composite indexes & unique constraints → __table_args__
  const compIdxs = getCompositeIndexes(program, model);
  const compUnqs = getCompositeUniques(program, model);
  const hasTableArgs = compIdxs.length > 0 || compUnqs.length > 0;
  if (compIdxs.length > 0) {
    saImports.add("sqlalchemy.Index");
  }
  if (compUnqs.length > 0) {
    saImports.add("sqlalchemy.UniqueConstraint");
  }

  // Add enum import if any enums collected
  if (enumTypes.size > 0) {
    stdImports.add("enum.Enum");
    saImports.add("sqlalchemy.Enum as SAEnum");
  }

  // Build import section
  let code = FILE_HEADER;

  // Group standard library imports
  const stdImportGroups = groupImports(stdImports);
  for (const [module, names] of stdImportGroups) {
    code += `from ${module} import ${[...names].sort().join(", ")}\n`;
  }
  if (stdImportGroups.size > 0) code += "\n";

  // SQLAlchemy imports
  const saImportGroups = groupImports(saImports);
  for (const [module, names] of saImportGroups) {
    code += `from ${module} import ${[...names].sort().join(", ")}\n`;
  }

  // SQLModel import
  const sqlmodelList = [...sqlmodelImports].sort();
  code += `from sqlmodel import ${sqlmodelList.join(", ")}\n`;
  code += "\n\n";

  // Enum class definitions before the model class
  for (const [enumName, members] of enumTypes) {
    code += generateEnumClass(enumName, members);
    code += "\n\n";
  }

  // Class definition
  const modelDoc = getDoc(program, model);
  code += `class ${model.name}(SQLModel, table=True):\n`;
  code += `${FOUR_SPACES}"""${modelDoc ?? `Represents the ${tableName} table.`}"""\n\n`;
  code += `${FOUR_SPACES}__tablename__ = "${tableName}"\n`;

  // Composite indexes / unique constraints
  if (hasTableArgs) {
    const tableArgEntries: string[] = [];
    for (const idx of compIdxs) {
      const cols = idx.columns.map((c) => `"${c}"`).join(", ");
      tableArgEntries.push(`${FOUR_SPACES}${FOUR_SPACES}Index("${idx.name}", ${cols})`);
    }
    for (const unq of compUnqs) {
      const cols = unq.columns.map((c) => `"${c}"`).join(", ");
      tableArgEntries.push(
        `${FOUR_SPACES}${FOUR_SPACES}UniqueConstraint(${cols}, name="${unq.name}")`,
      );
    }
    code += `${FOUR_SPACES}__table_args__ = (\n`;
    code += tableArgEntries.join(",\n") + ",\n";
    code += `${FOUR_SPACES})\n`;
  }

  code += "\n";

  for (const field of fieldDefs) {
    code += field;
  }

  if (relationDefs.length > 0) {
    code += `\n${FOUR_SPACES}# ─── Relationships ─────────────────────\n`;
    for (const rd of relationDefs) {
      code += rd;
    }
  }

  return code;
}

/**
 * Generate a SQLModel Field() for an auto-injected foreign key column.
 * Called for many-to-one / one-to-one relations where the FK is auto-derived.
 */
function generateAutoFkField(
  program: Program,
  relationProp: ModelProperty,
  rel: ResolvedRelation,
  stdImports: Set<string>,
  saImports: Set<string>,
  sqlmodelImports: Set<string>,
  needsField: { value: boolean },
  needsColumn: { value: boolean },
): string {
  const pyFieldName = rel.fkColumnName;
  const isOptional = relationProp.optional;

  const mapping = rel.fkDbType ? getPythonTypeMap(rel.fkDbType) : getPythonTypeMap("uuid");
  for (const imp of mapping.imports) stdImports.add(imp);
  for (const imp of mapping.saImports) saImports.add(imp);

  let pyType = mapping.pyType;
  if (isOptional) pyType = `${pyType} | None`;

  needsField.value = true;
  const fieldArgs: string[] = [];
  const columnArgs: string[] = [];

  if (isOptional) fieldArgs.push("default=None");
  if (!isOptional) columnArgs.push("nullable=False");

  // FK columns are indexed unless covered by a leading composite constraint; @unique overrides
  if (isUnique(program, relationProp)) {
    fieldArgs.push("unique=True");
  } else if (rel.autoInjectIndex) {
    fieldArgs.push("index=True");
  }

  // Foreign key reference with optional cascade constraints
  const fkRef = `${rel.targetTable}.${rel.fkTargetColumn}`;

  if (rel.onDelete || rel.onUpdate) {
    needsColumn.value = true;
    saImports.add("sqlalchemy.ForeignKey");
    const fkArgs: string[] = [`"${fkRef}"`];
    if (rel.onDelete) fkArgs.push(`ondelete="${rel.onDelete}"`);
    if (rel.onUpdate) fkArgs.push(`onupdate="${rel.onUpdate}"`);
    columnArgs.unshift(`ForeignKey(${fkArgs.join(", ")})`);
  } else {
    fieldArgs.push(`foreign_key="${fkRef}"`);
  }

  // @doc on relation → comment on FK column
  const doc = getDoc(program, relationProp);
  if (doc) {
    needsColumn.value = true;
    columnArgs.push(`comment="${doc.replace(/"/g, '\\"')}"`);
  }

  const docComment = doc ? `${FOUR_SPACES}# ${doc}\n` : "";

  // Determine whether to use sa_column=Column(...) or sa_column_kwargs={...}
  // Use sa_column when: type needs explicit SA column type, OR columnArgs contains ForeignKey(...)
  const needsExplicitColumn =
    (rel.fkDbType && NEEDS_SA_COLUMN.has(rel.fkDbType) && mapping.saColumnType) ||
    columnArgs.some((a) => a.startsWith("ForeignKey("));

  if (needsExplicitColumn) {
    needsColumn.value = true;
    saImports.add("sqlalchemy.Column");
    // Move index/unique/foreign_key from Field to Column
    const filteredFieldArgs = promoteFieldArgsToColumn(fieldArgs, columnArgs, saImports);
    const saType = mapping.saColumnType;
    const allColumnArgs = saType ? [saType, ...columnArgs].join(", ") : columnArgs.join(", ");
    filteredFieldArgs.push(`sa_column=Column(${allColumnArgs})`);
    return `${docComment}${FOUR_SPACES}${pyFieldName}: ${pyType} = Field(${filteredFieldArgs.join(", ")})\n`;
  }

  // Simple field with sa_column_kwargs (no ForeignKey here - safe to serialize)
  if (columnArgs.length > 0) {
    fieldArgs.push(`sa_column_kwargs=${serializeColumnKwargs(columnArgs)}`);
  }

  return `${docComment}${FOUR_SPACES}${pyFieldName}: ${pyType} = Field(${fieldArgs.join(", ")})\n`;
}

/**
 * Generate a SQLModel Relationship() for a navigation property.
 * - many-to-one: `user: "User" | None = Relationship(...)`
 * - one-to-many: `story_nodes: list["StoryNode"] = Relationship(...)`
 */
function generateResolvedRelationField(
  program: Program,
  prop: ModelProperty,
  rel: ResolvedRelation,
): string {
  const pyFieldName = camelToSnake(prop.name);
  const pyRefType = `"${rel.targetModel.name}"`;

  const isMany = rel.kind === "one-to-many" || rel.kind === "many-to-many";
  const pyType = isMany ? `list[${pyRefType}]` : `${pyRefType} | None`;

  const relArgs: string[] = [];

  // back_populates for bidirectional relationship
  if (rel.backPopulates) {
    relArgs.push(`back_populates="${rel.backPopulates}"`);
  }

  // Warn when one-to-many has no inverse FK detected
  if (rel.kind === "one-to-many" && !rel.backPopulates) {
    reportDiagnostic(program, {
      code: "missing-back-reference",
      format: {
        propName: prop.name,
        modelName: (prop.model as Model)?.name ?? "<unknown>",
        targetModel: rel.targetModel.name,
      },
      target: prop,
    });
  }

  // Self-referential many-to-one: SQLAlchemy needs explicit foreign_keys to
  // avoid AmbiguousForeignKeysError (the target table has multiple FKs to itself)
  const isSelfRef =
    (rel.kind === "many-to-one" || rel.kind === "one-to-one") && prop.model === rel.targetModel;
  if (isSelfRef) {
    relArgs.push(
      `sa_relationship_kwargs={"foreign_keys": "[${rel.targetModel.name}.${rel.fkColumnName}]"}`,
    );
  }

  // Cascade for one-to-many with delete actions
  if (isMany && rel.onDelete === "CASCADE") {
    relArgs.push('cascade="all, delete-orphan"');
  } else if (isMany && rel.onDelete === "SET NULL") {
    relArgs.push('cascade="save-update, merge"');
  }

  const doc = getDoc(program, prop);
  const docComment = doc ? `${FOUR_SPACES}# ${doc}\n` : "";
  return `${docComment}${FOUR_SPACES}${pyFieldName}: ${pyType} = Relationship(${relArgs.join(", ")})\n`;
}

/**
 * Generate a field definition for an enum-typed property.
 * Uses `sa_column=Column(SAEnum(EnumType))` for proper DB enum mapping.
 */
function generateEnumField(
  program: Program,
  prop: ModelProperty,
  pyFieldName: string,
  columnName: string,
  enumInfo: { enumType: Enum; members: EnumMemberInfo[] },
  saImports: Set<string>,
  sqlmodelImports: Set<string>,
  needsField: { value: boolean },
  needsColumn: { value: boolean },
): string {
  const enumTypeName = enumInfo.enumType.name;
  let pyType = enumTypeName;
  const isOptional = prop.optional;
  const isPk = isId(program, prop);

  if (isOptional) {
    pyType = `${pyType} | None`;
  }

  needsField.value = true;
  needsColumn.value = true;
  saImports.add("sqlalchemy.Column");

  const columnArgs: string[] = [`SAEnum(${enumTypeName})`];

  if (!isOptional && !isPk) {
    columnArgs.push("nullable=False");
  }

  // Index
  if (isIndex(program, prop)) {
    columnArgs.push("index=True");
  }

  // Unique
  if (isUnique(program, prop)) {
    columnArgs.push("unique=True");
  }

  // Default value
  const defaultVal = getDefaultValue(program, prop);
  if (defaultVal) {
    columnArgs.push(`server_default="${defaultVal}"`);
  }

  // @doc → comment
  const doc = getDoc(program, prop);
  if (doc) {
    columnArgs.push(`comment="${doc.replace(/"/g, '\\"')}"`);
  }

  const fieldArgs: string[] = [];
  if (isOptional) {
    fieldArgs.push("default=None");
  }
  if (isPk) {
    fieldArgs.push("primary_key=True");
  }
  fieldArgs.push(`sa_column=Column(${columnArgs.join(", ")})`);

  const docComment = doc ? `${FOUR_SPACES}# ${doc}\n` : "";
  return `${docComment}${FOUR_SPACES}${pyFieldName}: ${pyType} = Field(${fieldArgs.join(", ")})\n`;
}

function generateField(
  program: Program,
  prop: ModelProperty,
  stdImports: Set<string>,
  saImports: Set<string>,
  sqlmodelImports: Set<string>,
  needsField: { value: boolean },
  needsColumn: { value: boolean },
): string {
  const columnName = getColumnName(program, prop);
  const pyFieldName = columnName; // Python uses snake_case which matches column names
  const dbType = resolveDbType(prop.type);

  // Check for enum type
  const enumInfo = getPropertyEnum(prop);
  if (enumInfo) {
    return generateEnumField(
      program,
      prop,
      pyFieldName,
      columnName,
      enumInfo,
      saImports,
      sqlmodelImports,
      needsField,
      needsColumn,
    );
  }

  const mapping = dbType ? getPythonTypeMap(dbType) : getPythonTypeMap("unknown");

  if (!dbType || mapping.pyType === "Any") {
    reportDiagnostic(program, {
      code: "unsupported-type",
      format: { typeName: dbType ?? prop.type.kind, propName: prop.name },
      target: prop,
    });
  }

  // Collect Python type imports (always needed for type annotation)
  for (const imp of mapping.imports) {
    stdImports.add(imp);
  }
  // SA column type imports added later, only when we emit Column(...) with that type

  let pyType = mapping.pyType;
  const isOptional = prop.optional;
  const isPk = isId(program, prop);
  const isSoft = isSoftDelete(program, prop);
  const isAutoInc = isAutoIncrement(program, prop) || dbType === "serial" || dbType === "bigserial";
  const isIdx = isIndex(program, prop);
  const isUnq = isUnique(program, prop);
  const maxLen = getMaxLength(program, prop);
  const defaultVal = getDefaultValue(program, prop);
  const fk = getForeignKey(program, prop);
  const prec = getPrecision(program, prop);

  // AutoCreateTime / AutoUpdateTime
  const autoCreate = isAutoCreateTime(program, prop);
  const autoUpdate = isAutoUpdateTime(program, prop);

  // Format-based type overrides (Pydantic v2 semantic types)
  const format = getFormat(program, prop);
  if (format === "email") {
    stdImports.add("pydantic.EmailStr");
    pyType = "EmailStr";
  } else if (format === "url" || format === "uri") {
    stdImports.add("pydantic.AnyUrl");
    pyType = "AnyUrl";
  } else if (format !== undefined && format !== null && format !== "") {
    reportDiagnostic(program, {
      code: "unknown-format",
      target: prop,
      format: { format, propName: prop.name },
    });
  }

  // Handle optional types
  if (isOptional || isSoft) {
    pyType = `${pyType} | None`;
  }

  // Determine if we need Field() and/or Column()
  const fieldArgs: string[] = [];
  const columnArgs: string[] = [];

  // Primary key
  if (isPk) {
    needsField.value = true;
    if (dbType === "uuid") {
      stdImports.add("uuid.uuid4");
      fieldArgs.push("default_factory=uuid4");
    }
    fieldArgs.push("primary_key=True");
  }

  // Auto-increment
  if (isAutoInc && !isPk) {
    needsColumn.value = true;
    columnArgs.push("autoincrement=True");
  }

  // Nullable
  if (!isOptional && !isPk) {
    columnArgs.push("nullable=False");
  }
  if (isOptional || isSoft) {
    needsField.value = true;
    fieldArgs.push("default=None");
  }

  // Index
  if (isIdx || fk) {
    needsField.value = true;
    fieldArgs.push("index=True");
  }

  // Unique
  if (isUnq) {
    needsField.value = true;
    fieldArgs.push("unique=True");
  }

  // String length constraints (Pydantic v2 Field params)
  const isStringType = dbType === "string" || dbType === "text";
  if (isStringType) {
    const minLen = getMinLength(program, prop);
    if (minLen !== undefined) {
      needsField.value = true;
      fieldArgs.push(`min_length=${minLen}`);
    }
    if (maxLen !== undefined) {
      needsField.value = true;
      fieldArgs.push(`max_length=${maxLen}`);
    } else if (dbType === "string") {
      needsField.value = true;
      fieldArgs.push("max_length=255");
    }
  }

  // Numeric range constraints (Pydantic v2 ge/le) - includes decimal
  const isNumericType = dbType !== undefined && NUMERIC_TYPES.has(dbType);
  if (isNumericType) {
    const minVal = getMinValue(program, prop);
    const maxVal = getMaxValue(program, prop);
    if (minVal !== undefined) {
      needsField.value = true;
      fieldArgs.push(`ge=${minVal}`);
    }
    if (maxVal !== undefined) {
      needsField.value = true;
      fieldArgs.push(`le=${maxVal}`);
    }
  }

  // Precision for decimal → override saColumnType
  let overrideSaColumnType: string | undefined;
  if (prec && (dbType === "decimal" || dbType === "float64")) {
    overrideSaColumnType = `Numeric(${prec.precision}, ${prec.scale})`;
    saImports.add("sqlalchemy.Numeric");
  }

  // Pattern constraint
  const pattern = getPattern(program, prop);
  if (pattern) {
    needsField.value = true;
    const escaped = pattern.replace(/\\/g, "\\\\");
    fieldArgs.push(`pattern=r"${escaped}"`);
  }

  // Server defaults
  if (autoCreate) {
    needsColumn.value = true;
    saImports.add("sqlalchemy.func");
    columnArgs.push("server_default=func.now()");
  }
  if (autoUpdate) {
    needsColumn.value = true;
    saImports.add("sqlalchemy.func");
    columnArgs.push("onupdate=func.now()");
    if (!autoCreate) {
      columnArgs.push("server_default=func.now()");
    }
  }

  // Default value (non-auto-timestamp)
  if (defaultVal && !isPk && !autoCreate && !autoUpdate) {
    needsColumn.value = true;
    columnArgs.push(`server_default="${defaultVal}"`);
  }

  // Foreign key with cascade constraints
  if (fk) {
    needsField.value = true;
    const onDel = getOnDelete(program, prop);
    const onUpd = getOnUpdate(program, prop);

    if (onDel || onUpd) {
      // Use sa_column with ForeignKey to pass ondelete/onupdate
      needsColumn.value = true;
      saImports.add("sqlalchemy.ForeignKey");
      const fkArgs: string[] = [`"${fk.table}.${fk.column}"`];
      if (onDel) fkArgs.push(`ondelete="${onDel}"`);
      if (onUpd) fkArgs.push(`onupdate="${onUpd}"`);
      columnArgs.unshift(`ForeignKey(${fkArgs.join(", ")})`);
      // Don't also add plain foreign_key
    } else {
      fieldArgs.push(`foreign_key="${fk.table}.${fk.column}"`);
    }
  }

  // Soft delete - add index for efficient filtering
  if (isSoft) {
    needsField.value = true;
    if (!fieldArgs.some((a) => a.startsWith("index="))) {
      fieldArgs.push("index=True");
    }
  }

  // @doc → SQLAlchemy comment parameter
  const doc = getDoc(program, prop);
  if (doc) {
    needsColumn.value = true;
    columnArgs.push(`comment="${doc.replace(/"/g, '\\"')}"`);
  }

  const docComment = doc ? `${FOUR_SPACES}# ${doc}\n` : "";

  // Determine whether to use sa_column=Column(...) or sa_column_kwargs={...}
  // Use sa_column when: type needs explicit SA column type, has precision override,
  // or columnArgs contains callable expressions like ForeignKey(...)
  const effectiveSaColumnType = overrideSaColumnType ?? mapping.saColumnType ?? "";
  const needsExplicitColumn =
    (dbType && NEEDS_SA_COLUMN.has(dbType) && effectiveSaColumnType && !isPk) ||
    overrideSaColumnType ||
    columnArgs.some((a) => a.startsWith("ForeignKey("));
  if (needsExplicitColumn) {
    // Only add SA column type import here - when we actually emit Column(SaType, ...)
    for (const imp of mapping.saImports) {
      saImports.add(imp);
    }
    needsColumn.value = true;
    needsField.value = true;
    // Move index/unique/foreign_key from Field to Column
    const filteredFieldArgs = promoteFieldArgsToColumn(fieldArgs, columnArgs, saImports);
    const saType = effectiveSaColumnType || mapping.saColumnType;
    const allColumnArgs = saType ? [saType, ...columnArgs].join(", ") : columnArgs.join(", ");
    filteredFieldArgs.push(`sa_column=Column(${allColumnArgs})`);
    return `${docComment}${FOUR_SPACES}${pyFieldName}: ${pyType} = Field(${filteredFieldArgs.join(", ")})\n`;
  }

  // Field() construction - emit whenever there are field or column args
  // (covers cases like boolean/int with only server_default/nullable that never set needsField)
  if (fieldArgs.length > 0 || columnArgs.length > 0) {
    needsField.value = true;
    if (columnArgs.length > 0) {
      fieldArgs.push(`sa_column_kwargs=${serializeColumnKwargs(columnArgs)}`);
    }
    return `${docComment}${FOUR_SPACES}${pyFieldName}: ${pyType} = Field(${fieldArgs.join(", ")})\n`;
  }

  // Plain field - no decorators needed
  return `${docComment}${FOUR_SPACES}${pyFieldName}: ${pyType}\n`;
}

function generateInit(modelNames: string[], moduleFiles: string[], moduleName: string): string {
  let code = `"""${moduleName} — auto-generated models. DO NOT EDIT."""\n\n`;

  for (let i = 0; i < modelNames.length; i++) {
    code += `from .${moduleFiles[i]} import ${modelNames[i]}\n`;
  }

  code += "\n__all__ = [\n";
  for (const name of modelNames) {
    code += `${FOUR_SPACES}"${name}",\n`;
  }
  code += "]\n";

  return code;
}

// ─── Utilities ───────────────────────────────────────────────────────────────

/**
 * Group "module.Name" imports into { module → Set<Name> }.
 * Supports aliased imports: "sqlalchemy.dialects.postgresql.JSONB as JSONB"
 */
function groupImports(imports: Set<string>): Map<string, Set<string>> {
  const groups = new Map<string, Set<string>>();

  for (const imp of imports) {
    // Handle "some.module.Name as Alias" pattern
    const asMatch = imp.match(/^(.+)\.(\w+)\s+as\s+(\w+)$/);
    if (asMatch) {
      const [, mod, name, alias] = asMatch;
      const module = mod;
      if (!groups.has(module)) groups.set(module, new Set());
      groups.get(module)!.add(`${name} as ${alias}`);
      continue;
    }

    // Handle "module.Name" pattern
    const lastDot = imp.lastIndexOf(".");
    if (lastDot === -1) continue;

    const module = imp.substring(0, lastDot);
    const name = imp.substring(lastDot + 1);

    if (!groups.has(module)) groups.set(module, new Set());
    groups.get(module)!.add(name);
  }

  return groups;
}
