import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const CreateNotificationRequestSchema = z.object({
  recipientId: z.uuid(),
  subject: z.string(),
  body: z.string(),
  resourceType: z.string().optional(),
  resourceId: z.uuid().optional(),
})
export type CreateNotificationRequest = z.infer<typeof CreateNotificationRequestSchema>;
