import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const CreateNotificationRequestSchema = z.object({
  recipientId: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  subject: z.string(),
  body: z.string(),
  resourceType: z.string().optional(),
  resourceId: z
    .string()
    .uuid()
    .optional()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
})
export type CreateNotificationRequest = z.infer<typeof CreateNotificationRequestSchema>;
