import { z } from "zod";
import { PageRequestSchema } from "../shared/PageRequest.js";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const ListNotificationsRequestSchema = z.object({
  recipientId: z.uuid(),
  unreadOnly: z.boolean(),
  page: PageRequestSchema,
})
export type ListNotificationsRequest = z.infer<typeof ListNotificationsRequestSchema>;
