import { z } from "zod";
import { NotificationViewSchema } from "./NotificationView.js";
import { PageInfoSchema } from "../shared/PageInfo.js";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const ListNotificationsResponseSchema = z.object({
  notifications: z.array(NotificationViewSchema),
  page: PageInfoSchema,
})
export type ListNotificationsResponse = z.infer<typeof ListNotificationsResponseSchema>;
