import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const MarkNotificationReadRequestSchema = z.object({
  notificationId: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  recipientId: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
})
export type MarkNotificationReadRequest = z.infer<typeof MarkNotificationReadRequestSchema>;
