import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const MarkNotificationReadRequestSchema = z.object({
  notificationId: z.uuid(),
  recipientId: z.uuid(),
})
export type MarkNotificationReadRequest = z.infer<typeof MarkNotificationReadRequestSchema>;
