import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const NotificationStreamRequestSchema = z.object({
  recipientId: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
})
export type NotificationStreamRequest = z.infer<typeof NotificationStreamRequestSchema>;
