import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const NotificationViewSchema = z.object({
  id: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  recipientId: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  subject: z.string(),
  body: z.string(),
  state: z.union([z.literal(0), z.literal(1), z.literal(2), z.literal(3)]),
  resourceType: z.string().optional(),
  resourceId: z
    .string()
    .uuid()
    .optional()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  readAtIso: z.string().optional(),
})
export type NotificationView = z.infer<typeof NotificationViewSchema>;
