# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from typing import TYPE_CHECKING

from sqlalchemy import UniqueConstraint
from sqlmodel import Field, Relationship, SQLModel
from ...shared.world_owned import WorldOwned


if TYPE_CHECKING:
    from ...worlds.world import World


class Tag(WorldOwned, table=True):
    """Tag used to classify and filter content pool entries. The (world_id, name) pair is unique per world."""

    __tablename__ = "tags"  # type: ignore
    __table_args__ = (
        UniqueConstraint("world_id", "name", name="tags_world_id_name_unique"),
    )

    # Tag name - unique within a world.
    name: str = Field(
        max_length=100,
        sa_column_kwargs={
            "nullable": False,
            "comment": "Tag name - unique within a world.",
        },
    )
    # Category used to group related tags.
    category: str = Field(
        index=True,
        max_length=50,
        sa_column_kwargs={
            "nullable": False,
            "comment": "Category used to group related tags.",
        },
    )

    # ─── Relationships ─────────────────────
    world: World | None = Relationship()
