// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
	"github.com/google/uuid"

	entschema "entgo.io/ent/schema"
)


// VaultSpace Top-level vault owned by one account.
type VaultSpace struct {
	ent.Schema
}

func (VaultSpace) Annotations() []entschema.Annotation {
	return []entschema.Annotation{
		entsql.Annotation{Table: "vault_spaces"},
		entsql.WithComments(true),
	}
}

func (VaultSpace) Mixin() []ent.Mixin {
	return []ent.Mixin{
		SoftDeletableEntity{},
	}
}

func (VaultSpace) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("owner_id", uuid.UUID{}),
		field.String("name").
			MaxLen(120),
		field.Int64("quota_bytes"),
		field.Int64("used_bytes").
			Default(0),
	}
}

func (VaultSpace) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("owner", UserAccount.Type).
			Field("owner_id").
			Unique().
			Required().
			Annotations(entsql.OnDelete(entsql.Cascade)),
	}
}

func (VaultSpace) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("owner_id"),
	}
}
