// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

// Package models contains generated GORM models.
package models

import (
	"gorm.io/gorm"

	"github.com/demo-user/demo/models"
)

// Init initializes all models with GORM.
// Returns a slice of all registered models for auto-migration.
func Init(db *gorm.DB) error {
	return db.AutoMigrate(
		&models.AuditLog{},
		&models.GameEvent{},
		&models.Invitation{},
		&models.Location{},
		&models.Npc{},
		&models.StoryNode{},
		&models.Subscription{},
		&models.Tag{},
		&models.User{},
		&models.World{},
	)
}
