# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from typing import Any, TYPE_CHECKING

from sqlalchemy import Column, Index, Text
from sqlalchemy.dialects.postgresql import JSONB
from sqlmodel import Field, Relationship, SQLModel
from ...shared.world_owned import WorldOwned


if TYPE_CHECKING:
    from ...worlds.world import World


class Npc(WorldOwned, table=True):
    """Non-player character belonging to a world."""

    __tablename__ = "npcs"  # type: ignore
    __table_args__ = (Index("npcs_world_id_name_idx", "world_id", "name"),)

    # Name of the NPC - indexed for lookup.
    name: str = Field(
        index=True,
        max_length=200,
        sa_column_kwargs={
            "nullable": False,
            "comment": "Name of the NPC - indexed for lookup.",
        },
    )
    # Narrative description used in AI generation.
    description: str = Field(
        sa_column=Column(
            Text, nullable=False, comment="Narrative description used in AI generation."
        )
    )
    # Optional structured traits used during prompt assembly.
    traits: dict[str, Any] | None = Field(
        default=None,
        sa_column=Column(
            JSONB, comment="Optional structured traits used during prompt assembly."
        ),
    )

    # ─── Relationships ─────────────────────
    world: World | None = Relationship()
