// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package notifications

import (
	"github.com/google/uuid"
)

// CreateNotificationRequest CreateNotificationRequest
type CreateNotificationRequest struct {
	RecipientID uuid.UUID `validate:"required" json:"recipientId"`
	Subject string `validate:"required" json:"subject"`
	Body string `validate:"required" json:"body"`
	ResourceType *string `validate:"omitempty" json:"resourceType,omitempty"`
	ResourceID *uuid.UUID `validate:"omitempty" json:"resourceId,omitempty"`
}
