// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package notifications

import (
	file_vault_shared "github.com/example/file-vault/notifications-svc/file_vault/shared"
)

// ListNotificationsResponse ListNotificationsResponse
type ListNotificationsResponse struct {
	Notifications []NotificationView `json:"notifications"`
	Page file_vault_shared.PageInfo `json:"page"`
}
