// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package notifications

import (
	"github.com/google/uuid"
)

// NotificationStreamRequest NotificationStreamRequest
type NotificationStreamRequest struct {
	RecipientID uuid.UUID `validate:"required" json:"recipientId"`
}
