import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const StrongPasswordSchema = z
  .string()
  .min(8)
  .max(128)
  .regex(new RegExp("^(?=.*[A-Z])(?=.*[0-9]).*$"))
  .brand("StrongPassword")
