// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package worlds

// GetWorldRequest GetWorldRequest
type GetWorldRequest struct {
	Slug string `validate:"required" json:"slug"`
}
