import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const CommitFileVersionRequestSchema = z.object({
  fileId: z.uuid(),
  storageObjectId: z.uuid(),
  sizeBytes: z.string().regex(/^-?\d+$/),
  sha256: z.string(),
  actorId: z.uuid(),
})
export type CommitFileVersionRequest = z.infer<typeof CommitFileVersionRequestSchema>;
