import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const CreateFileDraftRequestSchema = z.object({
  vaultId: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  parentId: z
    .string()
    .uuid()
    .optional()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  name: z.string(),
  mediaType: z.string(),
  expectedSizeBytes: z.bigint(),
  actorId: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
})
export type CreateFileDraftRequest = z.infer<typeof CreateFileDraftRequestSchema>;
