import { z } from "zod";
import { FileViewSchema } from "./FileView.js";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const CreateFileDraftResponseSchema = z.object({
  file: FileViewSchema,
  uploadIntentId: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
})
export type CreateFileDraftResponse = z.infer<typeof CreateFileDraftResponseSchema>;
