import { z } from "zod";
import { NodeViewSchema } from "./NodeView.js";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const FileViewSchema = z.object({
  node: NodeViewSchema,
  category: z.union([
    z.literal(0),
    z.literal(1),
    z.literal(2),
    z.literal(3),
    z.literal(4),
    z.literal(5)
  ]),
  mediaType: z.string(),
  extension: z.string().optional(),
  sizeBytes: z.string().regex(/^-?\d+$/),
  sha256: z.string(),
  currentVersionId: z.uuid().optional(),
  labels: z.array(z.string()),
})
export type FileView = z.infer<typeof FileViewSchema>;
