import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const FileVersionViewSchema = z.object({
  id: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  fileId: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  versionNumber: z.number().int(),
  storageObjectId: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  sizeBytes: z.bigint(),
  sha256: z.string(),
  createdAtIso: z.string(),
})
export type FileVersionView = z.infer<typeof FileVersionViewSchema>;
