import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const GetNodeRequestSchema = z.object({
  nodeId: z.uuid(),
  requesterId: z.uuid(),
})
export type GetNodeRequest = z.infer<typeof GetNodeRequestSchema>;
