import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const GetNodeRequestSchema = z.object({
  nodeId: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  requesterId: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
})
export type GetNodeRequest = z.infer<typeof GetNodeRequestSchema>;
