import { z } from "zod";
import { PageRequestSchema } from "../shared/PageRequest.js";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const ListFolderRequestSchema = z.object({
  folderId: z.uuid(),
  requesterId: z.uuid(),
  page: PageRequestSchema,
})
export type ListFolderRequest = z.infer<typeof ListFolderRequestSchema>;
