import { z } from "zod";
import { NodeViewSchema } from "./NodeView.js";
import { PageInfoSchema } from "../shared/PageInfo.js";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const ListFolderResponseSchema = z.object({
  nodes: z.array(NodeViewSchema),
  page: PageInfoSchema,
})
export type ListFolderResponse = z.infer<typeof ListFolderResponseSchema>;
