import { z } from "zod";
import { PageRequestSchema } from "../shared/PageRequest.js";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const ListFolderRequestSchema = z.object({
  folderId: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  requesterId: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  page: PageRequestSchema,
})
export type ListFolderRequest = z.infer<typeof ListFolderRequestSchema>;
