import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const MoveNodeRequestSchema = z.object({
  nodeId: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  newParentId: z
    .string()
    .uuid()
    .optional()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  actorId: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
})
export type MoveNodeRequest = z.infer<typeof MoveNodeRequestSchema>;
