import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const MoveNodeRequestSchema = z.object({
  nodeId: z.uuid(),
  newParentId: z.uuid().optional(),
  actorId: z.uuid(),
})
export type MoveNodeRequest = z.infer<typeof MoveNodeRequestSchema>;
