import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const NodeViewSchema = z.object({
  id: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  vaultId: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  parentId: z
    .string()
    .uuid()
    .optional()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  kind: z.union([z.literal(0), z.literal(1), z.literal(2)]),
  name: z.string(),
  path: z.string(),
  state: z.union([z.literal(0), z.literal(1), z.literal(2), z.literal(3)]),
  visibility: z.union([z.literal(0), z.literal(1), z.literal(2), z.literal(3)]),
})
export type NodeView = z.infer<typeof NodeViewSchema>;
