import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const RenameNodeRequestSchema = z.object({
  nodeId: z.uuid(),
  name: z.string(),
  actorId: z.uuid(),
})
export type RenameNodeRequest = z.infer<typeof RenameNodeRequestSchema>;
