import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const RenameNodeRequestSchema = z.object({
  nodeId: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  name: z.string(),
  actorId: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
})
export type RenameNodeRequest = z.infer<typeof RenameNodeRequestSchema>;
