import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const TrashNodeRequestSchema = z.object({
  nodeId: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  actorId: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
})
export type TrashNodeRequest = z.infer<typeof TrashNodeRequestSchema>;
