import { z } from "zod";
import { ActorRefSchema } from "../shared/ActorRef.js";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const VaultViewSchema = z.object({
  id: z.uuid(),
  owner: ActorRefSchema,
  name: z.string(),
  quotaBytes: z.string().regex(/^-?\d+$/),
  usedBytes: z.string().regex(/^-?\d+$/),
})
export type VaultView = z.infer<typeof VaultViewSchema>;
