import { z } from "zod";
import { ActorRefSchema } from "../shared/ActorRef.js";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const VaultViewSchema = z.object({
  id: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  owner: ActorRefSchema,
  name: z.string(),
  quotaBytes: z.bigint(),
  usedBytes: z.bigint(),
})
export type VaultView = z.infer<typeof VaultViewSchema>;
