// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package shared

// PageInfo PageInfo
type PageInfo struct {
	NextPageToken *string `validate:"omitempty" json:"nextPageToken,omitempty"`
	TotalCount *uint64 `validate:"omitempty" json:"totalCount,omitempty"`
}
