import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const BeginUploadResponseSchema = z.object({
  uploadSessionId: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  storageObjectId: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  signedUploadUrl: z.string().optional(),
  expiresAtIso: z.string(),
})
export type BeginUploadResponse = z.infer<typeof BeginUploadResponseSchema>;
