import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const BeginUploadRequestSchema = z.object({
  accountId: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  fileName: z.string(),
  mediaType: z.string(),
  expectedSizeBytes: z.bigint(),
  expectedSha256: z.string().optional(),
})
export type BeginUploadRequest = z.infer<typeof BeginUploadRequestSchema>;
