import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const BeginUploadRequestSchema = z.object({
  accountId: z.uuid(),
  fileName: z.string(),
  mediaType: z.string(),
  expectedSizeBytes: z.string().regex(/^-?\d+$/),
  expectedSha256: z.string().optional(),
})
export type BeginUploadRequest = z.infer<typeof BeginUploadRequestSchema>;
