import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const CompleteUploadRequestSchema = z.object({
  uploadSessionId: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  sha256: z.string(),
  sizeBytes: z.bigint(),
})
export type CompleteUploadRequest = z.infer<typeof CompleteUploadRequestSchema>;
