import { z } from "zod";
import { StorageObjectViewSchema } from "./StorageObjectView.js";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const CompleteUploadResponseSchema = z.object({
  object: StorageObjectViewSchema,
})
export type CompleteUploadResponse = z.infer<typeof CompleteUploadResponseSchema>;
