import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const CompleteUploadRequestSchema = z.object({
  uploadSessionId: z.uuid(),
  sha256: z.string(),
  sizeBytes: z.string().regex(/^-?\d+$/),
})
export type CompleteUploadRequest = z.infer<typeof CompleteUploadRequestSchema>;
