import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const GetDownloadUrlRequestSchema = z.object({
  storageObjectId: z.uuid(),
  requesterId: z.uuid(),
  expiresInSeconds: z.number().int(),
})
export type GetDownloadUrlRequest = z.infer<typeof GetDownloadUrlRequestSchema>;
