import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const GetDownloadUrlResponseSchema = z.object({
  storageObjectId: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  signedDownloadUrl: z.string(),
  expiresAtIso: z.string(),
})
export type GetDownloadUrlResponse = z.infer<typeof GetDownloadUrlResponseSchema>;
