import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const GetDownloadUrlRequestSchema = z.object({
  storageObjectId: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  requesterId: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  expiresInSeconds: z.number().int(),
})
export type GetDownloadUrlRequest = z.infer<typeof GetDownloadUrlRequestSchema>;
