import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const StorageObjectViewSchema = z.object({
  id: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  bucket: z.string(),
  objectKey: z.string(),
  sizeBytes: z.bigint(),
  sha256: z.string(),
  mediaType: z.string(),
  state: z.union([
    z.literal(0),
    z.literal(1),
    z.literal(2),
    z.literal(3),
    z.literal(4)
  ]),
})
export type StorageObjectView = z.infer<typeof StorageObjectViewSchema>;
