import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const UploadReceiptSchema = z.object({
  uploadSessionId: z.uuid(),
  bytesReceived: z.string().regex(/^-?\d+$/),
  partCount: z.number().int(),
})
export type UploadReceipt = z.infer<typeof UploadReceiptSchema>;
