import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const UploadChunkSchema = z.object({
  uploadSessionId: z.uuid(),
  partNumber: z.number().int(),
  offsetBytes: z.string().regex(/^-?\d+$/),
  data: z.instanceof(Uint8Array),
  finalChunk: z.boolean(),
})
export type UploadChunk = z.infer<typeof UploadChunkSchema>;
