import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const UploadReceiptSchema = z.object({
  uploadSessionId: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  bytesReceived: z.bigint(),
  partCount: z.number().int(),
})
export type UploadReceipt = z.infer<typeof UploadReceiptSchema>;
