import { z } from "zod";

// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
export const UploadChunkSchema = z.object({
  uploadSessionId: z
    .string()
    .uuid()
    .describe("UUID type - maps to uuid column in PostgreSQL"),
  partNumber: z.number().int(),
  offsetBytes: z.bigint(),
  data: z.instanceof(Uint8Array),
  finalChunk: z.boolean(),
})
export type UploadChunk = z.infer<typeof UploadChunkSchema>;
