// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package storage

// StorageObjectStateCode represents the storage_object_state_code enum.
type StorageObjectStateCode int32

const (
	StorageObjectStateCodeUnspecified StorageObjectStateCode = 0
	StorageObjectStateCodePending     StorageObjectStateCode = 1
	StorageObjectStateCodeAvailable   StorageObjectStateCode = 2
	StorageObjectStateCodeQuarantined StorageObjectStateCode = 3
	StorageObjectStateCodeDeleted     StorageObjectStateCode = 4
)
