// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package storage

import (
	"github.com/google/uuid"
)

// UploadChunk UploadChunk
type UploadChunk struct {
	UploadSessionID uuid.UUID `validate:"required" json:"uploadSessionId"`
	PartNumber      int32     `validate:"required" json:"partNumber"`
	OffsetBytes     int64     `validate:"required" json:"offsetBytes"`
	Data            []byte    `validate:"required" json:"data"`
	FinalChunk      bool      `json:"finalChunk"`
}
