// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package storage

import (
	"github.com/google/uuid"
)

// BeginUploadRequest BeginUploadRequest
type BeginUploadRequest struct {
	AccountID uuid.UUID `validate:"required" json:"accountId"`
	FileName string `validate:"required" json:"fileName"`
	MediaType string `validate:"required" json:"mediaType"`
	ExpectedSizeBytes int64 `validate:"required" json:"expectedSizeBytes"`
	ExpectedSha256 *string `validate:"omitempty" json:"expectedSha256,omitempty"`
}
