// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package storage

import (
	"github.com/google/uuid"
)

// CompleteUploadRequest CompleteUploadRequest
type CompleteUploadRequest struct {
	UploadSessionID uuid.UUID `validate:"required" json:"uploadSessionId"`
	Sha256 string `validate:"required" json:"sha256"`
	SizeBytes int64 `validate:"required" json:"sizeBytes"`
}
