# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
from typing import Annotated

from pydantic import Field


DisplayName = Annotated[str, Field(max_length=255, min_length=1)]
PageSize = Annotated[int, Field(ge=1, le=100)]
SearchQuery = Annotated[str, Field(max_length=512, min_length=1)]
StrongPassword = Annotated[
    str, Field(max_length=128, min_length=8, pattern="^(?=.*[A-Z])(?=.*[0-9]).*$")
]
