# Code generated by @qninhdt/typespec-sqlmodel. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from uuid import UUID
from typing import Any
from datetime import datetime

from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy import Column, DateTime, Index, func
from sqlmodel import Field, Relationship, SQLModel


class AuditLog(SQLModel, table=True):
    """Immutable audit-log entry.  Uses an auto-incrementing bigserial surrogate key so entries can be ordered and paginated efficiently without UUIDs. Demonstrates:"""

    __tablename__ = "audit_logs"
    __table_args__ = (
        Index("audit_logs_entity_type_entity_id_idx", "entity_type", "entity_id"),
        Index("audit_logs_actor_id_created_at_idx", "actor_id", "created_at"),
    )

    # Auto-incrementing surrogate key - uses bigserial (64-bit) for high throughput Note: Does NOT use base id - overrides with bigserial for performance
    id: int = Field(
        primary_key=True,
        sa_column_kwargs={
            "comment": "Auto-incrementing surrogate key - uses bigserial (64-bit) for high throughput Note: Does NOT use base id - overrides with bigserial for performance"
        },
    )
    # Logical type of the changed entity, e.g. "World" or "StoryNode"
    entity_type: str = Field(
        index=True,
        max_length=100,
        sa_column_kwargs={
            "nullable": False,
            "comment": 'Logical type of the changed entity, e.g. "World" or "StoryNode"',
        },
    )
    # Primary key of the changed entity
    entity_id: UUID = Field(
        sa_column_kwargs={
            "nullable": False,
            "comment": "Primary key of the changed entity",
        }
    )
    # Action performed: "create", "update", or "delete"
    action: str = Field(
        max_length=50,
        sa_column_kwargs={
            "nullable": False,
            "comment": 'Action performed: "create", "update", or "delete"',
        },
    )
    # JSON patch or before/after snapshot
    diff: dict[str, Any] | None = Field(
        default=None,
        sa_column=Column(JSONB, comment="JSON patch or before/after snapshot"),
    )
    # Foreign key to Actor (User) - nullable for deleted users
    actor_id: UUID | None = Field(
        default=None,
        foreign_key="users.id",
        sa_column_kwargs={
            "comment": "Foreign key to Actor (User) - nullable for deleted users"
        },
    )
    created_at: datetime = Field(
        sa_column=Column(
            DateTime(timezone=True), nullable=False, server_default=func.now()
        )
    )

    # ─── Relationships ─────────────────────
    # User who performed the action - SET NULL when the user is deleted so audit history is preserved even after account removal
    actor: "User" | None = Relationship()
