# Code generated by @qninhdt/typespec-sqlmodel. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from uuid import UUID
from typing import Any
from datetime import datetime

from sqlalchemy import Column, DateTime, ForeignKey, Index, func
from sqlalchemy.dialects.postgresql import JSONB
from sqlmodel import Field, Relationship, SQLModel


class AuditLog(SQLModel, table=True):
    """Immutable audit-log entry.  Uses an auto-incrementing bigserial surrogate key so entries can be ordered and paginated efficiently without UUIDs. Demonstrates:"""

    __tablename__ = "audit_logs"
    __table_args__ = (
        Index("idx_audit_actor_time", "actor_id", "created_at"),
        Index("idx_audit_entity", "entity_type", "entity_id"),
    )

    # User who performed the action - SET NULL when the user is deleted so audit history is preserved even after account removal
    user_id: UUID | None = Field(default=None, sa_column=Column(ForeignKey("users.id", ondelete="SET NULL", onupdate="CASCADE"), comment="User who performed the action - SET NULL when the user is deleted so audit history is preserved even after account removal", index=True))
    # Auto-incrementing surrogate key - uses bigserial (64-bit) for high throughput Note: Does NOT use base id - overrides with bigserial for performance
    id: int = Field(primary_key=True, sa_column_kwargs={"comment": "Auto-incrementing surrogate key - uses bigserial (64-bit) for high throughput Note: Does NOT use base id - overrides with bigserial for performance"})
    # Logical type of the changed entity, e.g. "World" or "StoryNode"
    entity_type: str = Field(index=True, max_length=100, sa_column_kwargs={"nullable": False, "comment": "Logical type of the changed entity, e.g. \"World\" or \"StoryNode\""})
    # Primary key of the changed entity
    entity_id: UUID = Field(sa_column_kwargs={"nullable": False, "comment": "Primary key of the changed entity"})
    # Action performed: "create", "update", or "delete"
    action: str = Field(max_length=50, sa_column_kwargs={"nullable": False, "comment": "Action performed: \"create\", \"update\", or \"delete\""})
    # JSON patch or before/after snapshot
    diff: dict[str, Any] | None = Field(default=None, sa_column=Column(JSONB, comment="JSON patch or before/after snapshot"))
    created_at: datetime = Field(sa_column=Column(DateTime(timezone=True), nullable=False, server_default=func.now()))

    # ─── Relationships ─────────────────────
    # User who performed the action - SET NULL when the user is deleted so audit history is preserved even after account removal
    actor: "User" | None = Relationship()
