# Code generated by @qninhdt/typespec-sqlmodel. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from uuid import UUID
from typing import Optional

from pydantic import AnyUrl, BaseModel, EmailStr, Field


class PublicUser(BaseModel):
    """Public user record with sensitive / internal columns removed. Omits password hash, soft-delete, audit timestamps, and relationships."""

    # Unique identifier - use
    id: UUID = Field(..., description="Unique identifier - use")
    # Email address used for login - indexed for fast lookup. Constrained to max 320 characters with @format("email") validation.
    email: EmailStr = Field(..., max_length=320, description="Email address used for login - indexed for fast lookup. Constrained to max 320 characters with @format(\"email\") validation.")
    # Display name shown in the UI - max 100 characters
    display_name: str = Field(..., max_length=100, description="Display name shown in the UI - max 100 characters")
    # Optional avatar image URL - must be a valid URL, max 512 characters
    avatar_url: Optional[AnyUrl] = Field(None, max_length=512, description="Optional avatar image URL - must be a valid URL, max 512 characters")
    # Credits balance - defaults to 0 on registration
    credits: int = Field(..., description="Credits balance - defaults to 0 on registration")
    # Whether the account is active - false for suspended or deactivated accounts
    is_active: bool = Field(..., description="Whether the account is active - false for suspended or deactivated accounts")
