# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from uuid import UUID

from sqlmodel import Field, SQLModel
from .timestamped import Timestamped


class WorldOwned(Timestamped):
    """Shared mixin for content that belongs to a specific world. Demonstrates mixin-to-mixin inheritance."""

    # Foreign key to the owning world.
    world_id: UUID = Field(
        index=True,
        sa_column_kwargs={
            "nullable": False,
            "comment": "Foreign key to the owning world.",
        },
    )
