# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from uuid import UUID
from enum import Enum

from pydantic import BaseModel, Field


class ShareRoleCode(int, Enum):
    """Auto-generated enum for share_role_code."""

    unspecified = 0
    viewer = 1
    commenter = 2
    editor = 3
    owner = 4


class CreateShareLinkRequest(BaseModel):
    """CreateShareLinkRequest"""

    resource_node_id: UUID = Field(...)
    created_by: UUID = Field(...)
    role: ShareRoleCode = Field(...)
    expires_at_iso: str | None = Field(None)
    password: str | None = Field(None)
