# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from pydantic import BaseModel, Field
from ..shared.page_info import PageInfo
from .share_grant_view import ShareGrantView
from .share_link_view import ShareLinkView


class ListSharesResponse(BaseModel):
    """ListSharesResponse"""

    grants: list[ShareGrantView] = Field(...)
    links: list[ShareLinkView] = Field(...)
    page: PageInfo = Field(...)
