# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from typing import TYPE_CHECKING
from uuid import UUID
from datetime import datetime
from enum import Enum

from sqlalchemy import Column, DateTime, Enum as SAEnum, ForeignKey
from sqlmodel import Field, Relationship, SQLModel
from ..shared.entity import Entity


if TYPE_CHECKING:
    from ..identity.user_account import UserAccount
    from ..metadata.vault_node import VaultNode


class ShareSubjectKind(str, Enum):
    """Auto-generated enum for share_subject_kind."""

    account = "account"
    email = "email"
    organization = "organization"


class ShareRole(str, Enum):
    """Auto-generated enum for share_role."""

    viewer = "viewer"
    commenter = "commenter"
    editor = "editor"


class ShareGrant(Entity, table=True):
    """Direct grant from an owner to another principal."""

    __tablename__ = "share_grants"  # type: ignore

    resource_node_id: UUID = Field(
        sa_column=Column(
            ForeignKey("vault_nodes.id", ondelete="CASCADE"), nullable=False, index=True
        )
    )
    granted_by: UUID = Field(
        index=True, foreign_key="user_accounts.id", sa_column_kwargs={"nullable": False}
    )
    subject_kind: ShareSubjectKind = Field(
        sa_column=Column(SAEnum(ShareSubjectKind), nullable=False)
    )
    subject: str = Field(max_length=320, sa_column_kwargs={"nullable": False})
    role: ShareRole = Field(sa_column=Column(SAEnum(ShareRole), nullable=False))
    expires_at: datetime | None = Field(
        default=None, sa_column=Column(DateTime(timezone=True))
    )
    revoked_at: datetime | None = Field(
        default=None, sa_column=Column(DateTime(timezone=True))
    )

    # ─── Relationships ─────────────────────
    resource: VaultNode | None = Relationship()
    grantor: UserAccount | None = Relationship()
