# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from typing import TYPE_CHECKING
from uuid import UUID

from sqlalchemy import Column, ForeignKey, Text
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlmodel import Field, Relationship, SQLModel
from ..shared.entity import Entity


if TYPE_CHECKING:
    from ..metadata.file_metadata import FileMetadata


class ExtractedText(Entity, table=True):
    """Extracted searchable text. Large blobs may be stored externally."""

    __tablename__ = "extracted_texts"  # type: ignore

    file_id: UUID = Field(
        sa_column=Column(
            PG_UUID(as_uuid=True),
            ForeignKey("file_metadata.id", ondelete="CASCADE"),
            nullable=False,
            index=True,
            unique=True,
        )
    )
    language: str | None = Field(default=None, max_length=255)
    content: str = Field(sa_column=Column(Text, nullable=False))
    extraction_version: int = Field(
        sa_column_kwargs={"nullable": False, "server_default": "1"}
    )

    # ─── Relationships ─────────────────────
    file: FileMetadata | None = Relationship()
