# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from pydantic import BaseModel, Field
from ..shared.page_info import PageInfo
from .processing_job_view import ProcessingJobView


class ListProcessingJobsResponse(BaseModel):
    """ListProcessingJobsResponse"""

    jobs: list[ProcessingJobView] = Field(...)
    page: PageInfo = Field(...)
