# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from uuid import UUID
from enum import Enum

from pydantic import BaseModel, Field


class ProcessingKindCode(int, Enum):
    """Auto-generated enum for processing_kind_code."""

    unspecified = 0
    classify_file = 1
    extract_text = 2
    generate_summary = 3
    generate_preview = 4
    embed_content = 5


class ProcessingStatusCode(int, Enum):
    """Auto-generated enum for processing_status_code."""

    unspecified = 0
    queued = 1
    running = 2
    completed = 3
    failed = 4
    canceled = 5


class ProcessingJobView(BaseModel):
    """ProcessingJobView"""

    id: UUID = Field(...)
    file_id: UUID = Field(...)
    version_id: UUID | None = Field(None)
    kind: ProcessingKindCode = Field(...)
    status: ProcessingStatusCode = Field(...)
    started_at_iso: str | None = Field(None)
    finished_at_iso: str | None = Field(None)
    error_message: str | None = Field(None)
