// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package places

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/datatypes"
	"gorm.io/gorm"

	demo_game_platform_worlds "github.com/demo-user/demo/demo/game_platform/worlds"
)

// Location Physical or virtual location available inside a world.
type Location struct {
	// Unique identifier shared by most persisted records.
	ID uuid.UUID `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid();comment:Unique identifier shared by most persisted records." json:"id"`
	// Timestamp when the record was created.
	CreatedAt time.Time `gorm:"column:created_at;type:timestamptz;autoCreateTime;not null;comment:Timestamp when the record was created." json:"createdAt"`
	// Timestamp of the last update.
	UpdatedAt *time.Time `gorm:"column:updated_at;type:timestamptz;comment:Timestamp of the last update." validate:"omitempty" json:"updatedAt,omitempty"`
	// Soft delete marker for archival workflows.
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;index;comment:Soft delete marker for archival workflows." json:"deletedAt"`
	// Foreign key to the owning world.
	WorldID uuid.UUID `gorm:"column:world_id;type:uuid;not null;index:locations_world_id_idx;comment:Foreign key to the owning world." validate:"required" json:"worldId"`
	// Name of the location - indexed for lookup.
	Name string `gorm:"column:name;type:varchar(200);not null;index:locations_name_idx;comment:Name of the location - indexed for lookup." validate:"required,max=200" json:"name"`
	// Narrative description used in AI generation.
	Description string `gorm:"column:description;type:text;not null;comment:Narrative description used in AI generation." validate:"required" json:"description"`
	// Bounding box or point stored as GeoJSON.
	Coordinates *datatypes.JSON `gorm:"column:coordinates;type:jsonb;comment:Bounding box or point stored as GeoJSON." validate:"omitempty" json:"coordinates,omitempty"`

	// ─── Relationships ─────────────────────
	World demo_game_platform_worlds.World `gorm:"foreignKey:WorldID;references:ID;constraint:OnDelete:CASCADE,OnUpdate:CASCADE" json:"world"`
}

// TableName returns the table name for Location.
func (Location) TableName() string {
	return "locations"
}
