// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package models

// CreateInvitationForm Form payload for creating an invitation. Uses `@data` instead of `@table` - no DB schema is generated.  `::type` rule for decorators that require a `Scalar` target (e.g. `@inputType`): - Direct-scalar field  (`message?: text`)  → `@@dec(Form.message::type, ...)` `::type` resolves to the `text` scalar directly. ✓ - Lookup-typed field (`worldPrompt: World.prompt`) → `Form.worldPrompt::type` resolves to the source `ModelProperty` (`World.prompt`), NOT the scalar. Go one level deeper via the source property: `@@dec(World.prompt::type, ...)`. ✓
type CreateInvitationForm struct {
	// Email address of the person being invited. Lookup type: inherits @maxLength(320) and @format("email") from User.email. @title and @placeholder target ModelProperty - apply inline as normal.
	InviteeEmail string `validate:"required,max=320,email" json:"inviteeEmail" form:"inviteeEmail,title=Invitee Email,placeholder=friend@example.com"`
	// Name of the world to invite into. Lookup type: inherits @maxLength(200) from World.name.
	WorldName string `validate:"required,max=200" json:"worldName" form:"worldName,title=World Name,placeholder=Select or type a world name"`
	// Prompt text for the target world. Lookup type whose source scalar is `text` (custom, not a built-in) - used below to demonstrate `@@inputType` via `World.prompt::type`.
	WorldPrompt string `validate:"required" json:"worldPrompt" form:"worldPrompt,title=World Prompt"`
	// Optional personal message included in the invitation. Direct custom scalar (`text`) - @inputType applied via `::type` below.
	Message *string `validate:"omitempty" json:"message,omitempty" form:"message,title=Personal Message,placeholder=Write a short note to your invitee…"`
}
