// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

// User Registered user account
type User struct {
	// Unique identifier - use
	ID uuid.UUID `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid();comment:Unique identifier - use" json:"id"`
	// Timestamp when the record was created
	CreatedAt time.Time `gorm:"column:created_at;type:timestamptz;autoCreateTime;not null;comment:Timestamp when the record was created" json:"createdAt"`
	// Timestamp of the last update - omit in extending model to skip
	UpdatedAt *time.Time `gorm:"column:updated_at;type:timestamptz;comment:Timestamp of the last update - omit in extending model to skip" validate:"omitempty" json:"updatedAt,omitempty"`
	// Soft delete timestamp - null if active, set to deletion time when "deleted".
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;index;uniqueIndex:users_email_deleted_at_unique,priority:2;comment:Soft delete timestamp - null if active, set to deletion time when 'deleted'." json:"deletedAt"`
	// Email address used for login - indexed for fast lookup. Constrained to max 320 characters with @format("email") validation.
	Email string `gorm:"column:email;type:varchar(320);not null;uniqueIndex:users_email_deleted_at_unique,priority:1;comment:Email address used for login - indexed for fast lookup. Constrained to max 320 characters with @format('email') validation." validate:"required,max=320,email" json:"email"`
	// Hashed password - never store or return plain text
	PasswordHash string `gorm:"column:password_hash;type:varchar(255);not null;comment:Hashed password - never store or return plain text" validate:"required" json:"passwordHash"`
	// Display name shown in the UI - max 100 characters
	DisplayName string `gorm:"column:display_name;type:varchar(100);not null;comment:Display name shown in the UI - max 100 characters" validate:"required,max=100" json:"displayName"`
	// Optional avatar image URL - must be a valid URL, max 512 characters
	AvatarURL *string `gorm:"column:avatar_url;type:varchar(512);comment:Optional avatar image URL - must be a valid URL, max 512 characters" validate:"omitempty,max=512,url" json:"avatarUrl,omitempty"`
	// Credits balance - defaults to 0 on registration
	Credits int32 `gorm:"column:credits;type:integer;not null;default:0;comment:Credits balance - defaults to 0 on registration" validate:"required" json:"credits"`
	// Whether the account is active - false for suspended or deactivated accounts
	IsActive bool `gorm:"column:is_active;type:boolean;not null;default:true;comment:Whether the account is active - false for suspended or deactivated accounts" json:"isActive"`
	// Virtual field combining display name and email - not persisted to the database. Decorated with @ignore so emitters skip it.
	FullTitle *string `gorm:"-" json:"fullTitle,omitempty"`

	// ─── Relationships ─────────────────────
	// Subscription plans associated with this user
	Subscriptions []Subscription `gorm:"foreignKey:UserID;constraint:OnDelete:CASCADE,OnUpdate:CASCADE" json:"subscriptions,omitempty"` // Worlds owned by this user
	Worlds        []World        `gorm:"foreignKey:OwnerID;constraint:OnDelete:CASCADE,OnUpdate:CASCADE" json:"worlds,omitempty"`
}

// TableName returns the table name for User.
func (User) TableName() string {
	return "users"
}
