# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from uuid import UUID

from pydantic import BaseModel, Field


class CreateNotificationRequest(BaseModel):
    """CreateNotificationRequest"""

    recipient_id: UUID = Field(...)
    subject: str = Field(...)
    body: str = Field(...)
    resource_type: str | None = Field(None)
    resource_id: UUID | None = Field(None)
