# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from pydantic import BaseModel, Field
from .notification_view import NotificationView
from ..shared.page_info import PageInfo


class ListNotificationsResponse(BaseModel):
    """ListNotificationsResponse"""

    notifications: list[NotificationView] = Field(...)
    page: PageInfo = Field(...)
