# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from uuid import UUID

from pydantic import BaseModel, Field


class MarkNotificationReadRequest(BaseModel):
    """MarkNotificationReadRequest"""

    notification_id: UUID = Field(...)
    recipient_id: UUID = Field(...)
