# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from typing import Any, TYPE_CHECKING
from uuid import UUID
from enum import Enum

from sqlalchemy import Column, Enum as SAEnum, ForeignKey, UniqueConstraint
from sqlalchemy.dialects.postgresql import JSONB
from sqlmodel import Field, Relationship, SQLModel
from ..shared.entity import Entity


if TYPE_CHECKING:
    from ..identity.user_account import UserAccount


class NotificationChannel(str, Enum):
    """Auto-generated enum for notification_channel."""

    in_app = "in_app"
    email = "email"
    webhook = "webhook"


class NotificationPreference(Entity, table=True):
    """User preference per notification channel."""

    __tablename__ = "notification_preferences"  # type: ignore
    __table_args__ = (
        UniqueConstraint(
            "account_id",
            "channel",
            name="notification_preferences_account_id_channel_unique",
        ),
    )

    account_id: UUID = Field(
        sa_column=Column(
            ForeignKey("user_accounts.id", ondelete="CASCADE"),
            nullable=False,
            index=True,
        )
    )
    channel: NotificationChannel = Field(
        sa_column=Column(SAEnum(NotificationChannel), nullable=False)
    )
    enabled: bool = Field(
        sa_column_kwargs={"nullable": False, "server_default": "true"}
    )
    quiet_hours_json: dict[str, Any] | None = Field(
        default=None, sa_column=Column(JSONB)
    )

    # ─── Relationships ─────────────────────
    account: UserAccount | None = Relationship()
