# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from typing import TYPE_CHECKING
from uuid import UUID
from datetime import datetime

from sqlalchemy import Column, DateTime, ForeignKey, Text
from sqlmodel import Field, Relationship, SQLModel
from ..shared.entity import Entity


if TYPE_CHECKING:
    from ..identity.user_account import UserAccount


class Notification(Entity, table=True):
    """Notification visible in the product."""

    __tablename__ = "notifications"  # type: ignore

    recipient_id: UUID = Field(
        sa_column=Column(
            ForeignKey("user_accounts.id", ondelete="CASCADE"),
            nullable=False,
            index=True,
        )
    )
    subject: str = Field(max_length=160, sa_column_kwargs={"nullable": False})
    body: str = Field(sa_column=Column(Text, nullable=False))
    resource_type: str | None = Field(default=None, max_length=255)
    resource_id: UUID | None = Field(default=None)
    read_at: datetime | None = Field(
        default=None, sa_column=Column(DateTime(timezone=True))
    )

    # ─── Relationships ─────────────────────
    recipient: UserAccount | None = Relationship()
