# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from uuid import UUID
from enum import Enum

from pydantic import BaseModel, Field


class NotificationStateCode(int, Enum):
    """Auto-generated enum for notification_state_code."""

    unspecified = 0
    unread = 1
    read = 2
    archived = 3


class NotificationView(BaseModel):
    """NotificationView"""

    id: UUID = Field(...)
    recipient_id: UUID = Field(...)
    subject: str = Field(...)
    body: str = Field(...)
    state: NotificationStateCode = Field(...)
    resource_type: str | None = Field(None)
    resource_id: UUID | None = Field(None)
    read_at_iso: str | None = Field(None)
