# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from pydantic import BaseModel, Field
from .conversation_view import ConversationView
from .message_view import MessageView


class AssistantReply(BaseModel):
    """AssistantReply"""

    conversation: ConversationView = Field(...)
    messages: list[MessageView] = Field(...)
