# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from typing import TYPE_CHECKING
from uuid import UUID
from datetime import datetime
from enum import Enum

from sqlalchemy import Column, DateTime, Enum as SAEnum, ForeignKey, Text
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlmodel import Field, Relationship, SQLModel
from ..shared.entity import Entity


if TYPE_CHECKING:
    from .assistant_conversation import AssistantConversation
    from ..identity.user_account import UserAccount


class AssistantTaskStatus(str, Enum):
    """Auto-generated enum for assistant_task_status."""

    queued = "queued"
    running = "running"
    waiting_for_approval = "waiting_for_approval"
    completed = "completed"
    failed = "failed"
    canceled = "canceled"


class AssistantTask(Entity, table=True):
    """Durable user-requested task that may call file services internally."""

    __tablename__ = "assistant_tasks"  # type: ignore

    conversation_id: UUID = Field(
        sa_column=Column(
            PG_UUID(as_uuid=True),
            ForeignKey("assistant_conversations.id", ondelete="CASCADE"),
            nullable=False,
            index=True,
        )
    )
    requested_by: UUID = Field(
        sa_column=Column(
            PG_UUID(as_uuid=True),
            ForeignKey("user_accounts.id"),
            nullable=False,
            index=True,
        )
    )
    task_type: str = Field(max_length=120, sa_column_kwargs={"nullable": False})
    objective: str = Field(sa_column=Column(Text, nullable=False))
    status: AssistantTaskStatus = Field(
        sa_column=Column(
            SAEnum(AssistantTaskStatus), nullable=False, server_default="queued"
        )
    )
    target_node_id: UUID | None = Field(
        default=None, sa_column=Column(PG_UUID(as_uuid=True))
    )
    result_summary: str | None = Field(default=None, sa_column=Column(Text))
    started_at: datetime | None = Field(
        default=None, sa_column=Column(DateTime(timezone=True))
    )
    finished_at: datetime | None = Field(
        default=None, sa_column=Column(DateTime(timezone=True))
    )

    # ─── Relationships ─────────────────────
    conversation: AssistantConversation | None = Relationship()
    requester: UserAccount | None = Relationship()
