# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from uuid import UUID

from pydantic import BaseModel, Field
from .approval_request_view import ApprovalRequestView
from .assistant_task_view import AssistantTaskView
from .message_view import MessageView


class AssistantEvent(BaseModel):
    """AssistantEvent"""

    conversation_id: UUID = Field(...)
    task: AssistantTaskView | None = Field(None)
    message: MessageView | None = Field(None)
    approval: ApprovalRequestView | None = Field(None)
