# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from uuid import UUID
from enum import Enum

from pydantic import BaseModel, Field


class AssistantTaskStatusCode(int, Enum):
    """Auto-generated enum for assistant_task_status_code."""

    unspecified = 0
    queued = 1
    running = 2
    waiting_for_approval = 3
    completed = 4
    failed = 5
    canceled = 6


class AssistantTaskView(BaseModel):
    """AssistantTaskView"""

    id: UUID = Field(...)
    conversation_id: UUID = Field(...)
    task_type: str = Field(...)
    objective: str = Field(...)
    status: AssistantTaskStatusCode = Field(...)
    target_node_id: UUID | None = Field(None)
    result_summary: str | None = Field(None)
