# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from uuid import UUID

from pydantic import BaseModel, Field


class SendMessageRequest(BaseModel):
    """SendMessageRequest"""

    conversation_id: UUID = Field(...)
    sender_id: UUID = Field(...)
    content: str = Field(...)
