# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from uuid import UUID

from pydantic import BaseModel, Field


class StartAssistantTaskRequest(BaseModel):
    """StartAssistantTaskRequest"""

    conversation_id: UUID = Field(...)
    requested_by: UUID = Field(...)
    task_type: str = Field(...)
    objective: str = Field(...)
    target_node_id: UUID | None = Field(None)
