# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from uuid import UUID

from pydantic import BaseModel, Field


class StartConversationRequest(BaseModel):
    """StartConversationRequest"""

    owner_id: UUID = Field(...)
    title: str | None = Field(None)
    initial_message: str | None = Field(None)
