# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from pydantic import BaseModel, Field
from .assistant_event import AssistantEvent


class WatchConversationEvent(BaseModel):
    """WatchConversationEvent"""

    occurred_at_iso: str = Field(...)
    event: AssistantEvent = Field(...)
