// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package notifications

import (
	"github.com/google/uuid"

	file_vault_shared "github.com/example/file-vault/file_vault/shared"
)

// ListNotificationsRequest ListNotificationsRequest
type ListNotificationsRequest struct {
	RecipientID uuid.UUID                     `validate:"required" json:"recipientId"`
	UnreadOnly  bool                          `json:"unreadOnly"`
	Page        file_vault_shared.PageRequest `json:"page"`
}
