// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package notifications

import (
	"github.com/google/uuid"
)

// MarkNotificationReadRequest MarkNotificationReadRequest
type MarkNotificationReadRequest struct {
	NotificationID uuid.UUID `validate:"required" json:"notificationId"`
	RecipientID    uuid.UUID `validate:"required" json:"recipientId"`
}
