// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package stories

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/datatypes"
	"gorm.io/gorm"

	demo_game_platform_worlds "github.com/demo-user/demo/demo/game_platform/worlds"
)

// StoryNode Node in a lazily-generated story tree. Stores the cumulative content-pool IDs inherited from all ancestor nodes.
type StoryNode struct {
	// Unique identifier shared by most persisted records.
	ID uuid.UUID `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid();comment:Unique identifier shared by most persisted records." json:"id"`
	// Timestamp when the record was created.
	CreatedAt time.Time `gorm:"column:created_at;type:timestamptz;autoCreateTime;not null;comment:Timestamp when the record was created." json:"createdAt"`
	// Timestamp of the last update.
	UpdatedAt *time.Time `gorm:"column:updated_at;type:timestamptz;comment:Timestamp of the last update." validate:"omitempty" json:"updatedAt,omitempty"`
	// Soft delete marker for archival workflows.
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;index;comment:Soft delete marker for archival workflows." json:"deletedAt"`
	// Foreign key to the owning world.
	WorldID uuid.UUID `gorm:"column:world_id;type:uuid;not null;index:story_nodes_world_id_idx;index:story_nodes_world_id_depth_idx,priority:1;comment:Foreign key to the owning world." validate:"required" json:"worldId"`
	// Depth of this node in the story tree - root is 0.
	Depth int32 `gorm:"column:depth;type:integer;not null;index:story_nodes_depth_idx;index:story_nodes_world_id_depth_idx,priority:2;default:0;comment:Depth of this node in the story tree - root is 0." validate:"required" json:"depth"`
	// Content pool inherited from all ancestors.
	Pool datatypes.JSON `gorm:"column:pool;type:jsonb;not null;comment:Content pool inherited from all ancestors." validate:"required" json:"pool"`
	// Content introduced by this specific node.
	NewContent datatypes.JSON `gorm:"column:new_content;type:jsonb;not null;comment:Content introduced by this specific node." validate:"required" json:"newContent"`
	// IDs of lazily-expanded child nodes.
	ChildIDs datatypes.JSON `gorm:"column:child_ids;type:jsonb;not null;comment:IDs of lazily-expanded child nodes." validate:"required" json:"childIds"`
	// Searchable labels attached to the node for branch discovery.
	Tags     datatypes.JSONSlice[string] `gorm:"column:tags;type:jsonb;not null;comment:Searchable labels attached to the node for branch discovery." json:"tags"`
	ParentID *uuid.UUID                  `gorm:"column:parent_id;type:uuid" validate:"omitempty" json:"parentId,omitempty"`

	// ─── Relationships ─────────────────────
	// Owning world.
	World demo_game_platform_worlds.World `gorm:"foreignKey:WorldID;references:ID;constraint:OnDelete:CASCADE,OnUpdate:CASCADE" json:"world"`
	// Parent story node.
	Parent *StoryNode `gorm:"foreignKey:ParentID;references:ID;constraint:OnDelete:CASCADE" json:"parent,omitempty"`
	// Child nodes reachable from this node.
	Children []StoryNode `gorm:"foreignKey:ParentID;references:ID;constraint:OnDelete:CASCADE" json:"children,omitempty"`
}

// TableName returns the table name for StoryNode.
func (StoryNode) TableName() string {
	return "story_nodes"
}
