// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
	"github.com/google/uuid"

	entschema "entgo.io/ent/schema"
)


// MfaFactor Registered second factor. Secrets are encrypted outside the TypeSpec model.
type MfaFactor struct {
	ent.Schema
}

func (MfaFactor) Annotations() []entschema.Annotation {
	return []entschema.Annotation{
		entsql.Annotation{Table: "mfa_factors"},
		entsql.WithComments(true),
	}
}

func (MfaFactor) Mixin() []ent.Mixin {
	return []ent.Mixin{
		Entity{},
	}
}

func (MfaFactor) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("account_id", uuid.UUID{}),
		field.Enum("kind").Values("totp", "webauthn", "recovery_code"),
		field.String("label").
			MaxLen(120).
			Optional().
			Nillable(),
		field.String("secret_ref"),
		field.Time("verified_at").
			Optional().
			Nillable(),
		field.Time("disabled_at").
			Optional().
			Nillable(),
	}
}

func (MfaFactor) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("account", UserAccount.Type).
			Field("account_id").
			Unique().
			Required().
			Annotations(entsql.OnDelete(entsql.Cascade)),
	}
}

func (MfaFactor) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("account_id"),
	}
}
