# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from uuid import UUID
from datetime import datetime

from sqlalchemy import Column, DateTime
from sqlmodel import Field, SQLModel
from ..shared.entity import Entity


class AuditExportCheckpoint(Entity, table=True):
    """Outbox checkpoint for exporting audit events to external SIEM/storage."""

    __tablename__ = "audit_export_checkpoints"  # type: ignore

    sink_name: str = Field(
        unique=True, max_length=255, sa_column_kwargs={"nullable": False}
    )
    last_event_id: UUID | None = Field(default=None)
    exported_at: datetime | None = Field(
        default=None, sa_column=Column(DateTime(timezone=True))
    )
