# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from uuid import UUID
from enum import Enum

from pydantic import BaseModel, Field
from ..shared.string_pair import StringPair


class AuditSeverityCode(int, Enum):
    """Auto-generated enum for audit_severity_code."""

    unspecified = 0
    debug = 1
    info = 2
    warning = 3
    error = 4
    critical = 5


class AuditEventView(BaseModel):
    """AuditEventView"""

    id: UUID = Field(...)
    actor_id: UUID | None = Field(None)
    action: str = Field(...)
    resource_type: str = Field(...)
    resource_id: UUID | None = Field(None)
    severity: AuditSeverityCode = Field(...)
    created_at_iso: str = Field(...)
    metadata: list[StringPair] = Field(...)
