# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from uuid import UUID
from typing import Any
from enum import Enum

from sqlalchemy import Column, Enum as SAEnum
from sqlalchemy.dialects.postgresql import JSONB
from sqlmodel import Field, SQLModel
from ..shared.entity import Entity


class AuditSeverity(str, Enum):
    """Auto-generated enum for audit_severity."""

    info = "info"
    warning = "warning"
    critical = "critical"


class AuditEvent(Entity, table=True):
    """Append-only security and compliance event."""

    __tablename__ = "audit_events"  # type: ignore

    actor_id: UUID | None = Field(default=None, index=True)
    action: str = Field(max_length=160, sa_column_kwargs={"nullable": False})
    resource_type: str = Field(max_length=80, sa_column_kwargs={"nullable": False})
    resource_id: UUID | None = Field(default=None)
    severity: AuditSeverity = Field(
        sa_column=Column(SAEnum(AuditSeverity), nullable=False, server_default="info")
    )
    request_id: str | None = Field(default=None, max_length=255)
    ip_address_hash: str | None = Field(default=None, max_length=255)
    user_agent_hash: str | None = Field(default=None, max_length=255)
    metadata_json: dict[str, Any] | None = Field(default=None, sa_column=Column(JSONB))
