# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from pydantic import BaseModel, Field
from .audit_event_view import AuditEventView
from ..shared.page_info import PageInfo


class QueryAuditEventsResponse(BaseModel):
    """QueryAuditEventsResponse"""

    events: list[AuditEventView] = Field(...)
    page: PageInfo = Field(...)
