// Re-export library and state keys for consumers (emitters)
export { $lib } from "./lib.js";

/**
 * Emitter name used for generating "Code generated by X. DO NOT EDIT." header.
 * Other emitters import this to include the header in generated files.
 */
export const generatedHeader = "Code generated by @qninhdt/typespec-orm. DO NOT EDIT.";

/**
 * Compose a generated-file banner. Returns the canonical
 * `generatedHeader` marker by default; pass `extra` to prepend a license,
 * ticket link, or any service-specific preamble. The canonical marker is
 * always present so downstream tools can still detect generated files.
 */
export function buildGeneratedHeader(extra?: string): string {
  const trimmed = extra?.trim();
  if (!trimmed) return generatedHeader;
  return `${trimmed}\n${generatedHeader}`;
}
export {
  TableKey,
  TableMixinKey,
  MapKey,
  IndexKey,
  UniqueKey,
  CheckKey,
  AutoIncrementKey,
  SoftDeleteKey,
  ForeignKeyKey,
  MappedByKey,
  ManyToManyKey,
  AutoCreateTimeKey,
  AutoUpdateTimeKey,
  PrecisionKey,
  OnDeleteKey,
  OnUpdateKey,
  IgnoreKey,
  SchemaKey,
  DefaultExpressionKey,
  VersionKey,
  AuditKey,
  TenantIdKey,
  DataKey,
  TitleKey,
  PlaceholderKey,
  InputTypeKey,
  reportDiagnostic,
} from "./lib.js";

// ─── Validation hook ─────────────────────────────────────────────────────────
// Called by the TypeSpec compiler after all decorators are applied.

export { $onValidate } from "./validators.js";

// ─── Decorator namespace registration ────────────────────────────────────────
// TypeSpec resolves extern dec implementations via the $decorators export map.
// Individual $name functions must NOT be re-exported as top-level named exports
// to avoid "duplicate-symbol" errors with the extern dec declarations in the .tsp file.

import {
  $table,
  $tableMixin,
  $map,
  $index,
  $unique,
  $check,
  $autoIncrement,
  $softDelete,
  $foreignKey,
  $mappedBy,
  $manyToMany,
  $autoCreateTime,
  $autoUpdateTime,
  $precision,
  $onDelete,
  $onUpdate,
  $ignore,
  $schema,
  $defaultExpression,
  $version,
  $audit,
  $tenantId,
  $tableIndex,
  $tableUnique,
  $scope,
  $owner,
  $classification,
  $data,
  $title,
  $placeholder,
  $inputType,
} from "./decorators.js";

export const $decorators = {
  "Qninhdt.Orm": {
    table: $table,
    tableMixin: $tableMixin,
    map: $map,
    index: $index,
    unique: $unique,
    check: $check,
    autoIncrement: $autoIncrement,
    softDelete: $softDelete,
    foreignKey: $foreignKey,
    mappedBy: $mappedBy,
    manyToMany: $manyToMany,
    autoCreateTime: $autoCreateTime,
    autoUpdateTime: $autoUpdateTime,
    precision: $precision,
    onDelete: $onDelete,
    onUpdate: $onUpdate,
    ignore: $ignore,
    schema: $schema,
    defaultExpression: $defaultExpression,
    version: $version,
    audit: $audit,
    tenantId: $tenantId,
    tableIndex: $tableIndex,
    tableUnique: $tableUnique,
    scope: $scope,
    owner: $owner,
    classification: $classification,
    data: $data,
    title: $title,
    placeholder: $placeholder,
    inputType: $inputType,
  },
};

// Helper functions for emitters to read decorator state
export {
  isTable,
  isTableMixin,
  getTableName,
  getColumnName,
  isIndex,
  getIndexName,
  isUnique,
  getUniqueName,
  getCheck,
  getDefaultValue,
  isAutoIncrement,
  isSoftDelete,
  getMaxLength,
  getMinLength,
  getMinValue,
  getMaxValue,
  getPattern,
  getOrmScalarName,
  getCustomScalarName,
  getDoc,
  getForeignKey,
  getForeignKeyConfig,
  getForeignKeyTarget,
  getMappedBy,
  getManyToMany,
  getCompositeFields,
  isBuiltIn,
  isCustomScalar,
  collectCustomScalars,
  isAutoCreateTime,
  isAutoUpdateTime,
  getPrecision,
  getOnDelete,
  getOnUpdate,
  getSchemaName,
  getDefaultExpression,
  isVersionColumn,
  getAuditRole,
  isTenantIdColumn,
  findVersionProperty,
  findTenantIdProperty,
  getScopes,
  hasScope,
  getOwner,
  getClassification,
  isIgnored,
  isEnum,
  getEnumMembers,
  getPropertyEnum,
  getScalarChain,
  resolveDbType,
  camelToSnake,
  camelToPascal,
  deriveTableName,
  getNamespaceFullName,
  getNamespaceSegments,
  getTypeFullName,
  collectOrmManagedModels,
  collectTableModels,
  collectTableMixins,
  getModelOwnProperties,
  isOrmManagedModel,
  // Auto-relation detection
  findPrimaryKey,
  unwrapArrayType,
  collectManyToManyAssociations,
  deriveManyToManyJoinColumnName,
  resolvePropertyReference,
  arePropertyTypesCompatible,
  describeComparableType,
  isRelationLocalKeyUnique,
  resolveRelation,
  // Data / form helpers
  isData,
  getDataLabel,
  getTitle,
  collectDataModels,
  getPlaceholder,
  getInputType,
  getInputTypeForProperty,
  // Extended validation helpers
  isKey,
  isArrayType,
  getArrayElementType,
  getMaxItems,
  getMinItems,
  getMinValueExclusive,
  getMaxValueExclusive,
  getValidators,
} from "./helpers.js";

export type {
  ResolvedRelation,
  ForeignKeyConfig,
  CheckConstraintInfo,
  ManyToManyAssociation,
  PrecisionInfo,
  EnumMemberInfo,
  TableModel,
  ValidatorInfo,
} from "./helpers.js";

// ─── Shared emitter utilities ────────────────────────────────────────────────
export {
  NUMERIC_TYPES,
  deduplicateParts,
  classifyProperties,
  collectCompositeTypeFields,
  buildCompositeUniqueColumns,
} from "./emitter-utils.js";

export type {
  ClassifiedProperty,
  ClassifiedRelation,
  ClassifiedProperties,
  CompositeTypeField,
} from "./emitter-utils.js";

export {
  normalizeOrmGraph,
  selectModelsForEmitter,
  selectorMatchesName,
  getRelativeImportPath,
  getLibraryLeafName,
} from "./normalization.js";

export type {
  NormalizedOrmGraph,
  NormalizedOrmModel,
  NormalizedDependency,
  OrmSelector,
  OrmEmitterSelection,
} from "./normalization.js";

// ─── Emitter bootstrap ──────────────────────────────────────────────────────
export { bootstrapEmitter, isBootstrapSuccess } from "./emitter-bootstrap.js";

export {
  PG_MAX_IDENTIFIER_LENGTH,
  PG_RESERVED_WORDS,
  truncatePgIdentifier,
  isPgReservedWord,
} from "./identifier-policy.js";

export type {
  EmitterBootstrapConfig,
  EmitterBootstrapResult,
  BootstrapFailure,
} from "./emitter-bootstrap.js";
