// Re-export library and state keys for consumers (emitters)
export { $lib } from "./lib.js";

/**
 * Emitter name used for generating "Code generated by X. DO NOT EDIT." header.
 * Other emitters import this to include the header in generated files.
 */
export const generatedHeader = "Code generated by @qninhdt/typespec-orm. DO NOT EDIT.";
export {
  TableKey,
  TableMixinKey,
  MapKey,
  IndexKey,
  UniqueKey,
  AutoIncrementKey,
  SoftDeleteKey,
  ForeignKeyKey,
  MappedByKey,
  AutoCreateTimeKey,
  AutoUpdateTimeKey,
  PrecisionKey,
  OnDeleteKey,
  OnUpdateKey,
  IgnoreKey,
  DataKey,
  TitleKey,
  PlaceholderKey,
  InputTypeKey,
  reportDiagnostic,
} from "./lib.js";

// ─── Validation hook ─────────────────────────────────────────────────────────
// Called by the TypeSpec compiler after all decorators are applied.

export { $onValidate } from "./validators.js";

// ─── Decorator namespace registration ────────────────────────────────────────
// TypeSpec resolves extern dec implementations via the $decorators export map.
// Individual $name functions must NOT be re-exported as top-level named exports
// to avoid "duplicate-symbol" errors with the extern dec declarations in the .tsp file.

import {
  $table,
  $tableMixin,
  $map,
  $index,
  $unique,
  $autoIncrement,
  $softDelete,
  $foreignKey,
  $mappedBy,
  $autoCreateTime,
  $autoUpdateTime,
  $precision,
  $onDelete,
  $onUpdate,
  $ignore,
  $data,
  $title,
  $placeholder,
  $inputType,
} from "./decorators.js";

export const $decorators = {
  "Qninhdt.Orm": {
    table: $table,
    tableMixin: $tableMixin,
    map: $map,
    index: $index,
    unique: $unique,
    autoIncrement: $autoIncrement,
    softDelete: $softDelete,
    foreignKey: $foreignKey,
    mappedBy: $mappedBy,
    autoCreateTime: $autoCreateTime,
    autoUpdateTime: $autoUpdateTime,
    precision: $precision,
    onDelete: $onDelete,
    onUpdate: $onUpdate,
    ignore: $ignore,
    data: $data,
    title: $title,
    placeholder: $placeholder,
    inputType: $inputType,
  },
};

// Helper functions for emitters to read decorator state
export {
  isTable,
  isTableMixin,
  getTableName,
  getColumnName,
  isIndex,
  getIndexName,
  isUnique,
  getUniqueName,
  getDefaultValue,
  isAutoIncrement,
  isSoftDelete,
  getMaxLength,
  getMinLength,
  getMinValue,
  getMaxValue,
  getPattern,
  getFormat,
  getDoc,
  getForeignKey,
  getMappedBy,
  getCompositeFields,
  isAutoCreateTime,
  isAutoUpdateTime,
  getPrecision,
  getOnDelete,
  getOnUpdate,
  isIgnored,
  isEnum,
  getEnumMembers,
  getPropertyEnum,
  getScalarChain,
  resolveDbType,
  camelToSnake,
  camelToPascal,
  deriveTableName,
  getNamespaceFullName,
  getNamespaceSegments,
  getTypeFullName,
  collectTableModels,
  collectTableMixins,
  // Auto-relation detection
  findPrimaryKey,
  unwrapArrayType,
  resolveRelation,
  // Data / form helpers
  isData,
  getDataLabel,
  getTitle,
  collectDataModels,
  getPlaceholder,
  getInputType,
  // Extended validation helpers
  isKey,
  isArrayType,
  getArrayElementType,
  getMaxItems,
  getMinItems,
  getMinValueExclusive,
  getMaxValueExclusive,
  getValidators,
} from "./helpers.js";

export type {
  ResolvedRelation,
  PrecisionInfo,
  EnumMemberInfo,
  TableModel,
  ValidatorInfo,
} from "./helpers.js";

// ─── Shared emitter utilities ────────────────────────────────────────────────
export {
  NUMERIC_TYPES,
  deduplicateParts,
  classifyProperties,
  collectCompositeTypeFields,
  buildCompositeUniqueColumns,
} from "./emitter-utils.js";

export type {
  ClassifiedProperty,
  ClassifiedRelation,
  ClassifiedProperties,
  CompositeTypeField,
} from "./emitter-utils.js";

export {
  normalizeOrmGraph,
  selectModelsForEmitter,
  selectorMatchesName,
  getRelativeImportPath,
  getLibraryLeafName,
} from "./normalization.js";

export type {
  NormalizedOrmGraph,
  NormalizedOrmModel,
  NormalizedDependency,
  OrmSelector,
  OrmEmitterSelection,
} from "./normalization.js";
