// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package sharing

import (
	"github.com/google/uuid"
)

// CreateShareLinkRequest CreateShareLinkRequest
type CreateShareLinkRequest struct {
	ResourceNodeID uuid.UUID `validate:"required" json:"resourceNodeId"`
	CreatedBy uuid.UUID `validate:"required" json:"createdBy"`
	Role ShareRoleCode `validate:"oneof=0 1 2 3 4" json:"role"`
	ExpiresAtIso *string `validate:"omitempty" json:"expiresAtIso,omitempty"`
	Password *string `validate:"omitempty" json:"password,omitempty"`
}
