// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package sharing

import (
	"github.com/google/uuid"
)

// CreateShareGrantRequest CreateShareGrantRequest
type CreateShareGrantRequest struct {
	ResourceNodeID uuid.UUID `validate:"required" json:"resourceNodeId"`
	GrantedBy uuid.UUID `validate:"required" json:"grantedBy"`
	SubjectKind ShareSubjectKindCode `validate:"oneof=0 1 2 3" json:"subjectKind"`
	Subject string `validate:"required" json:"subject"`
	Role ShareRoleCode `validate:"oneof=0 1 2 3 4" json:"role"`
	ExpiresAtIso *string `validate:"omitempty" json:"expiresAtIso,omitempty"`
}
