// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package sharing

// ShareSubjectKindCode represents the share_subject_kind_code enum.
type ShareSubjectKindCode int32

const (
	ShareSubjectKindCodeShareSubjectKindUnspecified ShareSubjectKindCode = 0
	ShareSubjectKindCodeAccount ShareSubjectKindCode = 1
	ShareSubjectKindCodeGroup ShareSubjectKindCode = 2
	ShareSubjectKindCodePublicLink ShareSubjectKindCode = 3
)

// ShareRoleCode represents the share_role_code enum.
type ShareRoleCode int32

const (
	ShareRoleCodeShareRoleUnspecified ShareRoleCode = 0
	ShareRoleCodeViewer ShareRoleCode = 1
	ShareRoleCodeCommenter ShareRoleCode = 2
	ShareRoleCodeEditor ShareRoleCode = 3
	ShareRoleCodeOwner ShareRoleCode = 4
)

