// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package sharing

import (
	file_vault_shared "github.com/example/file-vault/sharing-svc/file_vault/shared"
)

// ListSharesResponse ListSharesResponse
type ListSharesResponse struct {
	Grants []ShareGrantView `json:"grants"`
	Links []ShareLinkView `json:"links"`
	Page file_vault_shared.PageInfo `json:"page"`
}
