// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package sharing

import (
	"github.com/google/uuid"
)

// RevokeShareGrantRequest RevokeShareGrantRequest
type RevokeShareGrantRequest struct {
	GrantID uuid.UUID `validate:"required" json:"grantId"`
	RevokedBy uuid.UUID `validate:"required" json:"revokedBy"`
}
