// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package sharing

import (
	"github.com/google/uuid"
)

// ShareLinkView ShareLinkView
type ShareLinkView struct {
	ID uuid.UUID `validate:"required" json:"id"`
	ResourceNodeID uuid.UUID `validate:"required" json:"resourceNodeId"`
	URL string `validate:"required" json:"url"`
	Role ShareRoleCode `validate:"oneof=0 1 2 3 4" json:"role"`
	ExpiresAtIso *string `validate:"omitempty" json:"expiresAtIso,omitempty"`
}
