# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from uuid import UUID

from pydantic import BaseModel, Field


class BeginUploadRequest(BaseModel):
    """BeginUploadRequest"""

    account_id: UUID = Field(...)
    file_name: str = Field(...)
    media_type: str = Field(...)
    expected_size_bytes: int = Field(...)
    expected_sha256: str | None = Field(None)
