# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from uuid import UUID

from pydantic import BaseModel, Field


class BeginUploadResponse(BaseModel):
    """BeginUploadResponse"""

    upload_session_id: UUID = Field(...)
    storage_object_id: UUID = Field(...)
    signed_upload_url: str | None = Field(None)
    expires_at_iso: str = Field(...)
