# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from sqlalchemy import text
from sqlmodel import Field, SQLModel
from ..shared.entity import Entity


class StorageBucket(Entity, table=True):
    """Physical storage bucket or logical provider namespace."""

    __tablename__ = "storage_buckets"  # type: ignore

    name: str = Field(unique=True, max_length=120, sa_column_kwargs={"nullable": False})
    provider: str = Field(max_length=80, sa_column_kwargs={"nullable": False})
    region: str = Field(max_length=80, sa_column_kwargs={"nullable": False})
    default_encryption: bool = Field(
        sa_column_kwargs={"nullable": False, "server_default": text("true")}
    )
