# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from typing import TYPE_CHECKING
from uuid import UUID
from enum import Enum

from sqlalchemy import Column, Enum as SAEnum, ForeignKey
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlmodel import Field, Relationship, SQLModel
from ..shared.entity import Entity


if TYPE_CHECKING:
    from .storage_bucket import StorageBucket


class StorageObjectState(str, Enum):
    """Auto-generated enum for storage_object_state."""

    pending = "pending"
    available = "available"
    quarantined = "quarantined"
    deleted = "deleted"


class StorageObject(Entity, table=True):
    """Physical object. Metadata service references this by id."""

    __tablename__ = "storage_objects"  # type: ignore

    bucket_id: UUID = Field(
        sa_column=Column(
            PG_UUID(as_uuid=True),
            ForeignKey("storage_buckets.id", ondelete="RESTRICT"),
            nullable=False,
            index=True,
        )
    )
    object_key: str = Field(
        unique=True, max_length=255, sa_column_kwargs={"nullable": False}
    )
    size_bytes: int = Field(sa_column_kwargs={"nullable": False})
    sha256: str = Field(max_length=128, sa_column_kwargs={"nullable": False})
    media_type: str = Field(max_length=160, sa_column_kwargs={"nullable": False})
    state: StorageObjectState = Field(
        sa_column=Column(
            SAEnum(StorageObjectState), nullable=False, server_default="pending"
        )
    )
    encryption_key_ref: str | None = Field(default=None, max_length=255)

    # ─── Relationships ─────────────────────
    bucket: StorageBucket | None = Relationship()
