# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from uuid import UUID
from enum import Enum

from pydantic import BaseModel, Field


class StorageObjectStateCode(int, Enum):
    """Auto-generated enum for storage_object_state_code."""

    unspecified = 0
    pending = 1
    available = 2
    quarantined = 3
    deleted = 4


class StorageObjectView(BaseModel):
    """StorageObjectView"""

    id: UUID = Field(...)
    bucket: str = Field(...)
    object_key: str = Field(...)
    size_bytes: int = Field(...)
    sha256: str = Field(...)
    media_type: str = Field(...)
    state: StorageObjectStateCode = Field(...)
