# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from typing import TYPE_CHECKING
from uuid import UUID
from datetime import datetime
from enum import Enum

from sqlalchemy import Column, DateTime, Enum as SAEnum, ForeignKey
from sqlmodel import Field, Relationship, SQLModel
from ..shared.entity import Entity


if TYPE_CHECKING:
    from .storage_bucket import StorageBucket
    from ..identity.user_account import UserAccount


class UploadState(str, Enum):
    """Auto-generated enum for upload_state."""

    initiated = "initiated"
    receiving = "receiving"
    completed = "completed"
    aborted = "aborted"
    expired = "expired"


class UploadSession(Entity, table=True):
    """Durable upload session for chunked or signed-url uploads."""

    __tablename__ = "upload_sessions"  # type: ignore

    account_id: UUID = Field(
        sa_column=Column(
            ForeignKey("user_accounts.id", ondelete="CASCADE"),
            nullable=False,
            index=True,
        )
    )
    bucket_id: UUID = Field(
        index=True,
        foreign_key="storage_buckets.id",
        sa_column_kwargs={"nullable": False},
    )
    storage_object_id: UUID | None = Field(default=None, index=True)
    file_name: str = Field(max_length=240, sa_column_kwargs={"nullable": False})
    expected_size_bytes: int = Field(sa_column_kwargs={"nullable": False})
    state: UploadState = Field(
        sa_column=Column(
            SAEnum(UploadState), nullable=False, server_default="initiated"
        )
    )
    expires_at: datetime = Field(
        sa_column=Column(DateTime(timezone=True), nullable=False)
    )
    completed_at: datetime | None = Field(
        default=None, sa_column=Column(DateTime(timezone=True))
    )

    # ─── Relationships ─────────────────────
    account: UserAccount | None = Relationship()
    bucket: StorageBucket | None = Relationship()
