# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from uuid import UUID

from pydantic import BaseModel, Field


class UploadChunk(BaseModel):
    """UploadChunk"""

    upload_session_id: UUID = Field(...)
    part_number: int = Field(...)
    offset_bytes: int = Field(...)
    data: bytes = Field(...)
    final_chunk: bool = Field(...)
