# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from uuid import UUID

from pydantic import BaseModel, Field


class UploadReceipt(BaseModel):
    """UploadReceipt"""

    upload_session_id: UUID = Field(...)
    bytes_received: int = Field(...)
    part_count: int = Field(...)
