# Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
# Source: https://github.com/qninhdt/typespec-libraries

from pydantic import BaseModel, EmailStr, Field


class CreateWorldForm(BaseModel):
    """Form payload for creating or editing a world. Demonstrates cross-namespace lookup types pulled from multiple bounded contexts."""

    # Display name of the world. Referenced by forms and collaboration models through lookup types.
    name: str = Field(
        ...,
        max_length=200,
        title="World Name",
        description="Display name of the world. Referenced by forms and collaboration models through lookup types.",
        json_schema_extra={"placeholder": "Chronicles of Emberfall"},
    )
    # System prompt used to guide AI generation within the world.
    prompt: str = Field(
        ...,
        title="World Prompt",
        description="System prompt used to guide AI generation within the world.",
    )
    # Email address used for login and invitations. Other namespaces reference this via lookup types.
    owner_email: EmailStr = Field(
        ...,
        max_length=320,
        title="Owner Email",
        description="Email address used for login and invitations. Other namespaces reference this via lookup types.",
    )
    # Tag name - unique within a world.
    starter_tag: str = Field(
        ...,
        max_length=100,
        title="Starter Tag",
        description="Tag name - unique within a world.",
    )
    # Name of the NPC - indexed for lookup.
    featured_npc: str = Field(
        ...,
        max_length=200,
        title="Featured NPC",
        description="Name of the NPC - indexed for lookup.",
    )
    summary: str | None = Field(
        None,
        title="Summary",
        json_schema_extra={"placeholder": "Describe the setting, themes, and tone."},
    )
