// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package invites

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"

	demo_game_platform_accounts "github.com/demo-user/demo/demo/game_platform/accounts"
	demo_game_platform_worlds "github.com/demo-user/demo/demo/game_platform/worlds"
)

// InvitationStatus represents the invitation_status enum.
type InvitationStatus string

const (
	InvitationStatusPending  InvitationStatus = "pending"
	InvitationStatusAccepted InvitationStatus = "accepted"
	InvitationStatusRevoked  InvitationStatus = "revoked"
	InvitationStatusExpired  InvitationStatus = "expired"
)

// Invitation Invitation record linking a user email to a shared world. Demonstrates cross-namespace lookup types and relations on the same table.
type Invitation struct {
	// Unique identifier shared by most persisted records.
	ID uuid.UUID `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid();comment:Unique identifier shared by most persisted records." json:"id"`
	// Timestamp when the record was created.
	CreatedAt time.Time `gorm:"column:created_at;type:timestamptz;autoCreateTime;not null;comment:Timestamp when the record was created." json:"createdAt"`
	// Timestamp of the last update.
	UpdatedAt *time.Time `gorm:"column:updated_at;type:timestamptz;comment:Timestamp of the last update." validate:"omitempty" json:"updatedAt,omitempty"`
	// Soft delete marker for archival workflows.
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;index;comment:Soft delete marker for archival workflows." json:"deletedAt"`
	// Email of the invitee - inherits validators from Accounts.User.email.
	InviteeEmail string `gorm:"column:invitee_email;type:varchar(320);not null;comment:Email of the invitee - inherits validators from Accounts.User.email." validate:"required,max=320,email" json:"inviteeEmail"`
	// Unique redeem code sent through email or copied in the UI.
	RedeemCode string `gorm:"column:redeem_code;type:varchar(64);not null;uniqueIndex:world_invitations_redeem_code_unique;comment:Unique redeem code sent through email or copied in the UI." validate:"required,max=64" json:"redeemCode"`
	// Current lifecycle state for the invitation.
	Status InvitationStatus `gorm:"column:status;type:varchar(20);not null;index:world_invitations_status_idx;index:world_invitations_inviter_id_status_idx,priority:2;default:pending;comment:Current lifecycle state for the invitation." validate:"oneof=pending,accepted,revoked,expired" json:"status"`
	// Optional personal note from the inviter.
	Message *string `gorm:"column:message;type:text;comment:Optional personal note from the inviter." validate:"omitempty,max=1000" json:"message,omitempty"`
	// When the invitation expires, if at all.
	ExpiresAt *time.Time `gorm:"column:expires_at;type:timestamptz;comment:When the invitation expires, if at all." validate:"omitempty" json:"expiresAt,omitempty"`
	// When the invitation was accepted by the recipient.
	AcceptedAt *time.Time `gorm:"column:accepted_at;type:timestamptz;comment:When the invitation was accepted by the recipient." validate:"omitempty" json:"acceptedAt,omitempty"`
	InviterID  uuid.UUID  `gorm:"column:inviter_id;type:uuid;not null;index:world_invitations_inviter_id_status_idx,priority:1" validate:"required" json:"inviterId"`
	WorldID    uuid.UUID  `gorm:"column:world_id;type:uuid;not null" validate:"required" json:"worldId"`

	// ─── Relationships ─────────────────────
	// User who created the invitation.
	Inviter demo_game_platform_accounts.User `gorm:"foreignKey:InviterID;constraint:OnDelete:CASCADE,OnUpdate:CASCADE" json:"inviter"` // World the invite grants access to.
	World   demo_game_platform_worlds.World  `gorm:"foreignKey:WorldID;constraint:OnDelete:CASCADE,OnUpdate:CASCADE" json:"world"`
}

// TableName returns the table name for Invitation.
func (Invitation) TableName() string {
	return "world_invitations"
}
