// Code generated by @qninhdt/typespec-orm. DO NOT EDIT.
// Source: https://github.com/qninhdt/typespec-libraries

package worlds

// CreateWorldForm Form payload for creating or editing a world. Demonstrates cross-namespace lookup types pulled from multiple bounded contexts.
type CreateWorldForm struct {
	// Display name of the world. Referenced by forms and collaboration models through lookup types.
	Name string `validate:"required,max=200" json:"name" form:"name,title=World Name,placeholder=Chronicles of Emberfall"`
	// System prompt used to guide AI generation within the world.
	Prompt string `validate:"required" json:"prompt" form:"prompt,title=World Prompt"`
	// Email address used for login and invitations. Other namespaces reference this via lookup types.
	OwnerEmail string `validate:"required,max=320,email" json:"ownerEmail" form:"ownerEmail,title=Owner Email"`
	// Tag name - unique within a world.
	StarterTag string `validate:"required,max=100" json:"starterTag" form:"starterTag,title=Starter Tag"`
	// Name of the NPC - indexed for lookup.
	FeaturedNpc string  `validate:"required,max=200" json:"featuredNpc" form:"featuredNpc,title=Featured NPC"`
	Summary     *string `validate:"omitempty" json:"summary,omitempty" form:"summary,title=Summary,placeholder=Describe the setting  themes  and tone."`
}
